//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DKDiagnosticController.h"

@class LightningControllerHardwareAuthenticationInputs;

@interface LightningControllerHardwareAuthenticationController : DKDiagnosticController
{
    LightningControllerHardwareAuthenticationInputs *_inputs;
}

@property(retain, nonatomic) LightningControllerHardwareAuthenticationInputs *inputs; // @synthesize inputs=_inputs;
- (void).cxx_destruct;
- (long long)base64EncodeData:(id)arg1 result:(id *)arg2;
- (void)disconnect:(unsigned int *)arg1;
- (long long)issueChallenge:(id)arg1 keyIndex:(int)arg2 response:(id *)arg3 options:(unsigned long long)arg4 connection:(unsigned int)arg5;
- (long long)connect:(unsigned int *)arg1;
- (void)start;
- (void)setupWithInputs:(id)arg1 responder:(id)arg2;

@end

