//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "DKDiagnosticInputs.h"

@class NSData, NSString;

@interface LightningControllerHardwareAuthenticationInputs : NSObject <DKDiagnosticInputs>
{
    int _keyIndex;
    NSData *_challenge;
}

@property(nonatomic) int keyIndex; // @synthesize keyIndex=_keyIndex;
@property(retain, nonatomic) NSData *challenge; // @synthesize challenge=_challenge;
- (void).cxx_destruct;
- (_Bool)_applyKeyIndexParameter:(id)arg1;
- (_Bool)_applyChallengeParameter:(id)arg1;
- (_Bool)validateAndInitializeParameters:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

