//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "LABackoffCounter.h"

@interface LocalBackoffCounter : NSObject <LABackoffCounter>
{
}

- (void)currentBackoffErrorWithReply:(CDUnknownBlockType)arg1;
- (void)actionSuccess;
- (void)actionBackoffWithReply:(CDUnknownBlockType)arg1;
- (void)actionFailureWithReply:(CDUnknownBlockType)arg1;

@end

