//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class LAUIPearlGlyphView, NSString, UIImageView, UIView, _UIBackdropView;

@interface ToastViewController : UIViewController
{
    _UIBackdropView *_backdropView;
    UIImageView *_backdropMaskImageView;
    UIView *_toastView;
    LAUIPearlGlyphView *_glyphView;
    NSString *_titleText;
}

@property(copy, nonatomic) NSString *titleText; // @synthesize titleText=_titleText;
@property(nonatomic) __weak LAUIPearlGlyphView *glyphView; // @synthesize glyphView=_glyphView;
@property(retain, nonatomic) UIView *toastView; // @synthesize toastView=_toastView;
- (void).cxx_destruct;
- (long long)preferredStatusBarStyle;
- (int)_preferredStatusBarVisibility;
- (void)dismissWithDelay:(double)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_updateBackdropMask;
- (void)viewDidLayoutSubviews;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (id)initWithGlyph:(id)arg1 title:(id)arg2;

@end

