//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ADBannerViewDelegate.h"

@class ADBannerView, NSString;

@interface ADPreviewAdLoader : NSObject <ADBannerViewDelegate>
{
    int _adType;
    ADBannerView *_bannerView;
    long long _numberOfAttempts;
}

+ (id)instance;
@property(nonatomic) int adType; // @synthesize adType=_adType;
@property(nonatomic) long long numberOfAttempts; // @synthesize numberOfAttempts=_numberOfAttempts;
@property(retain, nonatomic) ADBannerView *bannerView; // @synthesize bannerView=_bannerView;
- (void)dealloc;
- (void)bannerViewActionDidFinish:(id)arg1;
- (void)bannerViewDidLoadAd:(id)arg1;
- (void)bannerView:(id)arg1 didFailToReceiveAdWithError:(id)arg2;
- (id)loadedBannerView;
- (void)loadBanner:(int)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

