//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SAMovieV2MovieTheater.h"

@interface SAMovieV2MovieTheater (MapsSession)
- (id)_afui_mapsRelatedChildren;
- (id)_afui_mapsRelatedChild;
@end

