//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SVSStarkGatekeeperHeaderView.h"

@class UIButton;

@interface SVSStarkCancelButtonGatekeeperHeaderView : SVSStarkGatekeeperHeaderView
{
    UIButton *_cancelButton;
}

@property(readonly, nonatomic, getter=_cancelButton) UIButton *cancelButton; // @synthesize cancelButton=_cancelButton;
- (void).cxx_destruct;
- (id)preferredFocusEnvironments;
- (void)_cancelButtonTapped:(id)arg1;
- (void)layoutSubviews;
- (id)initWithAceObject:(id)arg1;
- (id)initWithRequestOptions:(id)arg1;
- (void)_initialize;

@end

