//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DKDiagnosticController.h"

#import "HDDiagnosticHost.h"

@class NSString, PearlErrorDataInputs;

@interface PearlErrorDataController : DKDiagnosticController <HDDiagnosticHost>
{
    PearlErrorDataInputs *_inputs;
}

@property(retain, nonatomic) PearlErrorDataInputs *inputs; // @synthesize inputs=_inputs;
- (void).cxx_destruct;
- (id)workingDirectory;
- (id)retrieveAssetByName:(id)arg1 error:(id *)arg2;
- (id)runRequestedHardwareDiagnostic:(id)arg1 error:(id *)arg2;
- (id)findRequestedHardwareDiagnostic:(id *)arg1;
- (void)finishWithError:(id)arg1;
- (id)processResultsForReport:(id)arg1;
- (void)start;
- (void)setupWithInputs:(id)arg1 responder:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

