//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSObject<OS_dispatch_queue>;

__attribute__((visibility("hidden")))
@interface MAGAutoBrightnessManager : NSObject
{
    NSObject<OS_dispatch_queue> *_brightnessQueue;
    CDUnknownBlockType _cameraBrightnessUpdateBlock;
    double *_samples;
    long long _index;
    double _requestStartTime;
}

- (void).cxx_destruct;
- (void)_cleanup;
- (double)_normalizeCameraBrightness:(double)arg1;
- (void)sampleCameraBrightnessIfNeeded:(struct opaqueCMSampleBuffer *)arg1;
- (void)requestCameraBrightnessUpdate:(CDUnknownBlockType)arg1;
- (void)dealloc;
- (id)init;

@end

