//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIControl.h"

@class CALayer, MAGFilterSetChangeSubscription, MAGNamedFilterSet, NSDictionary, UISwipeGestureRecognizer, UITapGestureRecognizer, UIView;

__attribute__((visibility("hidden")))
@interface MAGFilterLabelDial : UIControl
{
    MAGNamedFilterSet *_selectedFilterSet;
    NSDictionary *_filterSetToLabelMap;
    UIView *_meshView;
    UIView *_labelContainer;
    CALayer *_maskLayer;
    UISwipeGestureRecognizer *_rightSwipeGestureRecognizer;
    UISwipeGestureRecognizer *_leftSwipeGestureRecognizer;
    UITapGestureRecognizer *_tapGestureRecognizer;
    MAGFilterSetChangeSubscription *_changeSubscription;
}

@property(retain, nonatomic) MAGFilterSetChangeSubscription *changeSubscription; // @synthesize changeSubscription=_changeSubscription;
@property(retain, nonatomic) UITapGestureRecognizer *tapGestureRecognizer; // @synthesize tapGestureRecognizer=_tapGestureRecognizer;
@property(retain, nonatomic) UISwipeGestureRecognizer *leftSwipeGestureRecognizer; // @synthesize leftSwipeGestureRecognizer=_leftSwipeGestureRecognizer;
@property(retain, nonatomic) UISwipeGestureRecognizer *rightSwipeGestureRecognizer; // @synthesize rightSwipeGestureRecognizer=_rightSwipeGestureRecognizer;
@property(retain, nonatomic) CALayer *maskLayer; // @synthesize maskLayer=_maskLayer;
@property(retain, nonatomic) UIView *labelContainer; // @synthesize labelContainer=_labelContainer;
@property(retain, nonatomic) UIView *meshView; // @synthesize meshView=_meshView;
@property(retain, nonatomic) NSDictionary *filterSetToLabelMap; // @synthesize filterSetToLabelMap=_filterSetToLabelMap;
@property(retain, nonatomic) MAGNamedFilterSet *selectedFilterSet; // @synthesize selectedFilterSet=_selectedFilterSet;
- (void).cxx_destruct;
- (void)accessibilityDecrement;
- (void)accessibilityIncrement;
- (unsigned long long)accessibilityTraits;
- (id)accessibilityLabel;
- (id)accessibilityValue;
- (_Bool)isAccessibilityElement;
- (void)positionLabels;
- (void)setSelectedFilterSet:(id)arg1 animated:(_Bool)arg2;
- (void)setSelectedFilterSet:(id)arg1 animated:(_Bool)arg2 sendActions:(_Bool)arg3;
- (void)tapped:(id)arg1;
- (void)leftSwipeFired:(id)arg1;
- (void)rightSwipeFired:(id)arg1;
- (id)previousFilterSet;
- (id)nextFilterSet;
- (void)layoutSubviews;
- (void)tintColorDidChange;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)_horizontalMeshTransform;
- (struct CGSize)_interpolatedHorizontalMeshTransformSize;

@end

