//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIAccessibilityElement.h"

@class NSObject<MAGSnapshotCanvasAccessibilityElementDelegate>;

__attribute__((visibility("hidden")))
@interface MAGSnapshotCanvasAccessibilityElement : UIAccessibilityElement
{
    NSObject<MAGSnapshotCanvasAccessibilityElementDelegate> *_delegate;
}

@property(nonatomic) __weak NSObject<MAGSnapshotCanvasAccessibilityElementDelegate> *delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)accessibilityDecrement;
- (void)accessibilityIncrement;
- (id)accessibilityHint;
- (id)accessibilityValue;
- (id)accessibilityLabel;
- (unsigned long long)accessibilityTraits;

@end

