//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HKViewController.h"

#import "HKAuthorizationSettingsViewControllerDelegate.h"
#import "HKDocumentPickerViewControllerDelegate.h"
#import "HKHealthPrivacyServiceRemoteViewController.h"

@class BKSApplicationStateMonitor, HKAuthorizationRequestRecord, HKAuthorizationSettingsViewController, HKDocumentPickerViewController, HKHealthStore, HKNavigationController, HKObjectAuthorizationPromptSession, NSError, NSString, NSUUID;

@interface WDHealthPrivacyServiceViewController : HKViewController <HKHealthPrivacyServiceRemoteViewController, HKAuthorizationSettingsViewControllerDelegate, HKDocumentPickerViewControllerDelegate>
{
    HKHealthStore *_healthStore;
    HKNavigationController *_navigationController;
    HKAuthorizationSettingsViewController *_authorizationSettingsController;
    HKDocumentPickerViewController *_documentPickerController;
    NSError *_transactionError;
    HKAuthorizationRequestRecord *_requestRecord;
    HKObjectAuthorizationPromptSession *_promptSession;
    NSUUID *_sessionIdentifier;
    BKSApplicationStateMonitor *_applicationStateMonitor;
}

+ (id)_exportedInterface;
+ (id)_remoteViewControllerInterface;
@property(retain, nonatomic) BKSApplicationStateMonitor *applicationStateMonitor; // @synthesize applicationStateMonitor=_applicationStateMonitor;
@property(copy, nonatomic) NSUUID *sessionIdentifier; // @synthesize sessionIdentifier=_sessionIdentifier;
@property(retain, nonatomic) HKObjectAuthorizationPromptSession *promptSession; // @synthesize promptSession=_promptSession;
@property(retain, nonatomic) HKAuthorizationRequestRecord *requestRecord; // @synthesize requestRecord=_requestRecord;
@property(retain, nonatomic) NSError *transactionError; // @synthesize transactionError=_transactionError;
@property(retain, nonatomic) HKDocumentPickerViewController *documentPickerController; // @synthesize documentPickerController=_documentPickerController;
@property(retain, nonatomic) HKAuthorizationSettingsViewController *authorizationSettingsController; // @synthesize authorizationSettingsController=_authorizationSettingsController;
@property(retain, nonatomic) HKNavigationController *navigationController; // @synthesize navigationController=_navigationController;
@property(retain, nonatomic) HKHealthStore *healthStore; // @synthesize healthStore=_healthStore;
- (void).cxx_destruct;
- (id)_healthPrivacyHostViewController;
- (void)_finishWithError:(id)arg1;
- (void)documentPickerViewControllerDidFinish:(id)arg1 error:(id)arg2;
- (void)authorizationSettingsViewControllerDidFinish:(id)arg1 error:(id)arg2;
- (void)viewDidLoad;
- (void)_configureNavigationController;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)_hostDidTerminate;
- (void)_beginAuthorizationSessionWithIdentifier:(id)arg1;
- (void)_configureApplicationStateMonitor;
- (void)_hostApplicationStateDidChange:(unsigned int)arg1;
- (void)setRequestRecord:(id)arg1 updateDescription:(id)arg2 shareDescription:(id)arg3;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

