//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MultiTouchHelper : NSObject
{
}

- (id)isPowerConnected;
- (id)isBatteryCharging;
- (id)celsiusTemperatureFromService:(struct __IOHIDServiceClient *)arg1;
- (id)parseHIDLocationID:(int)arg1;
- (id)temperatureData;

@end

