//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSMutableArray, NSOperation;

@interface STSDownloadOperationInfo : NSObject
{
    NSMutableArray *_beginBlocks;
    NSMutableArray *_progressBlocks;
    NSMutableArray *_completionBlocks;
    NSOperation *_operation;
}

@property(readonly, nonatomic) NSOperation *operation; // @synthesize operation=_operation;
- (void).cxx_destruct;
- (void)addCompletion:(CDUnknownBlockType)arg1;
- (void)addProgress:(CDUnknownBlockType)arg1;
- (void)addBegin:(CDUnknownBlockType)arg1;
@property(readonly, copy, nonatomic) NSArray *completionBlocks;
@property(readonly, copy, nonatomic) NSArray *progressBlocks;
- (id)beginBlocks;
- (id)initWithOperation:(id)arg1 begin:(CDUnknownBlockType)arg2 progress:(CDUnknownBlockType)arg3 completion:(CDUnknownBlockType)arg4;

@end

