//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSURLSessionDownloadDelegate.h"

@class NSMutableDictionary, NSObject<OS_dispatch_queue>, NSOperationQueue, NSString, NSURLCache, NSURLSession, UIImage;

@interface STSImageCache : NSObject <NSURLSessionDownloadDelegate>
{
    NSOperationQueue *_operationQueue;
    NSURLSession *_imageSession;
    NSURLCache *_urlCache;
    NSMutableDictionary *_staticImageCache;
    NSMutableDictionary *_firstFrameImageCache;
    NSMutableDictionary *_imageInfoCache;
    NSMutableDictionary *_downloadOperationInfos;
    NSMutableDictionary *_cancelledDownloadOperationInfos;
    NSObject<OS_dispatch_queue> *_queuedOperationsInfoQueue;
    UIImage *_searchProviderImage;
}

+ (id)sharedCache;
@property(retain, nonatomic) UIImage *searchProviderImage; // @synthesize searchProviderImage=_searchProviderImage;
- (void).cxx_destruct;
- (_Bool)_allowImageInfoCaching;
- (id)_imageInfoWithData:(id)arg1;
- (id)_imageFromSampleBuffer:(struct opaqueCMSampleBuffer *)arg1;
- (id)_imageInfoUsingAVAssetReaderWithFileURL:(id)arg1;
- (id)_imageSession;
- (void)URLSession:(id)arg1 downloadTask:(id)arg2 didWriteData:(long long)arg3 totalBytesWritten:(long long)arg4 totalBytesExpectedToWrite:(long long)arg5;
- (void)URLSession:(id)arg1 downloadTask:(id)arg2 didFinishDownloadingToURL:(id)arg3;
- (void)URLSession:(id)arg1 task:(id)arg2 didCompleteWithError:(id)arg3;
- (void)clearInMemoryCache;
- (void)cancelAllDownloads;
- (void)cancelQueuedDownloadForURL:(id)arg1;
- (void)setPriority:(long long)arg1 forQueuedDownloadWithURL:(id)arg2;
- (void)fetchImageDataWithURL:(id)arg1 priority:(long long)arg2 isSource:(_Bool)arg3 begin:(CDUnknownBlockType)arg4 progress:(CDUnknownBlockType)arg5 completion:(CDUnknownBlockType)arg6;
- (void)fetchImageWithURL:(id)arg1 priority:(long long)arg2 isSource:(_Bool)arg3 begin:(CDUnknownBlockType)arg4 progress:(CDUnknownBlockType)arg5 completion:(CDUnknownBlockType)arg6;
- (id)fetchCachedImageInfoForURL:(id)arg1;
- (id)fetchCachedStaticImageForURL:(id)arg1 hasMultipleFrames:(_Bool *)arg2;
- (id)fetchCachedStaticImageForURL:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

