//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class STSSuggestionFooter, UITableView;

@interface STSSuggestionView : UIView
{
    STSSuggestionFooter *_footerView;
    UITableView *_tableView;
    UIView *_overlayView;
    id <STSSuggestionViewDelegate> _delegate;
    struct CGPoint _footerOffset;
    struct UIEdgeInsets _contentInset;
}

@property(nonatomic) __weak id <STSSuggestionViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) struct CGPoint footerOffset; // @synthesize footerOffset=_footerOffset;
@property(nonatomic) struct UIEdgeInsets contentInset; // @synthesize contentInset=_contentInset;
@property(retain, nonatomic) UIView *overlayView; // @synthesize overlayView=_overlayView;
@property(readonly, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
- (void).cxx_destruct;
- (void)_updateContentInsets;
- (void)_updateFooterOrigin;
- (void)updateFooterImage:(id)arg1;
- (void)_handleLogoTap:(id)arg1;
- (struct CGSize)footerSize;
@property(nonatomic, getter=isShowingFooter) _Bool showingFooter;
- (void)setOverlayView:(id)arg1 animated:(_Bool)arg2;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

