//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, STSSearchModel;

@protocol STSSearchModelDelegate <NSObject>
- (void)searchModel:(STSSearchModel *)arg1 insertedResultsAtIndexPaths:(NSArray *)arg2 removedResultsAtIndexPaths:(NSArray *)arg3;
- (void)searchModelUpdatedPredictedSuggestions:(STSSearchModel *)arg1;
@end

