//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DEExtensionProvider.h"

@class BKSProcessAssertion;

@interface PhotosDiagnosticsExtension : DEExtensionProvider
{
    BKSProcessAssertion *_wakeupPhotosAssertion;
}

- (void).cxx_destruct;
- (id)_excludeEmptyAttachments:(id)arg1;
- (void)_gatherPhotosDiagnosticData;
- (void)_retrieveDiagnosticsAgentIfPossible:(CDUnknownBlockType)arg1;
- (id)_retrievePhotosUICurrentAssetResources;
- (id)_retrievePhotosUILayerHierarchyDumps;
- (void)_gatherDescriptionOfPhotosUIStateAsLogs;
- (id)_currentTimestamp;
- (void)_collectDatabaseAtPath:(id)arg1 toPath:(id)arg2;
- (_Bool)_wakeupPhotos;
- (id)attachmentsForParameters:(id)arg1;
- (id)attachmentList;
- (id)_parseAttachmentsAndIncludeAll:(_Bool)arg1;
- (id)_attachmentsForGroupNamed:(id)arg1 usingFilePaths:(id)arg2 compress:(_Bool)arg3 deleteAfterAttaching:(_Bool)arg4;
- (id)_attachmentsForGroupNamed:(id)arg1 usingFilesNamed:(id)arg2 withSuffixes:(id)arg3 inDirectoryPath:(id)arg4 compress:(_Bool)arg5 deleteAfterAttaching:(_Bool)arg6;
- (id)_attachmentsForGroupNamed:(id)arg1 matchingRegexPattern:(id)arg2 excludingRegexPattern:(id)arg3 inDirectoryURL:(id)arg4 compress:(_Bool)arg5 deleteAfterAttaching:(_Bool)arg6;

@end

