/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 21, 2018 at 11:42:08 PM Central European Summer Time
* Operating System: Version 11.3.1 (Build 15E302)
* Image Source: /Applications/AppStore.app/Frameworks/JetEngine.framework/JetEngine
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class UITraitCollection;

@interface _TtC9JetEngineP33_05839733733FC3CDAF488FE79C549CF88CacheKey : NSObject {

	 useCase;
	 traitCollection;

}

@property (readonly,nonatomic) UITraitCollection * traitCollection; 
@property (readonly,nonatomic) long long hash; 
-(id)init;
-(UITraitCollection *)traitCollection;
-(BOOL)isEqual:(id)arg1 ;
-(long long)hash;
@end

