//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DKDiagnosticController.h"

@class NSString;

@interface BatteryUsageAnalysisController : DKDiagnosticController
{
    NSString *_workingDirectory;
    NSString *_archivesDirectory;
}

@property(retain, nonatomic) NSString *archivesDirectory; // @synthesize archivesDirectory=_archivesDirectory;
@property(retain, nonatomic) NSString *workingDirectory; // @synthesize workingDirectory=_workingDirectory;
- (void).cxx_destruct;
- (id)archiveLogFile:(id)arg1;
- (void)enumerateArchivedPowerLogsWithBlock:(CDUnknownBlockType)arg1;
- (_Bool)createWorkingDirectories;
- (id)writeCurrentPowerLog;
- (id)collectLogFile;
- (void)teardown;
- (void)start;
- (void)setupWithInputs:(id)arg1 responder:(id)arg2;

@end

