//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "_OSDCameraInterface.h"

@protocol _OSDCameraSyncInterface <_OSDCameraInterface>
- (_Bool)syncSlave:(id <_OSDCameraSyncInterface>)arg1 skipFrames:(_Bool)arg2 enableOutput:(_Bool)arg3 error:(id *)arg4;
@end

