//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "OSDPropertyBasedDevice.h"

@class NSObject<OS_dispatch_queue>, NSObject<OS_dispatch_semaphore>;

@interface OSDCaptureStream : OSDPropertyBasedDevice
{
    struct OpaqueFigCaptureStream *_streamRef;
    NSObject<OS_dispatch_semaphore> *_streamStartSemaphore;
    NSObject<OS_dispatch_semaphore> *_streamStopSemaphore;
    NSObject<OS_dispatch_queue> *_workQueue;
}

@property(retain, nonatomic) NSObject<OS_dispatch_queue> *workQueue; // @synthesize workQueue=_workQueue;
@property(retain, nonatomic) NSObject<OS_dispatch_semaphore> *streamStopSemaphore; // @synthesize streamStopSemaphore=_streamStopSemaphore;
@property(retain, nonatomic) NSObject<OS_dispatch_semaphore> *streamStartSemaphore; // @synthesize streamStartSemaphore=_streamStartSemaphore;
@property(readonly, nonatomic) struct OpaqueFigCaptureStream *streamRef; // @synthesize streamRef=_streamRef;
- (void).cxx_destruct;
- (_Bool)stop:(id *)arg1;
- (_Bool)start:(id *)arg1;
- (void)_receivedNotification:(struct __CFString *)arg1 notificationObject:(id)arg2 notificationPayload:(id)arg3;
- (_Bool)_unregisterForStreamNotifications:(id *)arg1;
- (_Bool)_registerForStreamNotifications:(id *)arg1;
- (int)backingCopyProperty:(struct __CFString *)arg1 dest:(const void **)arg2;
- (int)backingSetProperty:(struct __CFString *)arg1 value:(void *)arg2;
- (void *)backingRef;
- (id)name:(id *)arg1;
- (void)teardown;
- (void)dealloc;
- (id)initWithStream:(struct OpaqueFigCaptureStream *)arg1;

@end

