//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AKController, NSArray, PKInk, SSSScreenshot, UILongPressGestureRecognizer, UIPanGestureRecognizer, UIRotationGestureRecognizer, UITapGestureRecognizer, UIView;

@interface _SSSScreenshotContentOverlayController : NSObject
{
    _Bool _gesturesEnabled;
    _Bool _active;
    SSSScreenshot *_screenshot;
    id <_SSSScreenshotContentOverlayControllerDelegate> _delegate;
    PKInk *_ink;
}

@property(retain, nonatomic) PKInk *ink; // @synthesize ink=_ink;
@property(nonatomic) __weak id <_SSSScreenshotContentOverlayControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool active; // @synthesize active=_active;
@property(nonatomic) _Bool gesturesEnabled; // @synthesize gesturesEnabled=_gesturesEnabled;
@property(nonatomic) __weak SSSScreenshot *screenshot; // @synthesize screenshot=_screenshot;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSArray *gestureRecognizers;
@property(readonly, nonatomic) UIView *overlayView;
@property(readonly, nonatomic) UIRotationGestureRecognizer *rotationGestureRecognizer;
@property(readonly, nonatomic) UIPanGestureRecognizer *panGestureRecognizer;
@property(readonly, nonatomic) UILongPressGestureRecognizer *longPressGestureRecognizer;
@property(readonly, nonatomic) UITapGestureRecognizer *doubleTapGestureRecognizer;
@property(readonly, nonatomic) UITapGestureRecognizer *tapGestureRecognizer;
@property(readonly, nonatomic) struct CGRect rectToCenterAboveKeyboard;
@property(readonly, nonatomic) AKController *annotationKitController;
- (void)endedEditingWithOverlay;
- (void)enteredEditingWithOverlay;
- (void)updateUndoState;

@end

