//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UIViewPropertyAnimator;

@interface SSSAnimator : NSObject
{
    UIViewPropertyAnimator *_propertyAnimator;
    id <UIDragAnimating> _dragAnimating;
}

+ (id)animatorWithDragAnimating:(id)arg1;
+ (id)animatorWithPropertyAnimator:(id)arg1;
@property(nonatomic) __weak id <UIDragAnimating> dragAnimating; // @synthesize dragAnimating=_dragAnimating;
@property(nonatomic) __weak UIViewPropertyAnimator *propertyAnimator; // @synthesize propertyAnimator=_propertyAnimator;
- (void).cxx_destruct;
- (void)addCompletion:(CDUnknownBlockType)arg1;
- (void)addAnimations:(CDUnknownBlockType)arg1;

@end

