//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIApplication.h"

@class SSSAppDelegate;

@interface SSSApplication : UIApplication
{
}

+ (id)sharedSSSApplication;
- (_Bool)_canAnimateDragCancelInApp;
- (void)_handlePlatformSpecificActions:(id)arg1 forScene:(id)arg2 withTransitionContext:(id)arg3;
- (id)_imageIdentifierActionInActions:(id)arg1;
- (id)_screenshotActionInActions:(id)arg1;
- (id)_actionInActions:(id)arg1 ofClass:(Class)arg2;
@property(readonly, nonatomic) SSSAppDelegate *sssAppDelegate;

@end

