//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SSSFlashView.h"

@class SSSBlurView, UIViewPropertyAnimator, _SSSFlashWhiteView;

@interface SSSBlurringFlashView : SSSFlashView
{
    CDUnknownBlockType _completionBlock;
    SSSBlurView *_blurView;
    _SSSFlashWhiteView *_whiteView;
    UIViewPropertyAnimator *_whiteViewOpacityAnimator;
    UIViewPropertyAnimator *_blurViewRadiusAnimator;
    _Bool _isCompletingFlashWithNewTimingParameters;
    _Bool _whiteViewBackgroundColorAnimatorCompleted;
    _Bool _blurViewRadiusAnimatorCompleted;
}

- (void).cxx_destruct;
- (double)_cornerRadius;
- (void)_setCornerRadius:(double)arg1;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)_runCompletionBlockIfAppropriate;
- (void)_whiteViewBackgroundColorAnimatorCompleted;
- (void)_blurViewRadiusAnimatorCompleted;
- (void)flashWithCompletion:(CDUnknownBlockType)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

