//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "SSSContainerViewControllerDelegate.h"

@class NSTimer, SSSContainerViewController;

@interface SSSDittoRootViewController : UIViewController <SSSContainerViewControllerDelegate>
{
    SSSContainerViewController *_containerViewController;
    unsigned long long _containerViewControllerTargetState;
    NSTimer *_dismissTimer;
    _Bool _isPerformingDismissAnimation;
    _Bool _isInDragAndDrop;
    _Bool _isShowingSharingUI;
    _Bool _isShowingWaitingForImageIdentifierUpdatesUI;
    id <SSSDittoRootViewControllerDelegate> _delegate;
    id <SSSDittoViewController> _hostingViewController;
}

@property(nonatomic) __weak id <SSSDittoViewController> hostingViewController; // @synthesize hostingViewController=_hostingViewController;
@property(nonatomic) __weak id <SSSDittoRootViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
@property(readonly, nonatomic) _Bool shouldAnimateDragCancel;
@property(readonly, nonatomic) unsigned long long state;
- (void)_resetDismissTimer;
- (void)_invalidateDismissTimer;
- (void)_timerPostponingEventOccured;
- (_Bool)_shouldResetDismissTimer;
- (void)_animateDeletionDismiss;
- (void)_animateDismissWithVelocity:(double)arg1;
- (void)_animateDismiss;
- (void)_tearDownReferencesToContainerViewController;
- (void)_performPostDismissActionsForContainerViewController:(id)arg1;
- (void)_performPreDismissActions;
- (void)_dismissTimerTriggered;
- (void)_dismissAnimationFinishedForContainerViewController:(id)arg1;
- (void)_dismissWithoutAnimation;
- (void)performProgrammaticDismiss;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)pipify;
- (unsigned long long)supportedInterfaceOrientations;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)_updateViewProperties;
- (void)_animateViewPropertyChange;
- (void)_updateForSize:(struct CGSize)arg1;
- (void)_updateForCurrentSize;
- (void)_postNotificationForDidChangeToState:(unsigned long long)arg1;
- (void)_postNotificationForWillChangeToState:(unsigned long long)arg1;
- (void)_postNotificationName:(id)arg1;
- (void)containerViewControllerEndedShowingWaitingForImageIdentifierUpdatesUI:(id)arg1;
- (void)containerViewControllerBeganShowingWaitingForImageIdentifierUpdatesUI:(id)arg1;
- (void)containerViewControllerEndedShowingSharingUI:(id)arg1;
- (void)containerViewController:(id)arg1 willShowSharingUIWithBlock:(CDUnknownBlockType)arg2;
- (void)containerViewControllerEndedDragAndDrop:(id)arg1 shouldDismiss:(_Bool)arg2;
- (void)containerViewControllerBeganDragAndDrop:(id)arg1;
- (void)containerViewControllerHadGestureInteraction:(id)arg1;
- (void)containerViewController:(id)arg1 requestsDismissWithVelocity:(double)arg2;
- (void)containerViewControllerRequestsDismiss:(id)arg1;
- (void)containerViewControllerRequestsDeletionDismiss:(id)arg1;
- (void)containerViewController:(id)arg1 didTransitionToState:(unsigned long long)arg2;
- (void)containerViewController:(id)arg1 willTransitionToState:(unsigned long long)arg2 changeBlock:(CDUnknownBlockType)arg3;
- (int)_preferredStatusBarVisibility;
- (long long)preferredStatusBarStyle;
- (id)childViewControllerForStatusBarHidden;
- (id)childViewControllerForStatusBarStyle;
- (void)_addContainerViewController:(id)arg1;
- (void)_createAndParentContainerViewControllerIfPossible;
- (void)_createContainerViewControllerIfNecessary;
- (void)screenshotReceived:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

