//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "SSSDittoDebugViewDelegate.h"
#import "SSSDittoRootViewControllerDelegate.h"
#import "SSSDittoViewController.h"

@class SSSDittoRootViewController;

@interface SSSDittoDebugViewController : UIViewController <SSSDittoRootViewControllerDelegate, SSSDittoDebugViewDelegate, SSSDittoViewController>
{
    SSSDittoRootViewController *_rootViewController;
}

+ (void)prepareForDebugging;
- (void).cxx_destruct;
- (void)viewDidLoad;
- (id)debugView;
- (void)loadView;
- (void)_addScreenshots;
- (void)dittoDebugView:(id)arg1 requestsPresentationOfViewController:(id)arg2;
- (void)_addScreenshot;
- (void)becomeParentOfDittoRootViewController:(id)arg1;
- (void)dittoRootViewControllerFinishedShowingSharingUI:(id)arg1;
- (void)dittoRootViewController:(id)arg1 willShowShowSharingUIWithBlock:(CDUnknownBlockType)arg2;
- (void)dittoRootViewController:(id)arg1 willTransitionToState:(unsigned long long)arg2 changeBlock:(CDUnknownBlockType)arg3;
- (void)dittoRootViewController:(id)arg1 didTransitionToState:(unsigned long long)arg2;
@property(readonly, nonatomic) SSSDittoRootViewController *rootViewController;
- (void)stopBeingParentOfDittoRootViewController:(id)arg1;
- (void)screenshotEnvironmentDescriptionReceived:(id)arg1;
- (void)_prepareRootViewControllerIfNecessary;

@end

