//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBUIRemoteAlertServiceViewController.h"

#import "SSSDittoRootViewControllerDelegate.h"
#import "SSSDittoViewController.h"

@class SSSDittoRootViewController;

@interface SSSDittoRemoteAlertViewController : SBUIRemoteAlertServiceViewController <SSSDittoRootViewControllerDelegate, SSSDittoViewController>
{
    SSSDittoRootViewController *_rootViewController;
}

+ (_Bool)_isSecureForRemoteViewService;
- (void).cxx_destruct;
- (void)configureWithContext:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)prepareForActivationWithContext:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (long long)preferredStatusBarStyle;
- (int)_preferredStatusBarVisibility;
- (id)childViewControllerForStatusBarHidden;
- (id)childViewControllerForStatusBarStyle;
- (void)viewDidLoad;
- (void)handleButtonActions:(id)arg1;
@property(readonly, nonatomic) SSSDittoRootViewController *rootViewController;
- (void)stopBeingParentOfDittoRootViewController:(id)arg1;
- (void)becomeParentOfDittoRootViewController:(id)arg1;
- (void)dittoRootViewControllerFinishedShowingSharingUI:(id)arg1;
- (void)dittoRootViewController:(id)arg1 willShowShowSharingUIWithBlock:(CDUnknownBlockType)arg2;
- (void)dittoRootViewController:(id)arg1 didTransitionToState:(unsigned long long)arg2;
- (void)dittoRootViewController:(id)arg1 willTransitionToState:(unsigned long long)arg2 changeBlock:(CDUnknownBlockType)arg3;
- (void)_performDismiss;
- (void)_addRootViewController;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

