//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSArray, _SSSShadowViewInnerViewWithShadow;

@interface SSSShadowView : UIView
{
    _SSSShadowViewInnerViewWithShadow *_innerView;
    NSArray *_rectsForShadow;
}

+ (double)shadowOpacity;
+ (struct CGSize)shadowOffset;
+ (double)shadowRadius;
+ (id)shadowColor;
@property(retain, nonatomic) NSArray *rectsForShadow; // @synthesize rectsForShadow=_rectsForShadow;
- (void).cxx_destruct;
- (void)_enumerateAllShadowRectsWithBlock:(CDUnknownBlockType)arg1;
- (_Bool)_arrayOfRectValues:(id)arg1 isEqualToArrayOfRectValues:(id)arg2;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

