//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#pragma mark Blocks

typedef void (^CDUnknownBlockType)(void); // return type and parameters are unknown

#pragma mark Named Structures

struct CLRunningBufferStats<float> {
    CDUnknownFunctionPointerType *_vptr$CLRunningBufferStats;
    unsigned int fSize;
    float fRunningSum;
    float fRunningSumSquared;
    struct deque<float, std::__1::allocator<float>> fSamples;
};

struct CLRunningVector3d<float> {
    CDUnknownFunctionPointerType *_vptr$CLRunningVector3d;
    unsigned int fSize;
    struct CLRunningBufferStats<float> fRunningX;
    struct CLRunningBufferStats<float> fRunningY;
    struct CLRunningBufferStats<float> fRunningZ;
};

struct deque<float, std::__1::allocator<float>> {
    struct __split_buffer<float *, std::__1::allocator<float *>> {
        float **__first_;
        float **__begin_;
        float **__end_;
        struct __compressed_pair<float **, std::__1::allocator<float *>> {
            float **__value_;
        } __end_cap_;
    } __map_;
    unsigned long long __start_;
    struct __compressed_pair<unsigned long, std::__1::allocator<float>> {
        unsigned long long __value_;
    } __size_;
};

#pragma mark Typedef'd Structures

typedef struct {
    char *_field1;
    char *_field2;
    char *_field3;
    int _field4;
    char *_field5;
} CDStruct_13459f61;

