//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DKDiagnosticController.h"

@class NSMutableArray, OSDBumpMonitor, OSDLegacyCamera, OpticalImageStabilizerInputs;

@interface OpticalImageStabilizerController : DKDiagnosticController
{
    OSDLegacyCamera *_osdCamera;
    OSDBumpMonitor *_bumpMonitor;
    NSMutableArray *_bumpEvents;
    NSMutableArray *_testInstances;
    NSMutableArray *_actualPositions;
    NSMutableArray *_allResults;
    OpticalImageStabilizerInputs *_inputs;
}

@property(retain, nonatomic) OpticalImageStabilizerInputs *inputs; // @synthesize inputs=_inputs;
@property(retain, nonatomic) NSMutableArray *allResults; // @synthesize allResults=_allResults;
@property(retain, nonatomic) NSMutableArray *actualPositions; // @synthesize actualPositions=_actualPositions;
@property(retain, nonatomic) NSMutableArray *testInstances; // @synthesize testInstances=_testInstances;
@property(retain, nonatomic) NSMutableArray *bumpEvents; // @synthesize bumpEvents=_bumpEvents;
@property(retain, nonatomic) OSDBumpMonitor *bumpMonitor; // @synthesize bumpMonitor=_bumpMonitor;
@property(retain, nonatomic) OSDLegacyCamera *osdCamera; // @synthesize osdCamera=_osdCamera;
- (void).cxx_destruct;
- (double)stdev:(double *)arg1 size:(unsigned int)arg2;
- (double)variance:(double *)arg1 size:(unsigned int)arg2;
- (double)average:(double *)arg1 size:(unsigned int)arg2;
- (void)teardown;
- (void)setStatusCode:(id)arg1;
- (_Bool)hasOpticalImageStabilizer;
- (void)start;
- (_Bool)isPresent;
- (void)setupWithInputs:(id)arg1 responder:(id)arg2;

@end

