//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HFItemProvider.h"

@class HFItemBuilder<HFServiceLikeBuilder>, HFRoomBuilderItem;

@interface HSSetupServiceSelectedRoomItemProvider : HFItemProvider
{
    CDUnknownBlockType _filter;
    HFItemBuilder<HFServiceLikeBuilder> *_serviceLikeBuilder;
    HFRoomBuilderItem *_roomBuilderItem;
}

@property(retain, nonatomic) HFRoomBuilderItem *roomBuilderItem; // @synthesize roomBuilderItem=_roomBuilderItem;
@property(retain, nonatomic) HFItemBuilder<HFServiceLikeBuilder> *serviceLikeBuilder; // @synthesize serviceLikeBuilder=_serviceLikeBuilder;
@property(copy, nonatomic) CDUnknownBlockType filter; // @synthesize filter=_filter;
- (void).cxx_destruct;
- (id)invalidationReasons;
- (id)items;
- (id)reloadItems;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithServiceLikeBuilder:(id)arg1;
- (id)init;

@end

