//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HFStaticItem.h"

@interface HSSetupTroubleshootingTipItem : HFStaticItem
{
}

- (double)_subPriorityForPreferredOrder:(unsigned long long)arg1;
- (id)_initTroubleshootingTipWithResultsBlock:(CDUnknownBlockType)arg1;
- (id)_initTroubleshootingTipWithResults:(id)arg1;

@end

