//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBCodable.h"

#import "NSCopying.h"

@interface AWDICSSOSOperationDuration : PBCodable <NSCopying>
{
    unsigned long long _operationDurationMs;
    unsigned long long _timestamp;
    unsigned int _operationType;
    struct {
        unsigned int operationDurationMs:1;
        unsigned int timestamp:1;
        unsigned int operationType:1;
    } _has;
}

@property(nonatomic) unsigned int operationType; // @synthesize operationType=_operationType;
@property(nonatomic) unsigned long long operationDurationMs; // @synthesize operationDurationMs=_operationDurationMs;
@property(nonatomic) unsigned long long timestamp; // @synthesize timestamp=_timestamp;
- (void)mergeFrom:(id)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (_Bool)readFrom:(id)arg1;
- (id)dictionaryRepresentation;
- (id)description;
@property(nonatomic) _Bool hasOperationType;
@property(nonatomic) _Bool hasOperationDurationMs;
@property(nonatomic) _Bool hasTimestamp;

@end

