//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AWDServerConnection, NSObject<OS_dispatch_queue>;

@interface ICSAWDReporter : NSObject
{
    NSObject<OS_dispatch_queue> *_queue;
    AWDServerConnection *_serverConnection;
}

+ (id)sharedInstance;
@property(retain, nonatomic) AWDServerConnection *serverConnection; // @synthesize serverConnection=_serverConnection;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
- (void).cxx_destruct;
- (void)_reportMetricWithID:(unsigned int)arg1 metric:(id)arg2;
- (void)_reportSOSWithDuration:(double)arg1 type:(int)arg2;
- (void)reportCanceledSOSCountdownToNotify:(double)arg1;
- (void)reportCanceledSOSCountdownToCall:(double)arg1;
- (void)reportBioLockout;
- (id)init;

@end

