//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ICSAnnouncement.h"

@class CNContactStore, NSArray, NSString;

@interface ICSCallAnnouncement : ICSAnnouncement
{
    NSString *_callerName;
    long long _callerNameType;
    NSString *_callServiceName;
    NSString *_callDestinationID;
    CNContactStore *_contactStore;
    NSArray *_contacts;
    NSString *_callDisplayName;
    NSString *_callISOCountryCode;
    NSString *_contactIdentifier;
}

+ (id)announcementWithCall:(id)arg1;
@property(copy, nonatomic) NSString *contactIdentifier; // @synthesize contactIdentifier=_contactIdentifier;
@property(copy, nonatomic) NSString *callISOCountryCode; // @synthesize callISOCountryCode=_callISOCountryCode;
@property(copy, nonatomic) NSString *callDisplayName; // @synthesize callDisplayName=_callDisplayName;
@property(retain, nonatomic) NSArray *contacts; // @synthesize contacts=_contacts;
@property(retain, nonatomic) CNContactStore *contactStore; // @synthesize contactStore=_contactStore;
@property(copy, nonatomic) NSString *callDestinationID; // @synthesize callDestinationID=_callDestinationID;
@property(copy, nonatomic) NSString *callServiceName; // @synthesize callServiceName=_callServiceName;
@property(nonatomic) long long callerNameType; // @synthesize callerNameType=_callerNameType;
@property(copy, nonatomic) NSString *callerName; // @synthesize callerName=_callerName;
- (void).cxx_destruct;
- (void)handleContactStoreDidChangeNotification:(id)arg1;
- (id)contactsForDestinationID:(id)arg1 isoCountryCode:(id)arg2;
- (id)contactForIdentifier:(id)arg1;
@property(readonly, copy, nonatomic) NSArray *contactKeyDescriptors;
- (id)text;
- (id)callServiceNameForCall:(id)arg1;
- (long long)callerNameTypeForCall:(id)arg1;
- (id)callerNameForCall:(id)arg1;
- (void)dealloc;
- (id)initWithCall:(id)arg1;
- (id)init;

@end

