//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ICSCallAnnouncement.h"

#import "VSSpeechSynthesizerDelegate.h"

@class NSString, VSSpeechRequest, VSSpeechSynthesizer;

@interface ICSSiriCallAnnouncement : ICSCallAnnouncement <VSSpeechSynthesizerDelegate>
{
    long long *_callerIDType;
    VSSpeechRequest *_speechRequest;
    VSSpeechSynthesizer *_speechSynthesizer;
}

@property(retain, nonatomic) VSSpeechSynthesizer *speechSynthesizer; // @synthesize speechSynthesizer=_speechSynthesizer;
@property(retain, nonatomic) VSSpeechRequest *speechRequest; // @synthesize speechRequest=_speechRequest;
@property(nonatomic) long long *callerIDType; // @synthesize callerIDType=_callerIDType;
- (void).cxx_destruct;
- (void)speechSynthesizer:(id)arg1 willSpeakRangeOfSpeechString:(struct _NSRange)arg2 forRequest:(id)arg3;
- (void)speechSynthesizer:(id)arg1 didContinueSpeakingRequest:(id)arg2;
- (void)speechSynthesizer:(id)arg1 didPauseSpeakingRequest:(id)arg2;
- (void)speechSynthesizer:(id)arg1 didFinishSpeakingRequest:(id)arg2 successfully:(_Bool)arg3 phonemesSpoken:(id)arg4 withError:(id)arg5;
- (void)speechSynthesizer:(id)arg1 didFinishSpeakingRequest:(id)arg2 successfully:(_Bool)arg3 withError:(id)arg4;
- (void)speechSynthesizer:(id)arg1 didStartSpeakingRequest:(id)arg2;
- (void)speechSynthesizer:(id)arg1 willSpeakRangeOfSpeechString:(struct _NSRange)arg2;
- (void)speechSynthesizerDidContinueSpeaking:(id)arg1;
- (void)speechSynthesizerDidPauseSpeaking:(id)arg1;
- (void)speechSynthesizer:(id)arg1 didFinishSpeaking:(_Bool)arg2 phonemesSpoken:(id)arg3 withError:(id)arg4;
- (void)speechSynthesizer:(id)arg1 didFinishSpeaking:(_Bool)arg2 withError:(id)arg3;
- (void)speechSynthesizerDidStartSpeaking:(id)arg1;
- (void)stop;
- (void)start;
- (void)pause;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

