//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class PHRingtoneController;

@interface PHAudioInterruptionController : NSObject
{
    PHRingtoneController *_ringtoneController;
}

+ (id)sharedInstance;
@property(readonly, nonatomic) PHRingtoneController *ringtoneController; // @synthesize ringtoneController=_ringtoneController;
- (void).cxx_destruct;
- (void)_playAnnouncementForIncomingCallIfNecessary;
- (void)_callShouldSuppressRingtoneChanged:(id)arg1;
- (void)_updateAudioInterruptionsForCall:(id)arg1;
- (void)_callStatusChanged:(id)arg1;
- (void)dealloc;
- (id)init;

@end

