//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIAlertController.h"

@class NSArray;

@interface PHAudioRoutingAlertController : UIAlertController
{
    long long _callStyle;
    id <PHAudioRoutingAlertDataSource> _dataSource;
    id <PHAudioRoutingAlertDelegate> _delegate;
}

+ (id)alertControllerWithCallStyle:(long long)arg1 dataSource:(id)arg2 delegate:(id)arg3;
@property(nonatomic) __weak id <PHAudioRoutingAlertDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak id <PHAudioRoutingAlertDataSource> dataSource; // @synthesize dataSource=_dataSource;
@property(nonatomic) long long callStyle; // @synthesize callStyle=_callStyle;
- (void).cxx_destruct;
- (id)muteActionTitle;
- (_Bool)isMuted;
- (id)muteAlertAction;
- (id)hideActionTitle;
- (id)hideAlertAction;
- (id)routeAlertActionWithTitle:(id)arg1 route:(id)arg2;
@property(readonly, copy, nonatomic) NSArray *alertActions;
- (void)reload;

@end

