//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSArray;

@interface PHAudioCallControlsView : UIView
{
    _Bool _buttonsEnabled;
    id <PHAudioCallControlsViewDelegate> _delegate;
    NSArray *_buttonsArray;
}

+ (_Bool)audioCallControlTypeDependsUponImage:(unsigned long long)arg1;
@property(copy) NSArray *buttonsArray; // @synthesize buttonsArray=_buttonsArray;
@property(nonatomic) _Bool buttonsEnabled; // @synthesize buttonsEnabled=_buttonsEnabled;
@property(nonatomic) __weak id <PHAudioCallControlsViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (double)_horizontalSpacing;
- (double)_verticalSpacing;
- (double)_topMargin;
- (void)setFrame:(struct CGRect)arg1;
- (void)setCenter:(struct CGPoint)arg1;
- (id)buttonForControlType:(unsigned long long)arg1;
- (void)setSelectedState:(_Bool)arg1 forControlType:(unsigned long long)arg2;
- (void)buttonLongPressGestureRecognizer:(id)arg1;
- (void)buttonShortPressGestureRecognizer:(id)arg1;
- (void)buttonTapped:(id)arg1;
- (void)assignControlType:(unsigned long long)arg1 toButton:(id)arg2;
- (void)reloadButtonViewStates;
- (void)updateControls;
- (_Bool)needsReloadButtonViews;
- (void)reloadButtonViews;
- (struct CGSize)intrinsicContentSize;
- (id)init;

@end

