//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "PHCallParticipantLabelDelegate.h"

@class NSString, PHMultipleCallParticipantLabelView, PHSingleCallParticipantLabelView, UIButton, UILabel;

@interface PHCallParticipantsView : UIView <PHCallParticipantLabelDelegate>
{
    _Bool _shouldShowSingleDurationLabel;
    _Bool _allowsFieldModeSendButton;
    _Bool _shouldCompressLabelsVertically;
    _Bool _isEnabled;
    _Bool _isShowingInfoButton;
    id <PHCallParticipantsViewDelegate> _delegate;
    PHSingleCallParticipantLabelView *_singleCallLabelView;
    PHMultipleCallParticipantLabelView *_topMultipleCallLabelView;
    PHMultipleCallParticipantLabelView *_bottomMultipleCallLabelView;
    UILabel *_nameOverrideLabel;
    UILabel *_singleDurationTimerLabel;
    UIButton *_fieldModeSendButton;
}

@property(retain) UIButton *fieldModeSendButton; // @synthesize fieldModeSendButton=_fieldModeSendButton;
@property(retain) UILabel *singleDurationTimerLabel; // @synthesize singleDurationTimerLabel=_singleDurationTimerLabel;
@property(retain) UILabel *nameOverrideLabel; // @synthesize nameOverrideLabel=_nameOverrideLabel;
@property(retain) PHMultipleCallParticipantLabelView *bottomMultipleCallLabelView; // @synthesize bottomMultipleCallLabelView=_bottomMultipleCallLabelView;
@property(retain) PHMultipleCallParticipantLabelView *topMultipleCallLabelView; // @synthesize topMultipleCallLabelView=_topMultipleCallLabelView;
@property(retain) PHSingleCallParticipantLabelView *singleCallLabelView; // @synthesize singleCallLabelView=_singleCallLabelView;
@property(readonly, nonatomic) _Bool isShowingInfoButton; // @synthesize isShowingInfoButton=_isShowingInfoButton;
@property(nonatomic, setter=setEnabled:) _Bool isEnabled; // @synthesize isEnabled=_isEnabled;
@property(nonatomic) _Bool shouldCompressLabelsVertically; // @synthesize shouldCompressLabelsVertically=_shouldCompressLabelsVertically;
@property(nonatomic) _Bool allowsFieldModeSendButton; // @synthesize allowsFieldModeSendButton=_allowsFieldModeSendButton;
@property(nonatomic) _Bool shouldShowSingleDurationLabel; // @synthesize shouldShowSingleDurationLabel=_shouldShowSingleDurationLabel;
@property(nonatomic) __weak id <PHCallParticipantsViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (_Bool)shouldIgnoreUpdates;
- (void)_isEmergencyCallChanged:(id)arg1;
- (void)_metadataCacheDidFinishUpdating:(id)arg1;
- (void)showSendButtonGestureRecognizer:(id)arg1;
- (void)fieldModeButtonTapped:(id)arg1;
- (id)compactLabelTextForParticipantLabel:(id)arg1;
- (void)callLabelInfoLabelWasTappedForLabel:(id)arg1;
- (unsigned long long)indexForParticipantLabel:(id)arg1;
- (void)updateSingleDurationTimerLabelText;
- (void)participantLabelWasTapped:(id)arg1;
- (void)setTextColor:(id)arg1;
- (_Bool)_statusLabelStringWillFit:(id)arg1;
- (struct CGSize)intrinsicContentSize;
- (void)updateParticipantAtIndex:(unsigned long long)arg1 animated:(_Bool)arg2;
- (void)updateParticipantAtIndex:(unsigned long long)arg1;
- (void)updateParticipants;
- (float)multiparticipantTopToNameVerticalMargin;
- (void)updateParticipantsAnimated:(_Bool)arg1;
- (double)multipleCallLabelBaselineOffset;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

