//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class PHCarPlayHardwareControlsBroadcaster, PHCarPlayRootContainerViewController;

@interface PHCarPlayManager : NSObject
{
    PHCarPlayHardwareControlsBroadcaster *_hardwareControlsBroadcaster;
    PHCarPlayRootContainerViewController *_rootContainerViewController;
}

+ (_Bool)shouldLimitKeypadAccess;
@property(retain) PHCarPlayRootContainerViewController *rootContainerViewController; // @synthesize rootContainerViewController=_rootContainerViewController;
@property(retain) PHCarPlayHardwareControlsBroadcaster *hardwareControlsBroadcaster; // @synthesize hardwareControlsBroadcaster=_hardwareControlsBroadcaster;
- (void).cxx_destruct;

@end

