//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "CAAnimationDelegate.h"

@class CAGradientLayer, CALayer, NSAttributedString, NSString, PHMarqueeContentView, UIColor, UIFont, UILabel;

@interface PHMarqueeView : UIView <CAAnimationDelegate>
{
    _Bool _scalingEnabled;
    NSString *_text;
    NSAttributedString *_attributedText;
    UIFont *_font;
    UIColor *_textColor;
    double _maxNonMarqueeWidth;
    double _scrollDelay;
    double _scrollSpeed;
    CDUnknownBlockType _animationState;
    CAGradientLayer *_leftMaskLayer;
    CAGradientLayer *_rightMaskLayer;
    CALayer *_maskContainerLayer;
    PHMarqueeContentView *_contentView;
    UILabel *_label;
}

@property(retain) UILabel *label; // @synthesize label=_label;
@property(retain) PHMarqueeContentView *contentView; // @synthesize contentView=_contentView;
@property(retain) CALayer *maskContainerLayer; // @synthesize maskContainerLayer=_maskContainerLayer;
@property(retain) CAGradientLayer *rightMaskLayer; // @synthesize rightMaskLayer=_rightMaskLayer;
@property(retain) CAGradientLayer *leftMaskLayer; // @synthesize leftMaskLayer=_leftMaskLayer;
@property(copy, nonatomic) CDUnknownBlockType animationState; // @synthesize animationState=_animationState;
@property(nonatomic) double scrollSpeed; // @synthesize scrollSpeed=_scrollSpeed;
@property(nonatomic) double scrollDelay; // @synthesize scrollDelay=_scrollDelay;
@property(nonatomic) double maxNonMarqueeWidth; // @synthesize maxNonMarqueeWidth=_maxNonMarqueeWidth;
@property(nonatomic, getter=isScalingEnabled) _Bool scalingEnabled; // @synthesize scalingEnabled=_scalingEnabled;
@property(retain, nonatomic) UIColor *textColor; // @synthesize textColor=_textColor;
@property(retain, nonatomic) UIFont *font; // @synthesize font=_font;
@property(retain, nonatomic) NSAttributedString *attributedText; // @synthesize attributedText=_attributedText;
@property(retain, nonatomic) NSString *text; // @synthesize text=_text;
- (void).cxx_destruct;
- (void)setAttributedOrPlainText:(id)arg1;
- (void)maskEdges:(unsigned long long)arg1 animated:(_Bool)arg2;
- (void)maskEdges:(unsigned long long)arg1;
- (void)animationDidStop:(id)arg1 finished:(_Bool)arg2;
- (void)animationDidStart:(id)arg1;
- (void)removeMarqueeAnimation;
- (void)addMarqueeAnimationIfNecessary;
- (void)layoutSubviews;
- (void)sizeLabel;
- (_Bool)requiresMarquee;
- (struct CGSize)intrinsicContentSize;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

