//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MFMessageComposeViewController.h"

@class PHDeclineWithMessageController;

@interface PHMessageComposeViewController : MFMessageComposeViewController
{
    PHDeclineWithMessageController *_declineWithMessageController;
}

@property(retain, nonatomic) PHDeclineWithMessageController *declineWithMessageController; // @synthesize declineWithMessageController=_declineWithMessageController;
- (void).cxx_destruct;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;

@end

