//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ICSCallAnnouncement, NSObject<OS_dispatch_queue>;

@interface PHRingtoneController : NSObject
{
    NSObject<OS_dispatch_queue> *_queue;
    ICSCallAnnouncement *_callAnnouncement;
}

@property(retain, nonatomic) ICSCallAnnouncement *callAnnouncement; // @synthesize callAnnouncement=_callAnnouncement;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
- (void).cxx_destruct;
- (void)stopAnnouncement;
- (void)playAnnouncementForCall:(id)arg1;
- (void)_playCallAnnouncement:(id)arg1;
- (_Bool)_shouldAnnounceCalls;
- (_Bool)_isActivePreferredOutputPort:(id)arg1;
- (id)init;

@end

