//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class NSMutableArray, PHVideoOverlayContentView, PHVideoOverlayInsulatorView;

@interface PHVideoOverlayViewController : UIViewController
{
    id <PHVideoOverlayViewControllerDelegate> _delegate;
    PHVideoOverlayInsulatorView *_insulatorView;
    PHVideoOverlayContentView *_contentView;
    long long _currentVideoOverlayMode;
    NSMutableArray *_modesPriorityQueue;
}

@property(retain) NSMutableArray *modesPriorityQueue; // @synthesize modesPriorityQueue=_modesPriorityQueue;
@property long long currentVideoOverlayMode; // @synthesize currentVideoOverlayMode=_currentVideoOverlayMode;
@property(retain) PHVideoOverlayContentView *contentView; // @synthesize contentView=_contentView;
@property(retain) PHVideoOverlayInsulatorView *insulatorView; // @synthesize insulatorView=_insulatorView;
@property(nonatomic) __weak id <PHVideoOverlayViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)disableVideoOverlayModes;
- (void)hideVideoOverlayAnimated:(_Bool)arg1;
- (void)showVideoOverlayWithContentView:(id)arg1 animated:(_Bool)arg2;
- (void)setVideoOverlayWithMode:(long long)arg1 animated:(_Bool)arg2;
- (void)showNextVideoOverlayMode;
- (_Bool)isShowingOverlay;
- (_Bool)isModeEnabled:(long long)arg1;
- (_Bool)isShowingMode:(long long)arg1;
- (void)setVideoOverlayEnabled:(_Bool)arg1 forMode:(long long)arg2;
- (void)viewDidLoad;

@end

