//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ADSOptInConnection_RPC.h"
#import "NSXPCListenerDelegate.h"

@class NSString, NSXPCListener;

@interface ADSOptInConnectionManager : NSObject <NSXPCListenerDelegate, ADSOptInConnection_RPC>
{
    NSXPCListener *_xpcListener;
}

+ (_Bool)limitAdTrackingRestrictionEnabled;
+ (id)startOptInConnection;
@property(retain, nonatomic) NSXPCListener *xpcListener; // @synthesize xpcListener=_xpcListener;
- (void)_remote_getiAdIDsWithCompletionHandler:(CDUnknownBlockType)arg1;
- (_Bool)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;
- (id)init;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

