//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UIWebViewDelegate.h"

@class NSDictionary, NSString, UIActivityIndicatorView, UILabel, UIWebView;

@interface ADSPrivacyDetailsViewController : UIViewController <UIWebViewDelegate>
{
    id <ADSPrivacyDetailsViewControllerDelegate> _delegate;
    _Bool _shouldWaitOnTransparencyDetails;
    _Bool _clientAppIsExtension;
    _Bool _shouldShowActivityIndicator;
    _Bool _hasNotifiedDelegateTransparencyDidRender;
    NSDictionary *_transparencyDetails;
    UIWebView *_webView;
    UIActivityIndicatorView *_activityIndicatorView;
    UILabel *_errorLabel;
}

@property(nonatomic) _Bool hasNotifiedDelegateTransparencyDidRender; // @synthesize hasNotifiedDelegateTransparencyDidRender=_hasNotifiedDelegateTransparencyDidRender;
@property(nonatomic) _Bool shouldShowActivityIndicator; // @synthesize shouldShowActivityIndicator=_shouldShowActivityIndicator;
@property(retain, nonatomic) UILabel *errorLabel; // @synthesize errorLabel=_errorLabel;
@property(retain, nonatomic) UIActivityIndicatorView *activityIndicatorView; // @synthesize activityIndicatorView=_activityIndicatorView;
@property(retain, nonatomic) UIWebView *webView; // @synthesize webView=_webView;
@property(nonatomic) _Bool clientAppIsExtension; // @synthesize clientAppIsExtension=_clientAppIsExtension;
@property(nonatomic) _Bool shouldWaitOnTransparencyDetails; // @synthesize shouldWaitOnTransparencyDetails=_shouldWaitOnTransparencyDetails;
@property(retain, nonatomic) NSDictionary *transparencyDetails; // @synthesize transparencyDetails=_transparencyDetails;
- (void)webView:(id)arg1 didFailLoadWithError:(id)arg2;
- (void)webViewDidFinishLoad:(id)arg1;
- (void)attemptToNofitifyLinkOutDelegate;
- (_Bool)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(long long)arg3;
@property(readonly, nonatomic) NSString *transparencyRendererURL;
@property(readonly, nonatomic) NSString *transparencyRendererPayload;
@property(readonly, nonatomic) NSString *transparencyDetailsUnavailableMessage;
- (void)_considerNotifyingDelegateTransparencyDidRender;
- (void)_loadTransparencyWebPage;
- (void)_hideErrorMessage;
- (void)_showErrorMessage:(id)arg1;
- (void)_transparencyDetailsDidChange;
@property(nonatomic) __weak id <ADSPrivacyDetailsViewControllerDelegate> delegate;
- (void)willMoveToParentViewController:(id)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (id)init;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

