//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray;

@interface DDParsecViewProvider : NSObject
{
    NSMutableArray *_dictionaryCardCache;
    id <SearchUIFeedbackDelegate><SKStoreProductViewControllerDelegate><_MKPlaceViewControllerFeedbackDelegate> _feedbackDelegate;
}

@property __weak id <SearchUIFeedbackDelegate><SKStoreProductViewControllerDelegate><_MKPlaceViewControllerFeedbackDelegate> feedbackDelegate; // @synthesize feedbackDelegate=_feedbackDelegate;
- (void).cxx_destruct;
- (id)cardViewControllerForSearchResult:(id)arg1 title:(id)arg2 inPlatter:(_Bool)arg3;
- (id)initWithFeedbackDelegate:(id)arg1;

@end

