//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "NCWidgetProviding.h"
#import "PXMemoriesFeedWidgetViewControllerDelegate.h"

@class NSString, PXMemoriesFeedWidgetViewController, UIView;

@interface PhotosWidgetViewController : UIViewController <NCWidgetProviding, PXMemoriesFeedWidgetViewControllerDelegate>
{
    PXMemoriesFeedWidgetViewController *__memoriesFeedWidgetViewController;
    UIView *__widgetContentUnavailableView;
}

@property(retain, nonatomic, setter=_setWidgetContentUnavailableView:) UIView *_widgetContentUnavailableView; // @synthesize _widgetContentUnavailableView=__widgetContentUnavailableView;
@property(retain, nonatomic, setter=_setMemoriesFeedWidgetViewController:) PXMemoriesFeedWidgetViewController *_memoriesFeedWidgetViewController; // @synthesize _memoriesFeedWidgetViewController=__memoriesFeedWidgetViewController;
- (void).cxx_destruct;
- (void)widgetActiveDisplayModeDidChange:(long long)arg1 withMaximumSize:(struct CGSize)arg2;
- (void)availableNumberOfRowsDidChangeForMemoriesFeedWidgetViewController:(id)arg1;
- (void)memoriesFeedWidgetViewController:(id)arg1 openURL:(id)arg2;
- (unsigned long long)numberOfRowsVisibleForMemoriesFeedWidgetViewController:(id)arg1;
- (struct CGSize)referenceSizeForMemoriesFeedWidgetViewController:(id)arg1;
- (void)_updateWidgetContentUnavailableView;
- (void)preferredContentSizeDidChangeForChildContentContainer:(id)arg1;
- (void)viewWillLayoutSubviews;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)loadView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

