//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class BookmarksNavigationController, CompletionListTableViewController, UniversalSearchFirstTimeExperienceViewController;

@interface AbstractCatalogViewController : UIViewController
{
    double _minimumContentHeight;
}

- (void)_relinquishOwnershipOfViewControllerFromCurrentParent:(id)arg1;
- (_Bool)_takeOwnershipOfViewController:(id)arg1;
- (void)didGainOwnershipOfUniversalSearchFirstTimeExperienceViewController;
- (void)relinquishOwnershipOfUniversalSearchFirstTimeExperienceViewControllerFromCurrentParent;
- (void)takeOwnershipOfUniversalSearchFirstTimeExperienceViewController;
@property(readonly, nonatomic) UniversalSearchFirstTimeExperienceViewController *universalSearchFirstTimeExperienceViewController;
- (void)didGainOwnershipOfFavoritesNavigationController;
- (void)relinquishOwnershipOfFavoritesNavigationControllerFromCurrentParent;
- (void)takeOwnershipOfFavoritesNavigationController;
@property(readonly, nonatomic) BookmarksNavigationController *favoritesNavigationController;
- (void)didGainOwnershipOfCompletionsViewController;
- (void)relinquishOwnershipOfCompletionsViewControllerFromCurrentParent;
- (void)takeOwnershipOfCompletionsViewController;
@property(readonly, nonatomic) CompletionListTableViewController *completionsViewController;
- (_Bool)isResponsibleForLayoutOfViewController:(id)arg1;
- (void)setForegroundChildViewControllerNeedsUpdate;
@property(readonly, nonatomic) UIViewController *foregroundChildViewController;
- (void)updatePreferredContentSize;
@property(readonly, nonatomic) double requiredContentWidth;
- (void)preferredContentSizeDidChangeForChildContentContainer:(id)arg1;
- (void)viewWillLayoutSubviews;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;

@end

