//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "_SFManagedActivityViewController.h"

@class ActionPanelPrintActivityItemProvider, TabDocument;

@interface ActionPanel : _SFManagedActivityViewController
{
    _Bool _inCancel;
    _Bool _inCompletionHandler;
    ActionPanelPrintActivityItemProvider *_printProvider;
    TabDocument *_tabDocument;
}

@property(readonly, nonatomic) TabDocument *tabDocument; // @synthesize tabDocument=_tabDocument;
- (void).cxx_destruct;
- (id)excludedActivityTypes;
- (void)_preparePrint:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_prepareMail:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_preparePostToSocialNetwork:(id)arg1;
- (id)_titleForActivity:(id)arg1;
- (void)_prepareActivity:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_executeActivity;
- (void)_cancel;
- (void)_activityDidComplete:(id)arg1 withSuccess:(_Bool)arg2;
- (void)activityDidComplete:(id)arg1 withReturnedItems:(id)arg2 success:(_Bool)arg3;
- (void)viewDidDisappear:(_Bool)arg1;
- (long long)preferredStatusBarStyle;
- (id)initWithTabDocument:(id)arg1 sharingURL:(id)arg2 activityDelegate:(id)arg3;

// Remaining properties
@property(nonatomic) __weak id <ActionPanelDelegate> delegate; // @dynamic delegate;

@end

