//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCellLayoutManager.h"

@class NSString;

@interface BookmarksTableViewCellLayoutManager : UITableViewCellLayoutManager
{
    _Bool _usesVibrantAppearance;
    NSString *_currentContentSizeCategory;
}

+ (id)sharedManager;
@property(retain, nonatomic) NSString *currentContentSizeCategory; // @synthesize currentContentSizeCategory=_currentContentSizeCategory;
@property(nonatomic) _Bool usesVibrantAppearance; // @synthesize usesVibrantAppearance=_usesVibrantAppearance;
- (void).cxx_destruct;
- (void)layoutSubviewsOfCell:(id)arg1;
- (long long)_numberOfLinesForCurrentContentSize;
- (struct CGRect)accessoryEndingRectForCell:(id)arg1 forNewEditingState:(_Bool)arg2 showingDeleteConfirmation:(_Bool)arg3;
- (struct CGRect)accessoryStartingRectForCell:(id)arg1 forNewEditingState:(_Bool)arg2 showingDeleteConfirmation:(_Bool)arg3;
- (struct CGRect)textRectForCell:(id)arg1 rowWidth:(double)arg2 forSizing:(_Bool)arg3;

@end

