//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSIndexPath;

@interface IndexPathMove : NSObject
{
    NSIndexPath *_indexPathBeforeMove;
    NSIndexPath *_indexPathAfterMove;
}

@property(readonly, nonatomic) NSIndexPath *indexPathAfterMove; // @synthesize indexPathAfterMove=_indexPathAfterMove;
@property(readonly, nonatomic) NSIndexPath *indexPathBeforeMove; // @synthesize indexPathBeforeMove=_indexPathBeforeMove;
- (void).cxx_destruct;
- (id)initWithIndexPathBeforeMove:(id)arg1 indexPathAfterMove:(id)arg2;

@end

