//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "_SFBrowserSavedState.h"

@interface PPTTestBrowserSavedState : _SFBrowserSavedState
{
    unsigned long long _tabsCount;
}

@property(nonatomic) unsigned long long tabsCount; // @synthesize tabsCount=_tabsCount;
- (_Bool)activeDocumentIsValidForBrowserControllerWithUUID:(id)arg1;
- (id)savedTabsStateForBrowserControllerWithUUID:(id)arg1;

@end

