//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, TiltedTabItemLayoutInfo, TiltedTabView;

@interface TiltedTabItem : NSObject
{
    _Bool _recording;
    _Bool _usesDarkTheme;
    NSString *_title;
    TiltedTabItemLayoutInfo *_layoutInfo;
    TiltedTabView *_tiltedTabView;
}

@property(nonatomic) __weak TiltedTabView *tiltedTabView; // @synthesize tiltedTabView=_tiltedTabView;
@property(readonly, nonatomic) TiltedTabItemLayoutInfo *layoutInfo; // @synthesize layoutInfo=_layoutInfo;
@property(nonatomic) _Bool usesDarkTheme; // @synthesize usesDarkTheme=_usesDarkTheme;
@property(nonatomic, getter=isRecording) _Bool recording; // @synthesize recording=_recording;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;

@end

