//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ImageConverter, NSString;

@interface BioLogImage : NSObject
{
    _Bool _reviewed;
    _Bool _approved;
    NSString *_metaData;
    ImageConverter *_converter;
}

@property(retain, nonatomic) ImageConverter *converter; // @synthesize converter=_converter;
@property(nonatomic) _Bool approved; // @synthesize approved=_approved;
@property(nonatomic) _Bool reviewed; // @synthesize reviewed=_reviewed;
@property(readonly, nonatomic) NSString *metaData; // @synthesize metaData=_metaData;
- (void).cxx_destruct;
- (void)setApprovedNoSave:(_Bool)arg1;
- (void)setReviewedNoSave:(_Bool)arg1;
- (id)image;
- (id)initWithImagePath:(id)arg1;

@end

