//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class StreamingCryptor;

@interface EncryptingArchiver : NSObject
{
    int _archiveFd;
    StreamingCryptor *_cryptor;
    struct archive *_archive;
}

- (void).cxx_destruct;
- (long long)_writeData:(const void *)arg1 length:(unsigned long long)arg2;
- (_Bool)close;
- (_Bool)addData:(id)arg1 atLocation:(id)arg2;
- (_Bool)addFile:(id)arg1 atLocation:(id)arg2;
- (id)initWithKey:(id)arg1 path:(id)arg2;
- (void)dealloc;

@end

