//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSString;

@interface ImageConverter : NSObject
{
    NSString *_mFilePath;
    _Bool customerFile;
    int width;
    int height;
    int stride;
    _Bool _isFlood;
    NSString *_imagePath;
    NSString *_jsonPath;
    NSDictionary *_metaData;
    double _epoch;
    struct CGRect _faceRect;
}

@property(nonatomic) struct CGRect faceRect; // @synthesize faceRect=_faceRect;
@property(nonatomic) _Bool isFlood; // @synthesize isFlood=_isFlood;
@property(nonatomic) double epoch; // @synthesize epoch=_epoch;
@property(retain, nonatomic) NSDictionary *metaData; // @synthesize metaData=_metaData;
@property(retain, nonatomic) NSString *jsonPath; // @synthesize jsonPath=_jsonPath;
@property(retain, nonatomic) NSString *imagePath; // @synthesize imagePath=_imagePath;
- (void).cxx_destruct;
- (id)image;
@property(readonly) struct CGSize imageSize;
- (id)initWithImagePath:(id)arg1;
- (_Bool)parseMfile;
- (_Bool)parseJson;
- (_Bool)fetchDouble:(double *)arg1 dict:(id)arg2 key:(id)arg3;
- (_Bool)fetchInt:(int *)arg1 dict:(id)arg2 key:(id)arg3;
- (id)fetchNumberFromDict:(id)arg1 key:(id)arg2;
- (void)computePaths:(id)arg1;

@end

