//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UIToolbarDelegate.h"

@class NSLayoutConstraint, NSString, UIBarButtonItem, UIButton, UILabel, UITextView, UIToolbar;

@interface PearlAgreementViewController : UIViewController <UIToolbarDelegate>
{
    NSLayoutConstraint *_heightTextConstriant;
    UILabel *_mainTitle;
    UITextView *_legalText;
    UIBarButtonItem *_rightToolButton;
    UIBarButtonItem *_leftToolButton;
    UIToolbar *_approoveToolbar;
    UIButton *_aboutButton;
}

+ (id)aboutLocationServicesController;
@property(nonatomic) __weak UIButton *aboutButton; // @synthesize aboutButton=_aboutButton;
@property(nonatomic) __weak UIToolbar *approoveToolbar; // @synthesize approoveToolbar=_approoveToolbar;
@property(nonatomic) __weak UIBarButtonItem *leftToolButton; // @synthesize leftToolButton=_leftToolButton;
@property(nonatomic) __weak UIBarButtonItem *rightToolButton; // @synthesize rightToolButton=_rightToolButton;
@property(nonatomic) __weak UITextView *legalText; // @synthesize legalText=_legalText;
@property(nonatomic) __weak UILabel *mainTitle; // @synthesize mainTitle=_mainTitle;
- (void).cxx_destruct;
- (void)viewSafeAreaInsetsDidChange;
- (void)setLinkText:(id)arg1;
- (void)learnMoreButtonTapped;
- (void)setDescriptionText:(id)arg1 linkButton:(id)arg2;
- (long long)positionForBar:(id)arg1;
- (void)disagree:(id)arg1;
- (void)agree:(id)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

