//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "DKDiagnosticInputs.h"

@class NSString;

@interface PearlDiagnosticsInputs : NSObject <DKDiagnosticInputs>
{
    int _action;
    unsigned int _expirationInterval;
    int _errorCode;
    NSString *_actionString;
}

@property(nonatomic) int errorCode; // @synthesize errorCode=_errorCode;
@property(nonatomic) unsigned int expirationInterval; // @synthesize expirationInterval=_expirationInterval;
@property(nonatomic) int action; // @synthesize action=_action;
@property(retain, nonatomic) NSString *actionString; // @synthesize actionString=_actionString;
- (void).cxx_destruct;
- (_Bool)validateAndInitializeParameters:(id)arg1;
- (_Bool)validateAndInitializeSpecifications:(id)arg1;
- (_Bool)validateAndInitializePredicates:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

