//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@interface UIViewController (PearlDiagnosticsPrivate)
- (void)_addSubViewController:(id)arg1;
- (void)_addSubViewController:(id)arg1 toView:(id)arg2;
@end

