//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "PUVideoEditScrubberControllerDelegate.h"
#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"
#import "UICollectionViewDelegateFlowLayout.h"
#import "UINavigationBarDelegate.h"

@class AVPlayerViewController, ImageDataSource, NSArray, NSIndexPath, NSString, PUVideoEditScrubberController, UIBarButtonItem, UICollectionView, UIImageView, UINavigationBar, UINavigationItem, UIView, UIView<PLVideoOverlayButton>;

@interface UnlockApproveViewController : UIViewController <PUVideoEditScrubberControllerDelegate, UICollectionViewDelegate, UICollectionViewDataSource, UICollectionViewDelegateFlowLayout, UINavigationBarDelegate>
{
    ImageDataSource *_dataSource;
    unsigned long long _currentImageSetImageCount;
    NSIndexPath *_currentIndex;
    unsigned long long _currentPage;
    NSArray *_imagesOnPage;
    unsigned long long _totalNumberOfImages;
    unsigned long long _numberOfPages;
    unsigned long long _currentReviewedImages;
    int _cellDisplay;
    UIView<PLVideoOverlayButton> *_videoOverlayPlayButton;
    PUVideoEditScrubberController *_scrubberController;
    UIView *_enrollCellView;
    UIImageView *_enrollImageView;
    AVPlayerViewController *_enrollPlayerController;
    _Bool _isPlaying;
    _Bool _isSeeking;
    _Bool _hasPendingTime;
    CDStruct_1b6d18a9 _pendingTime;
    UICollectionView *_unlockImagesCollection;
    UINavigationBar *_reviewNavBar;
    UIBarButtonItem *_leftArrowButton;
    UIBarButtonItem *_rightArrowButton;
    UINavigationItem *_titleView;
    UIBarButtonItem *_declineBarButton;
    UIBarButtonItem *_playPauseBarButton;
    UIBarButtonItem *_approveBarButton;
    UIView *_movieScrubber;
}

+ (void)_enqueueOverlayPlayButton:(id)arg1;
+ (id)_dequeueOverlayPlayButton;
@property(nonatomic) __weak UIView *movieScrubber; // @synthesize movieScrubber=_movieScrubber;
@property(nonatomic) __weak UIBarButtonItem *approveBarButton; // @synthesize approveBarButton=_approveBarButton;
@property(retain, nonatomic) UIBarButtonItem *playPauseBarButton; // @synthesize playPauseBarButton=_playPauseBarButton;
@property(nonatomic) __weak UIBarButtonItem *declineBarButton; // @synthesize declineBarButton=_declineBarButton;
@property(nonatomic) __weak UINavigationItem *titleView; // @synthesize titleView=_titleView;
@property(nonatomic) __weak UIBarButtonItem *rightArrowButton; // @synthesize rightArrowButton=_rightArrowButton;
@property(nonatomic) __weak UIBarButtonItem *leftArrowButton; // @synthesize leftArrowButton=_leftArrowButton;
@property(nonatomic) __weak UINavigationBar *reviewNavBar; // @synthesize reviewNavBar=_reviewNavBar;
@property(nonatomic) __weak UICollectionView *unlockImagesCollection; // @synthesize unlockImagesCollection=_unlockImagesCollection;
- (void).cxx_destruct;
- (void)_seekToTime:(double)arg1;
- (void)_handleDidFinishSeekToPendingTime:(_Bool)arg1;
- (void)_updateFromPendingTime;
- (void)scrubberController:(id)arg1 valueDidChange:(double)arg2;
- (unsigned long long)supportedInterfaceOrientations;
- (void)setForwardArrowEnabled:(_Bool)arg1;
- (void)setBackArrowEnabled:(_Bool)arg1;
- (void)enrollVideoPlayedToEnd;
- (void)playPausePressed:(id)arg1;
- (void)videoIsPaused;
- (void)videoIsPlaying;
- (void)displayPlayButton:(_Bool)arg1;
- (void)playButtonClicked:(id)arg1;
- (unsigned long long)lastReviewedPage;
- (int)whichImageSetType:(id)arg1;
- (long long)positionForBar:(id)arg1;
- (void)turnPage:(_Bool)arg1;
- (void)prepareForTurningPage:(_Bool)arg1;
- (void)selectedCellsChanged;
- (struct CGSize)countCellSize;
- (unsigned long long)totalNumberOfMatch;
- (unsigned long long)totalNumberOfEnrollVideos;
- (unsigned long long)totalNumberOfImages;
- (unsigned long long)numberOfPages;
- (id)approveStateImageView:(_Bool)arg1 frame:(struct CGRect)arg2;
- (id)setTitle:(id)arg1 subtitle:(id)arg2;
- (void)setCellImageStatus:(id)arg1 approved:(_Bool)arg2;
- (id)imagesForPage:(unsigned long long)arg1;
- (void)setupCollectionViewCells;
- (void)loadImagePreviewOnCell:(id)arg1 indexPath:(id)arg2;
- (void)collectionView:(id)arg1 didDeselectItemAtIndexPath:(id)arg2;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)collectionView:(id)arg1 didEndDisplayingCell:(id)arg2 forItemAtIndexPath:(id)arg3;
- (void)collectionView:(id)arg1 willDisplayCell:(id)arg2 forItemAtIndexPath:(id)arg3;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (void)displayDeclineAlertForImageSet:(id)arg1 title:(id)arg2 message:(id)arg3 defaultButton:(id)arg4 cancel:(id)arg5;
- (void)reviewFinished;
- (void)goToForwardPage;
- (void)goToPreviousPage;
- (void)leftArrowPressed:(id)arg1;
- (void)rightArrowPressed:(id)arg1;
- (void)cancelPressed:(id)arg1;
- (void)imageSetDeclined:(id)arg1;
- (void)imageSetApproved:(id)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

