//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBUIRemoteAlertServiceViewController.h"

@class NSNumber, NSXPCConnection;

@interface SSActiveViewController : SBUIRemoteAlertServiceViewController
{
    _Bool _userInfoSet;
    NSNumber *isPausedNumber;
    NSXPCConnection *helperToolConnection;
    id helperTool;
}

@property _Bool userInfoSet; // @synthesize userInfoSet=_userInfoSet;
@property(retain) id helperTool; // @synthesize helperTool;
@property(retain) NSXPCConnection *helperToolConnection; // @synthesize helperToolConnection;
@property(retain) NSNumber *isPausedNumber; // @synthesize isPausedNumber;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)sendResultAndTerminate:(int)arg1;
- (void)showControls;
- (void)setUserInfo:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

