//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DSLogLine.h"

@class NSString;

@interface DABackupRestoreLogLine : DSLogLine
{
}

@property(readonly, nonatomic) long long backupRestoreEventType;
@property(readonly, nonatomic) _Bool didSucceed;
@property(readonly, nonatomic) long long backupCode;
@property(readonly, nonatomic) NSString *eventSubType;

@end

