//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DKDiagnosticController.h"

@class AppCrashHistoryInputs;

@interface AppCrashHistoryController : DKDiagnosticController
{
    AppCrashHistoryInputs *_inputs;
}

@property(retain, nonatomic) AppCrashHistoryInputs *inputs; // @synthesize inputs=_inputs;
- (void).cxx_destruct;
- (id)appNameForBundleID:(id)arg1;
- (id)userFriendlyAppNameForBundleID:(id)arg1;
- (void)parseLogsWithCollector:(id)arg1;
- (void)start;
- (void)setupWithInputs:(id)arg1 responder:(id)arg2;

@end

