//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@interface _WDInteractiveChartHeartRateOverlayKey : NSObject <NSCopying>
{
    long long _contextType;
    long long _timeScope;
}

@property(nonatomic) long long timeScope; // @synthesize timeScope=_timeScope;
@property(nonatomic) long long contextType; // @synthesize contextType=_contextType;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)initWithContextType:(long long)arg1 timeScope:(long long)arg2;

@end

