//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HKDisplayType.h"

@interface HKDisplayType (WDPortraitSamplesExistChartDataProvider)
- (struct NSArray *)_menstruationAccentPointsFromSamples:(id)arg1 accentYValue:(long long)arg2;
- (struct NSArray *)_ovulationAccentPointsFromSamples:(id)arg1 accentYValue:(long long)arg2;
- (struct NSArray *)accentPointsFromSamples:(id)arg1 accentYValue:(long long)arg2;
@end

