//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HKSwitchTableViewCell.h"

#import "HKSwitchTableViewCellDelegate.h"
#import "WDFavoriteDisplayTypesControllerObserver.h"

@class HKDisplayType, NSString, WDFavoriteDisplayTypesController;

@interface HKFavoriteSwitchTableViewCell : HKSwitchTableViewCell <HKSwitchTableViewCellDelegate, WDFavoriteDisplayTypesControllerObserver>
{
    WDFavoriteDisplayTypesController *_favoriteDisplayTypesController;
    HKDisplayType *_displayType;
}

+ (id)defaultReuseIdentifier;
@property(retain, nonatomic) HKDisplayType *displayType; // @synthesize displayType=_displayType;
@property(retain, nonatomic) WDFavoriteDisplayTypesController *favoriteDisplayTypesController; // @synthesize favoriteDisplayTypesController=_favoriteDisplayTypesController;
- (void).cxx_destruct;
- (void)favoriteDisplayTypesControllerDidUpdate:(id)arg1;
- (void)switchCellValueChanged:(id)arg1 value:(_Bool)arg2;
- (void)updateSwitchValue;
- (void)dealloc;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

