//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HKMedicalRecord.h"

#import "WDMedicalRecordDisplayable.h"

@class HKInspectableValueCollection, NSDate, NSString;

@interface HKMedicalRecord (DisplayItemAdditions) <WDMedicalRecordDisplayable>
+ (id)_sortedDisplayItemsForDosages:(id)arg1;
+ (id)_periodDisplayItemWithStartDate:(id)arg1 endDate:(id)arg2 startTitle:(id)arg3 endTitle:(id)arg4 instanceTitle:(id)arg5 rangeTitle:(id)arg6;
@property(readonly, nonatomic) long long recordCategoryType;
@property(readonly, nonatomic) _Bool isDateLess;
@property(readonly, nonatomic) _Bool isDisplayable;
@property(readonly, nonatomic) NSString *meaningfulDateString;
@property(readonly, nonatomic) NSDate *meaningfulDate;
@property(readonly, nonatomic) NSString *meaningfulDateTitle;
- (id)codings;
@property(readonly, nonatomic) HKInspectableValueCollection *chartValue;
- (void)fetchChartValueWithRangeWithHealthStore:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)fetchStructuredFieldItemsWithHealthRecordsStore:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)fetchDisplayNameItemWithHealthRecordsStore:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)fetchDetailItemsWithHealthRecordsStore:(id)arg1 completion:(CDUnknownBlockType)arg2;
@property(readonly, nonatomic) NSString *subtitle;
@property(readonly, copy, nonatomic) NSString *title;
- (void)fetchTitleWithHealthRecordsStore:(id)arg1 completion:(CDUnknownBlockType)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@end

