//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HKObjectType.h"

@interface HKObjectType (WDFormatters)
- (Class)wd_valueFormatterClass;
- (id)wd_numberFormatterForUnit:(id)arg1 decimalPrecisionRule:(id)arg2 formattingContext:(long long)arg3;
- (id)wd_numberFormatterForUnit:(id)arg1 decimalPrecisionRule:(id)arg2;
@end

