//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HKReportView.h"

@class NSLayoutConstraint;

@interface HKReportContentView : HKReportView
{
    NSLayoutConstraint *_widthConstraint;
    NSLayoutConstraint *_heightConstraint;
}

- (void).cxx_destruct;
- (void)fitContents;
- (void)setHeight:(double)arg1;
- (void)setWidth:(double)arg1;
- (void)_setupView;
- (id)init;

@end

