//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HKReportContent.h"

@class _HKReportSeparatorView;

@interface HKReportSeparatorContent : HKReportContent
{
    _HKReportSeparatorView *_view;
}

@property(retain, nonatomic) _HKReportSeparatorView *view; // @synthesize view=_view;
- (void).cxx_destruct;
- (void)renderAndDraw:(_Bool)arg1;
- (id)init;

@end

