//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class NSURL;

@interface WDClinicalSettingsViewAnalyticsDataViewControllerFileCell : UITableViewCell
{
    NSURL *_fileURL;
}

+ (id)defaultReuseIdentifier;
@property(retain, nonatomic) NSURL *fileURL; // @synthesize fileURL=_fileURL;
- (void).cxx_destruct;
- (id)description;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

