//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class WDProfile;

@interface WDClinicalOnboardingManager : NSObject
{
    WDProfile *_profile;
}

@property(retain, nonatomic) WDProfile *profile; // @synthesize profile=_profile;
- (void).cxx_destruct;
- (id)_appTabBarController;
- (void)startOauthLogonSessionForGateway:(id)arg1;
- (void)onboardAsNewGateway:(id)arg1 inBatch:(id)arg2;
- (void)onboardWithActivity:(id)arg1;
- (id)initWithProfile:(id)arg1;
- (id)init;

@end

