//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SFSafariViewControllerDelegate.h"

@class HKHealthRecordsStore, NSString, NSURL;

@interface WDClinicalSourcesDataProviderSafariDelegate : NSObject <SFSafariViewControllerDelegate>
{
    HKHealthRecordsStore *_healthRecordsStore;
    NSURL *_loginURL;
}

+ (id)sharedSafariDelegate;
@property(retain, nonatomic) NSURL *loginURL; // @synthesize loginURL=_loginURL;
@property(retain, nonatomic) HKHealthRecordsStore *healthRecordsStore; // @synthesize healthRecordsStore=_healthRecordsStore;
- (void).cxx_destruct;
- (id)safariViewController:(id)arg1 excludedActivityTypesForURL:(id)arg2 title:(id)arg3;
- (void)safariViewControllerDidFinish:(id)arg1;
- (void)_postAWDMetricForSafariCancellation:(id)arg1;
- (id)init;
- (id)_init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

