//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WDTableViewSection.h"

@interface WDClinicalSettingsAboutSection : WDTableViewSection
{
}

- (void)didSelectRow:(unsigned long long)arg1 representedByCell:(id)arg2 withCompletion:(CDUnknownBlockType)arg3;
- (id)_tableViewHealthRecordsInfoCell:(id)arg1;
- (id)_tableViewPrivacyInfoCell:(id)arg1;
- (id)cellForRow:(unsigned long long)arg1 table:(id)arg2;
- (unsigned long long)numberOfRows;

@end

