//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

#import "HKDateCacheObserver.h"
#import "WDDashboardCellChartSourceDelegate.h"
#import "WDDashboardCellForceTouchDelegate.h"
#import "WDDashboardCellPrimaryValueSourceDelegate.h"
#import "WDDashboardCellSecondaryValueSourceDelegate.h"
#import "WDDisplayTypeDetailViewControllerChartCellType.h"
#import "WDDottedAverageBackgroundViewDataSource.h"

@class HKDateCache, HKDisplayCategory, HKUnitPreferenceController, NSString, UIImageView, UILabel, WDChart, WDDottedAverageBackgroundView;

@interface WDDashboardTableViewCell_Eagle : UITableViewCell <WDDashboardCellPrimaryValueSourceDelegate, WDDashboardCellSecondaryValueSourceDelegate, WDDashboardCellChartSourceDelegate, HKDateCacheObserver, WDDottedAverageBackgroundViewDataSource, WDDisplayTypeDetailViewControllerChartCellType, WDDashboardCellForceTouchDelegate>
{
    UIImageView *_backgroundImageView;
    UIImageView *_categoryIcon;
    UILabel *_averageLabel;
    UIImageView *_averageUnitIcon;
    UILabel *_currentValueLabel;
    UILabel *_lastUpdatedLabel;
    UILabel *_titleLabel;
    WDDottedAverageBackgroundView *_chartBackground;
    HKDateCache *_dateCache;
    HKDisplayCategory *_displayCategory;
    HKUnitPreferenceController *_unitController;
    unsigned long long _displayMode;
    unsigned long long _marginMode;
    id <WDDashboardCellPrimaryValueSource> _primaryValueSource;
    id <WDDashboardCellSecondaryValueSource> _secondaryValueSource;
    id <WDDashboardCellChartSource> _chartSource;
    long long _timeScope;
    WDChart *_chartView;
}

+ (double)preferredCellHeightForChartSource:(id)arg1 timeScope:(long long)arg2 displayMode:(unsigned long long)arg3;
@property(readonly, nonatomic) WDChart *chartView; // @synthesize chartView=_chartView;
@property(nonatomic) long long timeScope; // @synthesize timeScope=_timeScope;
@property(readonly, nonatomic) id <WDDashboardCellChartSource> chartSource; // @synthesize chartSource=_chartSource;
@property(readonly, nonatomic) id <WDDashboardCellSecondaryValueSource> secondaryValueSource; // @synthesize secondaryValueSource=_secondaryValueSource;
@property(readonly, nonatomic) id <WDDashboardCellPrimaryValueSource> primaryValueSource; // @synthesize primaryValueSource=_primaryValueSource;
@property(nonatomic) unsigned long long marginMode; // @synthesize marginMode=_marginMode;
@property(nonatomic) unsigned long long displayMode; // @synthesize displayMode=_displayMode;
- (void).cxx_destruct;
- (id)backgroundView:(id)arg1 formattedStringWithValue:(id)arg2 numberFormatter:(id)arg3;
- (void)dateCacheDidUpdate:(id)arg1 onNotification:(id)arg2;
- (struct CGRect)forceTouchFrame;
- (void)chartSourceDidUpdateHistoricalData:(id)arg1;
- (void)secondaryValueSourceDidUpdate:(id)arg1;
- (void)primaryValueSourceDidUpdate:(id)arg1;
- (_Bool)_shouldHideChart;
- (id)_getLastUpdatedText;
- (id)_getCategoryIcon;
- (id)_currentValueTextWithValueFontSize:(double)arg1 unitFontSize:(double)arg2;
- (id)_getLastUpdatedDate;
- (id)_averageLabelText;
- (void)_updateUI;
- (void)_updateImageUI;
- (void)_setupSubviews;
- (id)_timeAxisDescriptor;
- (void)_updateTimeBasedUI;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)setPrimaryValueSource:(id)arg1 secondaryValueSource:(id)arg2 chartSource:(id)arg3;
- (void)layoutSubviews;
- (void)setDisplayCategory:(id)arg1;
- (void)dealloc;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2 dateCache:(id)arg3 unitController:(id)arg4 timeScope:(long long)arg5;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

