//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "WDDashboardCellPrimaryValueSource.h"

@class HKDisplayCategory, HKDisplayType, NSDate, NSSet, NSString, WDProfile;

@interface WDDashboardSummaryItem : NSObject <WDDashboardCellPrimaryValueSource>
{
    id <WDDashboardCellPrimaryValueSourceDelegate> _primaryValueSourceDelegate;
    HKDisplayType *_displayType;
    HKDisplayCategory *_displayCategory;
    NSDate *_lastUpdated;
    NSSet *_summaries;
    WDProfile *_profile;
    id <WDDataProviderValue> _valueFormatter;
}

@property(retain, nonatomic) id <WDDataProviderValue> valueFormatter; // @synthesize valueFormatter=_valueFormatter;
@property(retain, nonatomic) WDProfile *profile; // @synthesize profile=_profile;
@property(readonly, nonatomic) NSSet *summaries; // @synthesize summaries=_summaries;
@property(readonly, nonatomic) NSDate *lastUpdated; // @synthesize lastUpdated=_lastUpdated;
@property(readonly, nonatomic) HKDisplayCategory *displayCategory; // @synthesize displayCategory=_displayCategory;
@property(readonly, nonatomic) HKDisplayType *displayType; // @synthesize displayType=_displayType;
@property(nonatomic) __weak id <WDDashboardCellPrimaryValueSourceDelegate> primaryValueSourceDelegate; // @synthesize primaryValueSourceDelegate=_primaryValueSourceDelegate;
- (void).cxx_destruct;
- (_Bool)containsActivitySummary;
- (id)mostRecentValueWithValueFont:(id)arg1 unitFont:(id)arg2;
@property(readonly, nonatomic) NSString *primaryValueContextualText;
- (id)initWithSystolicSummary:(id)arg1 diastolicSummary:(id)arg2 profile:(id)arg3;
- (id)initWithSummary:(id)arg1 profile:(id)arg2;

@end

