//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HKTableViewController.h"

#import "WDUserActivityResponder.h"

@class HKDataMetadataDetailSection, HKValueRange, WDInteractiveChartViewController;

@interface WDFixedChartViewController : HKTableViewController <WDUserActivityResponder>
{
    HKValueRange *_fixedRange;
    WDInteractiveChartViewController *_chartController;
    HKDataMetadataDetailSection *_metadataSection;
}

@property(readonly, nonatomic) HKDataMetadataDetailSection *metadataSection; // @synthesize metadataSection=_metadataSection;
@property(readonly, nonatomic) WDInteractiveChartViewController *chartController; // @synthesize chartController=_chartController;
@property(readonly, nonatomic) HKValueRange *fixedRange; // @synthesize fixedRange=_fixedRange;
- (void).cxx_destruct;
- (id)applyTransitionActivity:(id)arg1;
- (void)applyChangeActivity:(id)arg1;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (_Bool)tableView:(id)arg1 shouldHighlightRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)cellForChart;
- (void)viewDidLoad;
- (id)initWithInteractiveChartViewController:(id)arg1 sessionSample:(id)arg2 profile:(id)arg3 title:(id)arg4;

@end

