//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WDInteractiveChartDataFormatter.h"

@class NSString;

@interface WDInteractiveChartNumberFormatter : WDInteractiveChartDataFormatter
{
    NSString *_unitFormatString;
}

@property(copy, nonatomic) NSString *unitFormatString; // @synthesize unitFormatString=_unitFormatString;
- (void).cxx_destruct;
- (id)formattedValueStringForChartData:(id)arg1 options:(long long)arg2;
- (id)formattedSelectedRangeLabelDataWithChartData:(id)arg1;
- (id)_formattedStringWithValue:(id)arg1 formatter:(id)arg2;
- (id)init;

@end

