//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WDInteractiveChartViewController.h"

@class WDMedicalRecordAnnotationViewDataSource;

@interface WDInteractiveChartMedicalRecordController : WDInteractiveChartViewController
{
    WDMedicalRecordAnnotationViewDataSource *_annotationViewDataSource;
}

@property(retain, nonatomic) WDMedicalRecordAnnotationViewDataSource *annotationViewDataSource; // @synthesize annotationViewDataSource=_annotationViewDataSource;
- (void).cxx_destruct;
- (id)_colorForDisplayType:(id)arg1;
- (void)updateSelectionAnnotationDataSourceForContext:(id)arg1 displayType:(id)arg2 timeScope:(long long)arg3;
- (void)installAnnotationDataSourceForAnnotationView:(id)arg1;
- (double)dateSelectorHeight;

@end

