//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WDInteractiveChartSinglePointData.h"

@class HKInspectableValueInRange;

@interface WDInteractiveChartMedicalRecordData : WDInteractiveChartSinglePointData
{
    HKInspectableValueInRange *_valueInRange;
}

@property(retain, nonatomic) HKInspectableValueInRange *valueInRange; // @synthesize valueInRange=_valueInRange;
- (void).cxx_destruct;

@end

