//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WDMedicalRecordGroupableCell.h"

@class NSString, UILabel;

@interface WDMedicalRecordSectionHeaderCell : WDMedicalRecordGroupableCell
{
    UILabel *_titleLabel;
}

+ (double)_titleLabelLastBaselineToBottom;
+ (double)_titleLabelTopToFirstBaseline;
+ (id)_titleLabelFont;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void).cxx_destruct;
@property(copy, nonatomic) NSString *title;
- (void)setupSubviews;

@end

