//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "WDInteractiveChartAnnotationViewDataSource.h"

@class HKInspectableValueInRange, NSString, UILabel, UIStackView, WDReferenceRangeView;

@interface WDMedicalRecordAnnotationViewDataSource : NSObject <WDInteractiveChartAnnotationViewDataSource>
{
    HKInspectableValueInRange *_valueInRange;
    UIStackView *_dateColumn;
    UILabel *_upperDateLabel;
    UILabel *_lowerDateLabel;
    WDReferenceRangeView *_referenceRangeView;
}

@property(retain, nonatomic) WDReferenceRangeView *referenceRangeView; // @synthesize referenceRangeView=_referenceRangeView;
@property(retain, nonatomic) UILabel *lowerDateLabel; // @synthesize lowerDateLabel=_lowerDateLabel;
@property(retain, nonatomic) UILabel *upperDateLabel; // @synthesize upperDateLabel=_upperDateLabel;
@property(retain, nonatomic) UIStackView *dateColumn; // @synthesize dateColumn=_dateColumn;
@property(retain, nonatomic) HKInspectableValueInRange *valueInRange; // @synthesize valueInRange=_valueInRange;
- (void).cxx_destruct;
- (void)_updateReferenceRangeViewWithValueInRange:(id)arg1;
- (void)_updateDateColumnWithDate:(id)arg1;
- (void)_setupReferenceRangeView;
- (void)_setupDateColumn;
- (id)columnViewForColumnAtIndex:(long long)arg1;
- (long long)numberOfColumnsForAnnotationView:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

