//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WDMedicalRecordGroupableCell.h"

@class NSString, UIImageView, UILabel;

@interface WDMedicalRecordTimelineContentSubtitleCell : WDMedicalRecordGroupableCell
{
    NSString *_titleString;
    NSString *_subtitleString;
    UILabel *_titleLabel;
    UILabel *_subtitleLabel;
    UIImageView *_disclosureChevronView;
}

+ (double)_subtitleLabelLastBaselineToBottom;
+ (double)_subtitleLabelTopToFirstBaseline;
+ (id)_subtitleLabelFont;
+ (double)_titleLabelTopToFirstBaseline;
+ (id)_titleLabelFont;
@property(retain, nonatomic) UIImageView *disclosureChevronView; // @synthesize disclosureChevronView=_disclosureChevronView;
@property(retain, nonatomic) UILabel *subtitleLabel; // @synthesize subtitleLabel=_subtitleLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void).cxx_destruct;
@property(copy, nonatomic) NSString *subtitle;
@property(copy, nonatomic) NSString *title;
- (void)setupSubviews;

@end

