//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WDPortraitDataProvider.h"

@interface WDMostRecentDateSecondaryValueDataProvider : WDPortraitDataProvider
{
}

- (id)_mostRecentPredicate;
- (_Bool)_shouldPrefixSecondaryValueWithDot;
- (id)_secondaryValueFormatString;
- (id)_mostRecentValueQueryWithCompletion:(CDUnknownBlockType)arg1;
- (id)fetchOperationWithCompletion:(CDUnknownBlockType)arg1;
- (id)secondaryValue;

@end

