//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "HKDateCacheObserver.h"

@class HKActivitySummary, HKFetchOperation, HKQuery, NSCache, NSCalendar, NSHashTable, NSMutableDictionary, NSString, WDProfile;

@interface WDPortraitActivitySummaryChartDataProvider : NSObject <HKDateCacheObserver>
{
    NSHashTable *_observers;
    NSCache *_activitySummaryForTimeScopeCache;
    NSMutableDictionary *_activitySummaryChartPointsForTimeScopeCache;
    NSCalendar *_cachedCalendar;
    HKFetchOperation *_outstandingFetchOperation;
    HKQuery *_observerQuery;
    NSCache *_hourlyActivitySummaryCache;
    WDProfile *_profile;
}

@property(retain, nonatomic) WDProfile *profile; // @synthesize profile=_profile;
- (void).cxx_destruct;
- (void)_hourlyActivityDataForStartDate:(id)arg1 endDate:(id)arg2 healthStore:(id)arg3 calendar:(id)arg4 handler:(CDUnknownBlockType)arg5;
- (id)_hourlySummariesFromStartDate:(id)arg1 endDate:(id)arg2 calendar:(id)arg3 moveData:(id)arg4 exerciseData:(id)arg5 standData:(id)arg6 dayGoalData:(id)arg7;
- (id)_buildHourlyActivitySummaryFromDate:(id)arg1 calendar:(id)arg2 moveQuantity:(id)arg3 exerciseQuantity:(id)arg4 standQuantity:(id)arg5 moveGoal:(id)arg6 exerciseGoal:(id)arg7 standGoal:(id)arg8;
- (void)_hourActivitySummariesForDateRange:(id)arg1 pageHandler:(CDUnknownBlockType)arg2;
- (void)_hourlyActivityPageDataArrived:(id)arg1 pageNumber:(id)arg2 error:(id)arg3;
- (void)_hourlyPageInProgress:(id)arg1;
- (void)_submitHourlyQueryForPageNumber:(id)arg1 startDate:(id)arg2 endDate:(id)arg3;
- (id)_hourActivitySummariesForDateRange:(id)arg1;
- (id)_buildActivitySummaryFromAverages:(struct _WDActivitySummaryAverages)arg1 startDate:(id)arg2 calendar:(id)arg3 energyUnit:(id)arg4 exerciseUnit:(id)arg5 standHourUnit:(id)arg6;
- (void)_monthActivitySummariesForCachedData:(id)arg1 handler:(CDUnknownBlockType)arg2;
- (id)_monthActivitySummariesForDateRange:(id)arg1;
- (id)_dayActivitySummariesForDateRange:(id)arg1;
- (id)cachedCalendar;
- (void)dateCacheDidUpdate:(id)arg1 onNotification:(id)arg2;
- (void)_unitPreferencesDidUpdate:(id)arg1;
- (void)_alertObserversDidUpdateValues;
- (void)_clearCaches;
- (void)_stopActivitySummaryChangeObserver;
- (void)_setupActivitySummaryChangeObserver;
- (id)_queriesForTimeScope:(long long)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (id)_fetchOperationForTimeScope:(long long)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (void)_transitionToFetchFailureForTimeScope:(long long)arg1;
- (void)_fetchValueWithRetryCount:(long long)arg1;
- (void)_partitionAndProcessActivitySummariesForAllTimeScopes:(id)arg1;
- (id)_chartPointsWithMove:(double)arg1 moveGoal:(double)arg2 exercise:(double)arg3 exerciseGoal:(double)arg4 standHour:(double)arg5 standHourGoal:(double)arg6 timestamp:(id)arg7;
- (id)_activitySummaryChartPointsForActivitySummariesOfYearScope:(id)arg1;
- (void)removeObserver:(id)arg1;
- (void)addObserver:(id)arg1;
- (id)activitySummaryChartPointsForTimeScope:(long long)arg1;
- (id)activitySummariesForDateRange:(id)arg1 timeScope:(long long)arg2;
- (id)activitySummariesForTimeScope:(long long)arg1;
@property(readonly, nonatomic) HKActivitySummary *latestActivitySummary;
- (_Bool)activitySummariesAreLoading;
- (void)dealloc;
- (id)initWithProfile:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

