//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WDPortraitSampleQueryChartDataProvider.h"

@interface WDPortraitTimePeriodHorizontalLineChartDataProvider : WDPortraitSampleQueryChartDataProvider
{
}

- (id)createChartPointsFromStartDate:(id)arg1 toEndDate:(id)arg2 yValue:(id)arg3;
- (id)generateChartPointsFromSamples:(id)arg1;

@end

