//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WDPortraitChartDataProvider.h"

@interface WDPortraitDailySleepChartDataProvider : WDPortraitChartDataProvider
{
}

- (id)averageSecondaryValueFormatString;
- (id)generateAverageValue;
- (id)_chartPointFromQueryResult:(id)arg1;
- (struct NSArray *)_dailyChartPointsFromQueryResults:(id)arg1;
- (struct NSArray *)_monthlyChartPointsFromQueryResults:(id)arg1 startDate:(id)arg2;
- (id)generateChartPoints;
- (id)_queriesWithCompletion:(CDUnknownBlockType)arg1;
- (id)fetchOperationWithCompletion:(CDUnknownBlockType)arg1;

@end

