//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UIStateRestoring.h"

@class HKDateCache, HKDisplayCategoryController, HKDisplayTypeController, HKHealthRecordsStore, HKHealthStore, HKManualEntryValidationController, HKUCUMUnitDisplayConverter, HKUnitPreferenceController, NSString, WDChartDataCacheController, WDClinicalSourcesDataProvider, WDFavoriteDisplayTypesController, WDMedicalRecordCountProvider, WDNotificationManager, WDSampleTypeDateRangeController, WDSampleTypeUpdateController, WDSelectedTimeScopeController, WDSourceOrderController, WDStoreDataProvider, WDUserActivityManager, WDUserDefaults, _HKWheelchairUseCharacteristicCache;

@interface WDProfile : NSObject <UIStateRestoring>
{
    WDClinicalSourcesDataProvider *_clinicalSourcesDataProvider;
    HKHealthRecordsStore *_healthRecordsStore;
    HKDateCache *_dateCache;
    HKDisplayCategoryController *_displayCategoryController;
    HKDisplayTypeController *_displayTypeController;
    HKHealthStore *_healthStore;
    HKManualEntryValidationController *_manualEntryValidationController;
    HKUnitPreferenceController *_unitController;
    HKUCUMUnitDisplayConverter *_ucumDisplayConverter;
    WDChartDataCacheController *_dataCacheController;
    WDFavoriteDisplayTypesController *_favoriteDisplayTypesController;
    WDMedicalRecordCountProvider *_medicalRecordCountProvider;
    WDNotificationManager *_notificationManager;
    WDSelectedTimeScopeController *_selectedTimeScopeController;
    WDSampleTypeUpdateController *_updateController;
    WDSampleTypeDateRangeController *_sampleTypeDateRangeController;
    WDStoreDataProvider *_storeDataProvider;
    WDSourceOrderController *_sourceOrderController;
    WDUserActivityManager *_userActivityManager;
    WDUserDefaults *_userDefaults;
    _HKWheelchairUseCharacteristicCache *_wheelchairUseCharacteristicCache;
}

@property(readonly, nonatomic) _HKWheelchairUseCharacteristicCache *wheelchairUseCharacteristicCache; // @synthesize wheelchairUseCharacteristicCache=_wheelchairUseCharacteristicCache;
@property(readonly, nonatomic) WDUserDefaults *userDefaults; // @synthesize userDefaults=_userDefaults;
@property(readonly, nonatomic) WDUserActivityManager *userActivityManager; // @synthesize userActivityManager=_userActivityManager;
@property(readonly, nonatomic) WDSourceOrderController *sourceOrderController; // @synthesize sourceOrderController=_sourceOrderController;
@property(readonly, nonatomic) WDStoreDataProvider *storeDataProvider; // @synthesize storeDataProvider=_storeDataProvider;
@property(readonly, nonatomic) WDSampleTypeDateRangeController *sampleTypeDateRangeController; // @synthesize sampleTypeDateRangeController=_sampleTypeDateRangeController;
@property(readonly, nonatomic) WDSampleTypeUpdateController *updateController; // @synthesize updateController=_updateController;
@property(readonly, nonatomic) WDSelectedTimeScopeController *selectedTimeScopeController; // @synthesize selectedTimeScopeController=_selectedTimeScopeController;
@property(readonly, nonatomic) WDNotificationManager *notificationManager; // @synthesize notificationManager=_notificationManager;
@property(readonly, nonatomic) WDMedicalRecordCountProvider *medicalRecordCountProvider; // @synthesize medicalRecordCountProvider=_medicalRecordCountProvider;
@property(readonly, nonatomic) WDFavoriteDisplayTypesController *favoriteDisplayTypesController; // @synthesize favoriteDisplayTypesController=_favoriteDisplayTypesController;
@property(readonly, nonatomic) WDChartDataCacheController *dataCacheController; // @synthesize dataCacheController=_dataCacheController;
@property(readonly, nonatomic) HKUCUMUnitDisplayConverter *ucumDisplayConverter; // @synthesize ucumDisplayConverter=_ucumDisplayConverter;
@property(readonly, nonatomic) HKUnitPreferenceController *unitController; // @synthesize unitController=_unitController;
@property(readonly, nonatomic) HKManualEntryValidationController *manualEntryValidationController; // @synthesize manualEntryValidationController=_manualEntryValidationController;
@property(readonly, nonatomic) HKHealthStore *healthStore; // @synthesize healthStore=_healthStore;
@property(readonly, nonatomic) HKDisplayTypeController *displayTypeController; // @synthesize displayTypeController=_displayTypeController;
@property(readonly, nonatomic) HKDisplayCategoryController *displayCategoryController; // @synthesize displayCategoryController=_displayCategoryController;
@property(readonly, nonatomic) HKDateCache *dateCache; // @synthesize dateCache=_dateCache;
- (void).cxx_destruct;
- (void)_setHealthRecordsStore:(id)arg1;
@property(readonly, nonatomic) HKHealthRecordsStore *healthRecordsStore;
@property(readonly, nonatomic) WDClinicalSourcesDataProvider *clinicalSourcesDataProvider;
- (id)_createHealthStore;
- (id)_initWithHealthStore:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) Class objectRestorationClass;
@property(readonly, nonatomic) id <UIStateRestoring> restorationParent;
@property(readonly) Class superclass;

@end

