//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WDSampleListDataProvider.h"

@class NSMutableArray, NSMutableDictionary;

@interface WDSleepListDataProvider : WDSampleListDataProvider
{
    NSMutableDictionary *_sleepData;
    NSMutableArray *_orderedKeys;
}

- (void).cxx_destruct;
- (id)dataListViewController:(id)arg1 viewControllerForItemAtIndexPath:(id)arg2;
- (void)dataListViewControllerDidDeleteAllData:(id)arg1;
- (void)dataListViewController:(id)arg1 didRemoveObjectAtIndex:(unsigned long long)arg2 forSection:(unsigned long long)arg3 sectionRemoved:(_Bool *)arg4;
- (id)dataListViewController:(id)arg1 secondaryTextForObject:(id)arg2;
- (id)dataListViewController:(id)arg1 textForObject:(id)arg2;
- (id)dataListViewController:(id)arg1 objectAtIndex:(unsigned long long)arg2 forSection:(unsigned long long)arg3;
- (id)_sleepSampleAtIndex:(unsigned long long)arg1 section:(unsigned long long)arg2;
- (unsigned long long)dataListViewController:(id)arg1 numberOfObjectsForSection:(unsigned long long)arg2;
- (id)dataListViewController:(id)arg1 titleForSection:(unsigned long long)arg2;
- (unsigned long long)numberOfSectionsForDataListViewController:(id)arg1;
- (long long)cellStyleForDataListViewController:(id)arg1;
- (id)_sleepDataDictionaryFromSamples:(id)arg1;
- (void)_callUpdateHandler;
- (id)sampleTypes;

@end

