//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIActivityIndicatorView, UILabel;

@interface WDSpinnerView : UIView
{
    UIActivityIndicatorView *_spinner;
    UILabel *_label;
}

- (void).cxx_destruct;
- (void)stopSpinner;
- (void)startSpinner;
- (void)setMessageWhileSpinning:(id)arg1;
@property(readonly, nonatomic, getter=isAnimating) _Bool animating;
- (void)_setupSubviews;
- (id)init;

@end

