//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class HKDisplayCategory, NSMutableArray;

@interface WDStoredDataCategory : NSObject
{
    NSMutableArray *_displayTypes;
    HKDisplayCategory *_category;
}

@property(retain) HKDisplayCategory *category; // @synthesize category=_category;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSMutableArray *displayTypes; // @synthesize displayTypes=_displayTypes;

@end

