//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class BatteryOutlineView, StrokedLabel, UIImageView;

@interface BatteryView : UIView
{
    _Bool _chargerConnected;
    _Bool _lowPowerMode;
    double _batteryLevel;
    double _lowBatteryThreshold;
    StrokedLabel *_batteryLabel;
    BatteryOutlineView *_batteryOutlineView;
    UIImageView *_lightningView;
}

+ (id)imageNamed:(id)arg1;
@property(retain, nonatomic) UIImageView *lightningView; // @synthesize lightningView=_lightningView;
@property(retain, nonatomic) BatteryOutlineView *batteryOutlineView; // @synthesize batteryOutlineView=_batteryOutlineView;
@property(retain, nonatomic) StrokedLabel *batteryLabel; // @synthesize batteryLabel=_batteryLabel;
@property(nonatomic) double lowBatteryThreshold; // @synthesize lowBatteryThreshold=_lowBatteryThreshold;
@property(nonatomic) _Bool lowPowerMode; // @synthesize lowPowerMode=_lowPowerMode;
@property(nonatomic) double batteryLevel; // @synthesize batteryLevel=_batteryLevel;
@property(nonatomic) _Bool chargerConnected; // @synthesize chargerConnected=_chargerConnected;
- (void).cxx_destruct;
- (void)updateAccessiblityLabel;
- (void)updateBatteryLevelLabelWithLowBatteryThreshold:(double)arg1;
- (void)hideLightningImage;
- (void)showLightningImage;
- (id)_queryConstraintBetweenView:(id)arg1 andView:(id)arg2;
- (struct CGSize)intrinsicContentSize;
- (void)_commonConfiguration;
- (void)awakeFromNib;
- (id)initWithFrame:(struct CGRect)arg1;

@end

