//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UITableViewDataSource.h"
#import "UITableViewDataSourcePrefetching.h"
#import "UITableViewDelegate.h"

@class FMAttributedStringRenderer, FMIPAccount, NSArray, NSCache, NSDictionary, NSString, UITableView, UITraitCollection;

@interface DeviceListDataSource : NSObject <UITableViewDataSource, UITableViewDelegate, UITableViewDataSourcePrefetching>
{
    _Bool _showAllDevicesSection;
    NSArray *_orderedKeys;
    UITableView *_tableView;
    FMIPAccount *_account;
    NSDictionary *_model;
    id _kvoToken;
    id _notificationToken;
    id _devicesLoadedNotificationToken;
    id _measurementSystemChangedNotificationToken;
    id _contentSizeCategoryDidChangeNotificationToken;
    id _locationUpdatedNotificationToken;
    id _deviceImageURLUpdatedNotificationToken;
    NSCache *_imageCache;
    NSCache *_rowHeightCache;
    double _axTextImageViewWidth;
    FMAttributedStringRenderer *_renderer;
    UITraitCollection *_traitCollection;
}

@property(retain, nonatomic) UITraitCollection *traitCollection; // @synthesize traitCollection=_traitCollection;
@property(retain, nonatomic) FMAttributedStringRenderer *renderer; // @synthesize renderer=_renderer;
@property(nonatomic) double axTextImageViewWidth; // @synthesize axTextImageViewWidth=_axTextImageViewWidth;
@property(retain, nonatomic) NSCache *rowHeightCache; // @synthesize rowHeightCache=_rowHeightCache;
@property(retain, nonatomic) NSCache *imageCache; // @synthesize imageCache=_imageCache;
@property(retain, nonatomic) id deviceImageURLUpdatedNotificationToken; // @synthesize deviceImageURLUpdatedNotificationToken=_deviceImageURLUpdatedNotificationToken;
@property(retain, nonatomic) id locationUpdatedNotificationToken; // @synthesize locationUpdatedNotificationToken=_locationUpdatedNotificationToken;
@property(retain, nonatomic) id contentSizeCategoryDidChangeNotificationToken; // @synthesize contentSizeCategoryDidChangeNotificationToken=_contentSizeCategoryDidChangeNotificationToken;
@property(retain, nonatomic) id measurementSystemChangedNotificationToken; // @synthesize measurementSystemChangedNotificationToken=_measurementSystemChangedNotificationToken;
@property(retain, nonatomic) id devicesLoadedNotificationToken; // @synthesize devicesLoadedNotificationToken=_devicesLoadedNotificationToken;
@property(retain, nonatomic) id notificationToken; // @synthesize notificationToken=_notificationToken;
@property(retain, nonatomic) id kvoToken; // @synthesize kvoToken=_kvoToken;
@property(retain, nonatomic) NSDictionary *model; // @synthesize model=_model;
@property(retain, nonatomic) FMIPAccount *account; // @synthesize account=_account;
@property(nonatomic) __weak UITableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) _Bool showAllDevicesSection; // @synthesize showAllDevicesSection=_showAllDevicesSection;
@property(retain, nonatomic) NSArray *orderedKeys; // @synthesize orderedKeys=_orderedKeys;
- (void).cxx_destruct;
- (void)tableView:(id)arg1 prefetchRowsAtIndexPaths:(id)arg2;
- (id)populateCacheWithStringDict:(id)arg1 width:(double)arg2 rtl:(_Bool)arg3 forDeviceId:(id)arg4;
- (id)attributedStringWithStringDictionary:(id)arg1;
- (double)axImageSizeForTableView:(id)arg1 cell:(id)arg2;
- (void)tableView:(id)arg1 updateAXImageForRowAtIndexPath:(id)arg2 cell:(id)arg3;
- (id)stringDictionaryForDevice:(id)arg1;
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (_Bool)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 estimatedHeightForRowAtIndexPath:(id)arg2;
- (double)fallbackEstimatedHeightForContentSizeCategory:(id)arg1;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
@property(readonly, nonatomic) _Bool showSectionHeaders;
@property(readonly, nonatomic) _Bool hasMyDevicesSection;
- (id)deviceForIndexPath:(id)arg1;
- (_Bool)_matchDevice:(id)arg1 deviceClass:(id)arg2 model:(id)arg3 color:(id)arg4;
- (void)_updateShowAllDeviceSectionWithTraitCollection:(id)arg1;
- (void)animateTableViewUpdate:(id)arg1 toNewList:(id)arg2;
- (id)indexPathForDevice:(id)arg1 usingKeys:(id)arg2 inModel:(id)arg3;
- (id)indexPathForDevice:(id)arg1;
- (id)keyForSection:(long long)arg1;
- (id)orderedAndFilteredKeyListFromModel:(id)arg1;
- (id)orderedKeysFromList:(id)arg1;
- (id)sortFamilyArray:(id)arg1;
- (id)groupedDictionaryFromRawList:(id)arg1;
- (void)initializeModel;
- (void)dealloc;
- (void)flushCache;
- (void)invalidate;
- (void)updateVisibleCellsOfTableView:(id)arg1 withBlock:(CDUnknownBlockType)arg2;
- (id)initWithTableView:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

