//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DeviceObservingViewController.h"

@class AKAppleIDAuthenticationInAppContext, CAAnimation, FMIPButton, FMIPCommandContext, HorizontalRule, NSLayoutConstraint, UIActivityIndicatorView, UIButton, UIColor, UILabel, UIScrollView, UIStackView, UITapGestureRecognizer, UIView;

@interface DeviceDetailViewController : DeviceObservingViewController
{
    _Bool _pendingActionHidden;
    _Bool _notifyMeHidden;
    _Bool _leftChannelMuted;
    _Bool _rightChannelMuted;
    _Bool _isDeviceChanging;
    UILabel *_deviceNameLabel;
    HorizontalRule *_bottomSpacer;
    UILabel *_primaryDeviceStatusLabel;
    UILabel *_secondaryDeviceStatusLabel;
    UIView *_buttonContainerView;
    UIStackView *_buttonStackView;
    UIView *_deviceDetailsContainerView;
    UIButton *_carButton;
    NSLayoutConstraint *_carButtonPositionConstraint;
    FMIPButton *_playSoundButton;
    FMIPButton *_lostModeButton;
    FMIPButton *_eraseDeviceButton;
    UIView *_pendingActionsContainerView;
    UILabel *_pendingActionsTitleLabel;
    UILabel *_pendingActionsSeparatorLabel;
    UILabel *_pendingActionsSubtitleLabel;
    UIView *_notifyMeContainerView;
    UIButton *_notifyMeButton;
    UIActivityIndicatorView *_playSoundIndicatorView;
    FMIPButton *_singleActionButton;
    UIButton *_debugButtonPendingAction;
    UIButton *_debugButtonNotifyme;
    CAAnimation *_primarySubtitleAnimation;
    CAAnimation *_secondarySubtitleAnimation;
    double _animationPeriod;
    FMIPCommandContext *_authCommandContext;
    AKAppleIDAuthenticationInAppContext *_authContext;
    UITapGestureRecognizer *_notificationsSettingsGesture;
    UIScrollView *_scrollView;
    UIStackView *_contentStackView;
    NSLayoutConstraint *_paneHeightConstraint;
    UIView *_accessoryButtonContainerView;
    FMIPButton *_accessoryPlaySoundButton;
    FMIPButton *_accessoryMuteLeftButton;
    FMIPButton *_accessoryMuteRightButton;
}

@property(nonatomic) _Bool isDeviceChanging; // @synthesize isDeviceChanging=_isDeviceChanging;
@property(nonatomic) _Bool rightChannelMuted; // @synthesize rightChannelMuted=_rightChannelMuted;
@property(nonatomic) _Bool leftChannelMuted; // @synthesize leftChannelMuted=_leftChannelMuted;
@property(retain, nonatomic) FMIPButton *accessoryMuteRightButton; // @synthesize accessoryMuteRightButton=_accessoryMuteRightButton;
@property(retain, nonatomic) FMIPButton *accessoryMuteLeftButton; // @synthesize accessoryMuteLeftButton=_accessoryMuteLeftButton;
@property(retain, nonatomic) FMIPButton *accessoryPlaySoundButton; // @synthesize accessoryPlaySoundButton=_accessoryPlaySoundButton;
@property(retain, nonatomic) UIView *accessoryButtonContainerView; // @synthesize accessoryButtonContainerView=_accessoryButtonContainerView;
@property(retain, nonatomic) NSLayoutConstraint *paneHeightConstraint; // @synthesize paneHeightConstraint=_paneHeightConstraint;
@property(retain, nonatomic) UIStackView *contentStackView; // @synthesize contentStackView=_contentStackView;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(retain, nonatomic) UITapGestureRecognizer *notificationsSettingsGesture; // @synthesize notificationsSettingsGesture=_notificationsSettingsGesture;
@property(retain, nonatomic) AKAppleIDAuthenticationInAppContext *authContext; // @synthesize authContext=_authContext;
@property(retain, nonatomic) FMIPCommandContext *authCommandContext; // @synthesize authCommandContext=_authCommandContext;
@property(nonatomic) double animationPeriod; // @synthesize animationPeriod=_animationPeriod;
@property(retain, nonatomic) CAAnimation *secondarySubtitleAnimation; // @synthesize secondarySubtitleAnimation=_secondarySubtitleAnimation;
@property(retain, nonatomic) CAAnimation *primarySubtitleAnimation; // @synthesize primarySubtitleAnimation=_primarySubtitleAnimation;
@property(retain, nonatomic) UIButton *debugButtonNotifyme; // @synthesize debugButtonNotifyme=_debugButtonNotifyme;
@property(retain, nonatomic) UIButton *debugButtonPendingAction; // @synthesize debugButtonPendingAction=_debugButtonPendingAction;
@property(retain, nonatomic) FMIPButton *singleActionButton; // @synthesize singleActionButton=_singleActionButton;
@property(nonatomic) _Bool notifyMeHidden; // @synthesize notifyMeHidden=_notifyMeHidden;
@property(nonatomic) _Bool pendingActionHidden; // @synthesize pendingActionHidden=_pendingActionHidden;
@property(retain, nonatomic) UIActivityIndicatorView *playSoundIndicatorView; // @synthesize playSoundIndicatorView=_playSoundIndicatorView;
@property(retain, nonatomic) UIButton *notifyMeButton; // @synthesize notifyMeButton=_notifyMeButton;
@property(retain, nonatomic) UIView *notifyMeContainerView; // @synthesize notifyMeContainerView=_notifyMeContainerView;
@property(retain, nonatomic) UILabel *pendingActionsSubtitleLabel; // @synthesize pendingActionsSubtitleLabel=_pendingActionsSubtitleLabel;
@property(retain, nonatomic) UILabel *pendingActionsSeparatorLabel; // @synthesize pendingActionsSeparatorLabel=_pendingActionsSeparatorLabel;
@property(retain, nonatomic) UILabel *pendingActionsTitleLabel; // @synthesize pendingActionsTitleLabel=_pendingActionsTitleLabel;
@property(retain, nonatomic) UIView *pendingActionsContainerView; // @synthesize pendingActionsContainerView=_pendingActionsContainerView;
@property(retain, nonatomic) FMIPButton *eraseDeviceButton; // @synthesize eraseDeviceButton=_eraseDeviceButton;
@property(retain, nonatomic) FMIPButton *lostModeButton; // @synthesize lostModeButton=_lostModeButton;
@property(retain, nonatomic) FMIPButton *playSoundButton; // @synthesize playSoundButton=_playSoundButton;
@property(retain, nonatomic) NSLayoutConstraint *carButtonPositionConstraint; // @synthesize carButtonPositionConstraint=_carButtonPositionConstraint;
@property(retain, nonatomic) UIButton *carButton; // @synthesize carButton=_carButton;
@property(retain, nonatomic) UIView *deviceDetailsContainerView; // @synthesize deviceDetailsContainerView=_deviceDetailsContainerView;
@property(retain, nonatomic) UIStackView *buttonStackView; // @synthesize buttonStackView=_buttonStackView;
@property(retain, nonatomic) UIView *buttonContainerView; // @synthesize buttonContainerView=_buttonContainerView;
@property(retain, nonatomic) UILabel *secondaryDeviceStatusLabel; // @synthesize secondaryDeviceStatusLabel=_secondaryDeviceStatusLabel;
@property(retain, nonatomic) UILabel *primaryDeviceStatusLabel; // @synthesize primaryDeviceStatusLabel=_primaryDeviceStatusLabel;
@property(retain, nonatomic) HorizontalRule *bottomSpacer; // @synthesize bottomSpacer=_bottomSpacer;
@property(retain, nonatomic) UILabel *deviceNameLabel; // @synthesize deviceNameLabel=_deviceNameLabel;
- (void).cxx_destruct;
- (void)goToNotificationsSettings;
- (void)cancelErase:(id)arg1;
- (void)_cancelEraseWithPassword:(id)arg1 commandContext:(id)arg2;
- (void)_completeCancelErase;
- (void)removeFromAccount:(id)arg1;
- (void)performDeviceAction:(id)arg1;
- (void)playSound:(id)arg1;
- (void)toggleNotifyMe:(id)arg1;
- (void)getDirections:(id)arg1;
- (void)allDevices:(id)arg1;
- (void)modalFlowDone:(id)arg1;
- (void)modalFlowCancel:(id)arg1;
- (void)stopAnimation;
- (void)startAnimation;
- (id)pulseAlphaAnimationWithTimeOffset:(double)arg1;
@property(readonly, nonatomic) UIColor *redSubtitleColor;
@property(readonly, nonatomic) UIColor *blackSubtitleColor;
- (void)hidePendingActionViews;
- (void)showPendingActionViews;
- (void)updatePendingOrSuggestionForDevice:(id)arg1;
- (void)hideNotifymeViews;
- (void)showNotifyMeViews;
- (void)prepareForSegue:(id)arg1 sender:(id)arg2;
- (void)sendUpdatedPlaySoundCommand;
- (void)muteRight:(id)arg1;
- (void)muteLeft:(id)arg1;
- (void)accessoryPlaySound:(id)arg1;
- (void)configureAccessoryButtonsForDevice:(id)arg1;
- (void)configureButtons;
- (void)updateDeviceStatusLabel;
- (void)configureSingleActionButtonWithTitle:(id)arg1 andAction:(SEL)arg2;
- (id)wrappedActivityIndicatorViewOfSize:(struct CGSize)arg1;
- (id)_animatedRadarImage;
- (id)_animatedSoundImageFlipped:(_Bool)arg1;
- (id)rotationAnimation;
- (id)pulseAlphaAnimationWithBeginTime:(double)arg1;
- (void)updateNotifyMeForDevice:(id)arg1;
- (void)selectedDeviceChanged:(id)arg1;
- (id)addObserversForDevice:(id)arg1;
- (void)recalculateHeightConstraint;
- (void)traitCollectionDidChange:(id)arg1;
- (void)viewWillLayoutSubviews;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)configureForDebugging;
- (void)viewDidLoad;
- (void)debugToggleNotifyme:(id)arg1;
- (void)debugTogglePendingAction:(id)arg1;

@end

