//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DeviceObservingViewController.h"

#import "UITableViewDelegate.h"

@class DeviceListDataSource, NSDictionary, NSIndexPath, NSLayoutConstraint, NSString, UITableView, UITableViewCell;

@interface DeviceListViewController : DeviceObservingViewController <UITableViewDelegate>
{
    _Bool _isDismissingMasterPane;
    _Bool _isSelectingRow;
    NSDictionary *_familyMemberDetails;
    id <DeviceListDelegate> _deviceListDelegate;
    UITableView *_tableView;
    NSLayoutConstraint *_tableViewHeightConstraint;
    DeviceListDataSource *_dataSource;
    NSIndexPath *_selectionIndexPath;
    UITableViewCell *_orbSourceCell;
    NSIndexPath *_menuIndexPath;
}

@property(retain, nonatomic) NSIndexPath *menuIndexPath; // @synthesize menuIndexPath=_menuIndexPath;
@property(nonatomic) __weak UITableViewCell *orbSourceCell; // @synthesize orbSourceCell=_orbSourceCell;
@property(retain, nonatomic) NSIndexPath *selectionIndexPath; // @synthesize selectionIndexPath=_selectionIndexPath;
@property(nonatomic) _Bool isSelectingRow; // @synthesize isSelectingRow=_isSelectingRow;
@property(nonatomic) _Bool isDismissingMasterPane; // @synthesize isDismissingMasterPane=_isDismissingMasterPane;
@property(retain, nonatomic) DeviceListDataSource *dataSource; // @synthesize dataSource=_dataSource;
@property(retain, nonatomic) NSLayoutConstraint *tableViewHeightConstraint; // @synthesize tableViewHeightConstraint=_tableViewHeightConstraint;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) __weak id <DeviceListDelegate> deviceListDelegate; // @synthesize deviceListDelegate=_deviceListDelegate;
- (void).cxx_destruct;
- (void)_previewingContext:(id)arg1 willDismissViewController:(id)arg2;
- (void)_previewingContext:(id)arg1 willPresentViewController:(id)arg2;
- (void)previewingContext:(id)arg1 commitViewController:(id)arg2;
- (id)previewingContext:(id)arg1 viewControllerForLocation:(struct CGPoint)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 estimatedHeightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 estimatedHeightForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didEndEditingRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willBeginEditingRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 titleForDeleteConfirmationButtonForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)refresh:(id)arg1;
- (void)allDevices:(id)arg1;
- (void)selectDevice:(id)arg1;
- (void)selectedDeviceChanged:(id)arg1;
- (_Bool)shouldUpdateNavigationBar;
- (void)updateAllDevicesImage;
@property(readonly, nonatomic) NSDictionary *familyMemberDetails; // @synthesize familyMemberDetails=_familyMemberDetails;
- (void)reloadTableView;
- (void)viewWillLayoutSubviews;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)willTransitionToTraitCollection:(id)arg1 withTransitionCoordinator:(id)arg2;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

