//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSObject<OS_dispatch_queue>, UIImage;

@interface ImageCacheEnvelope : NSObject
{
    _Bool _invalid;
    UIImage *_image;
    NSObject<OS_dispatch_queue> *_serialQueue;
}

@property(readonly) NSObject<OS_dispatch_queue> *serialQueue; // @synthesize serialQueue=_serialQueue;
@property _Bool invalid; // @synthesize invalid=_invalid;
@property(retain) UIImage *image; // @synthesize image=_image;
- (void).cxx_destruct;
- (void)updateImage:(id)arg1;
- (void)markInvalid;
- (id)initWithImage:(id)arg1;

@end

