//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSArray, PSPasscodeField;

@interface PasscodeField : UIView
{
    PSPasscodeField *_psPasscodeField;
}

@property(retain, nonatomic) PSPasscodeField *psPasscodeField; // @synthesize psPasscodeField=_psPasscodeField;
- (void).cxx_destruct;
@property(nonatomic) unsigned long long numberOfEntryFields;
@property(nonatomic) __weak id <PSPasscodeFieldDelegate> delegate;
@property(retain, nonatomic) NSArray *fieldSpacing;
- (_Bool)becomeFirstResponder;
- (_Bool)canResignFirstResponder;
- (_Bool)canBecomeFirstResponder;
- (struct CGSize)intrinsicContentSize;
- (void)commonSetup;
- (void)awakeFromNib;
- (void)prepareForInterfaceBuilder;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

