//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FMIPCommandViewController.h"

#import "UITextFieldDelegate.h"

@class NSString, PasscodeEntryView, UILabel, UIScrollView, UITextField, UIView;

@interface PasscodeViewController : FMIPCommandViewController <UITextFieldDelegate>
{
    UITextField *_hiddenPasscodeField;
    UILabel *_passcodeEntryDescriptionLabel;
    UIView *_entryPlaceholder;
    NSString *_firstPasscode;
    NSString *_secondPasscode;
    PasscodeEntryView *_firstEntryView;
    PasscodeEntryView *_secondEntryView;
    PasscodeEntryView *_currentEntryView;
    long long _passcodeLength;
    UIScrollView *_scrollView;
}

@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(nonatomic) long long passcodeLength; // @synthesize passcodeLength=_passcodeLength;
@property(nonatomic) __weak PasscodeEntryView *currentEntryView; // @synthesize currentEntryView=_currentEntryView;
@property(retain, nonatomic) PasscodeEntryView *secondEntryView; // @synthesize secondEntryView=_secondEntryView;
@property(retain, nonatomic) PasscodeEntryView *firstEntryView; // @synthesize firstEntryView=_firstEntryView;
@property(retain, nonatomic) NSString *secondPasscode; // @synthesize secondPasscode=_secondPasscode;
@property(retain, nonatomic) NSString *firstPasscode; // @synthesize firstPasscode=_firstPasscode;
@property(retain, nonatomic) UIView *entryPlaceholder; // @synthesize entryPlaceholder=_entryPlaceholder;
@property(retain, nonatomic) UILabel *passcodeEntryDescriptionLabel; // @synthesize passcodeEntryDescriptionLabel=_passcodeEntryDescriptionLabel;
@property(retain, nonatomic) UITextField *hiddenPasscodeField; // @synthesize hiddenPasscodeField=_hiddenPasscodeField;
- (void).cxx_destruct;
- (void)decrementPasscode;
- (void)incrementPasscode;
- (void)resetAllFields;
- (void)proceedToNextStep;
- (void)validatePasscode;
- (void)slideBackForFirstPasscode;
- (void)slideForSecondPasscode;
- (void)textChanged:(id)arg1;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)passcodeEntryTapped;
- (void)setAccessibilityValueForPasscodeEntry;
- (id)createPasscodeEntryViewForAttempt:(long long)arg1;
- (void)recalulateEntryViewCenters;
- (void)traitCollectionDidChange:(id)arg1;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)viewWillLayoutSubviews;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)warningColor;
- (id)normalColor;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

