//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FMIPDeviceCommand.h"

@class NSArray, NSString;

@interface PlaySoundCommand : FMIPDeviceCommand
{
    _Bool _didUserConfirmSafetyWarning;
    NSString *_subject;
    NSArray *_channels;
    NSString *_userAction;
}

@property(nonatomic) NSString *userAction; // @synthesize userAction=_userAction;
@property(nonatomic) _Bool didUserConfirmSafetyWarning; // @synthesize didUserConfirmSafetyWarning=_didUserConfirmSafetyWarning;
@property(copy, nonatomic) NSArray *channels; // @synthesize channels=_channels;
@property(copy, nonatomic) NSString *subject; // @synthesize subject=_subject;
- (void).cxx_destruct;
- (_Bool)ignoreCancellationErrors;
- (id)jsonBodyDictionary;
- (id)path;
- (id)initWithDevice:(id)arg1;

@end

