//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIBarButtonItem.h"

@class RefreshWrapperButton, TintedActivityIndicatorView, UIImageView;

@interface RefreshBarButtonItem : UIBarButtonItem
{
    RefreshWrapperButton *_wrapperButton;
    TintedActivityIndicatorView *_aiv;
    UIImageView *_imageView;
}

@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
@property(retain, nonatomic) TintedActivityIndicatorView *aiv; // @synthesize aiv=_aiv;
@property(retain, nonatomic) RefreshWrapperButton *wrapperButton; // @synthesize wrapperButton=_wrapperButton;
- (void).cxx_destruct;
- (id)accessibilityHint;
- (id)accessibilityLabel;
@property(readonly, nonatomic, getter=isAnimating) _Bool animating;
- (void)stopAnimating;
- (void)startAnimating;
- (void)setImageInsets:(struct UIEdgeInsets)arg1;
- (id)initWithTarget:(id)arg1 action:(SEL)arg2;
- (id)initWithCoder:(id)arg1;
- (id)init;

@end

