//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UISplitViewController.h"

#import "UISplitViewControllerDelegate.h"

@class FMIPNavigationController, UINavigationController;

@interface SplitViewController : UISplitViewController <UISplitViewControllerDelegate>
{
    UINavigationController *_delegateMasterVC;
    FMIPNavigationController *_delegateDetailVC;
}

@property(retain, nonatomic) FMIPNavigationController *delegateDetailVC; // @synthesize delegateDetailVC=_delegateDetailVC;
@property(retain, nonatomic) UINavigationController *delegateMasterVC; // @synthesize delegateMasterVC=_delegateMasterVC;
- (void).cxx_destruct;
- (void)splitViewController:(id)arg1 willChangeToDisplayMode:(long long)arg2;
- (id)splitViewController:(id)arg1 separateSecondaryViewControllerFromPrimaryViewController:(id)arg2;
- (_Bool)splitViewController:(id)arg1 collapseSecondaryViewController:(id)arg2 ontoPrimaryViewController:(id)arg3;
- (long long)targetDisplayModeForActionInSplitViewController:(id)arg1;
- (id)primaryViewControllerForExpandingSplitViewController:(id)arg1;
- (id)primaryViewControllerForCollapsingSplitViewController:(id)arg1;
- (void)traitCollectionDidChange:(id)arg1;
- (void)showPrimaryPaneWithCompletion:(CDUnknownBlockType)arg1;
- (void)hidePrimaryPane;
- (void)viewDidLoad;

@end

