//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FMIPDeviceCommand.h"

@class NSString;

@interface ValidatePasswordCommand : FMIPDeviceCommand
{
    NSString *_auth;
    long long _validatePasswordContext;
}

@property(nonatomic) long long validatePasswordContext; // @synthesize validatePasswordContext=_validatePasswordContext;
@property(copy, nonatomic) NSString *auth; // @synthesize auth=_auth;
- (void).cxx_destruct;
- (id)jsonBodyDictionary;
- (id)path;

@end

