//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, PKPeerPaymentController;

@interface PKInAppDismissedAcceptPaymentObserver : NSObject
{
    PKPeerPaymentController *_peerPaymentController;
    NSString *_paymentIdentifier;
    CDUnknownBlockType _completion;
}

+ (id)observerWithPeerPaymentController:(id)arg1 paymentIdentifier:(id)arg2 completion:(CDUnknownBlockType)arg3;
@property(readonly, copy, nonatomic) CDUnknownBlockType completion; // @synthesize completion=_completion;
@property(readonly, nonatomic) NSString *paymentIdentifier; // @synthesize paymentIdentifier=_paymentIdentifier;
@property(readonly, nonatomic) PKPeerPaymentController *peerPaymentController; // @synthesize peerPaymentController=_peerPaymentController;
- (void).cxx_destruct;
- (void)dealloc;
- (void)startObserving;

@end

