//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PKPeerPaymentMessagesContentBaseViewController.h"

@class PKCurrencyAmount, PKPeerPaymentMessagesContentAmountEntryView;

@interface PKPeerPaymentMessagesContentAmountEntryViewController : PKPeerPaymentMessagesContentBaseViewController
{
    PKCurrencyAmount *_amount;
    PKPeerPaymentMessagesContentAmountEntryView *_mainView;
}

@property(readonly, nonatomic) PKPeerPaymentMessagesContentAmountEntryView *mainView; // @synthesize mainView=_mainView;
@property(copy, nonatomic) PKCurrencyAmount *amount; // @synthesize amount=_amount;
- (void).cxx_destruct;
- (void)viewWillLayoutSubviews;
- (_Bool)_canShowKeypad;
- (void)_noteAmountChanged;
- (void)reloadContent;
- (void)viewDidLoad;
- (id)initWithMessagesAppController:(id)arg1;

@end

