//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class PKPeerPaymentNumberPadActionButton;

@interface PKPeerPaymentMessagesNumberPadView : UIView
{
    UIView *_buttonContainerView;
    PKPeerPaymentNumberPadActionButton *_buttons[4][3];
    _Bool _enabled;
    CDUnknownBlockType _actionHandler;
}

+ (struct CGSize)referenceSize;
@property(nonatomic, getter=isEnabled) _Bool enabled; // @synthesize enabled=_enabled;
@property(copy, nonatomic) CDUnknownBlockType actionHandler; // @synthesize actionHandler=_actionHandler;
- (void).cxx_destruct;
- (void)_handleActionButton:(id)arg1;
- (id)_buttonForAction:(unsigned long long)arg1;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)init;

@end

