//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PSListController.h"

@class NSArray, NSNumber, NSString, NSTimer, PSEditableTableCell, UITextField;

@interface CBAlternateNetworkViewController : PSListController
{
    _Bool _otherNetworkViewActive;
    _Bool _joining;
    NSArray *_hiddenNetworkWithNoPasswordGroup;
    NSArray *_hiddenNetworkWithPasswordGroup;
    NSArray *_currentSecurityGroup;
    NSString *_networkName;
    NSNumber *_networkSecurityType;
    NSString *_networkPassword;
    UITextField *_currentlyActiveTextField;
    PSEditableTableCell *_networkNameCell;
    PSEditableTableCell *_passwordCell;
    long long _indexToSelect;
    unsigned long long _retryJoinAttemptCount;
    NSTimer *_joinTimer;
}

@property(retain, nonatomic) NSTimer *joinTimer; // @synthesize joinTimer=_joinTimer;
@property(nonatomic) unsigned long long retryJoinAttemptCount; // @synthesize retryJoinAttemptCount=_retryJoinAttemptCount;
@property(nonatomic) _Bool joining; // @synthesize joining=_joining;
@property(nonatomic) long long indexToSelect; // @synthesize indexToSelect=_indexToSelect;
@property(retain, nonatomic) PSEditableTableCell *passwordCell; // @synthesize passwordCell=_passwordCell;
@property(retain, nonatomic) PSEditableTableCell *networkNameCell; // @synthesize networkNameCell=_networkNameCell;
@property(retain, nonatomic) UITextField *currentlyActiveTextField; // @synthesize currentlyActiveTextField=_currentlyActiveTextField;
@property(retain, nonatomic) NSString *networkPassword; // @synthesize networkPassword=_networkPassword;
@property(retain, nonatomic) NSNumber *networkSecurityType; // @synthesize networkSecurityType=_networkSecurityType;
@property(retain, nonatomic) NSString *networkName; // @synthesize networkName=_networkName;
@property(retain, nonatomic) NSArray *currentSecurityGroup; // @synthesize currentSecurityGroup=_currentSecurityGroup;
@property(retain, nonatomic) NSArray *hiddenNetworkWithPasswordGroup; // @synthesize hiddenNetworkWithPasswordGroup=_hiddenNetworkWithPasswordGroup;
@property(retain, nonatomic) NSArray *hiddenNetworkWithNoPasswordGroup; // @synthesize hiddenNetworkWithNoPasswordGroup=_hiddenNetworkWithNoPasswordGroup;
@property(nonatomic) _Bool otherNetworkViewActive; // @synthesize otherNetworkViewActive=_otherNetworkViewActive;
- (void).cxx_destruct;
- (_Bool)_passwordIsValid;
- (_Bool)_networkNameIsValid;
- (_Bool)_canAttemptJoin;
- (void)_checkoutAndPostAssociationCompletedNotificationWithError:(int)arg1;
- (void)_presentFailedAssociationAlertWithTitle:(id)arg1 message:(id)arg2;
- (void)_updateReturnKey;
- (void)_enableUI:(_Bool)arg1;
- (void)_setReturnKeyEnabled:(_Bool)arg1;
- (void)_enableRightBarButtonItem:(_Bool)arg1;
- (void)_enableLeftBarButtonItem:(_Bool)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)password;
- (void)setPassword:(id)arg1;
- (id)securityType;
- (void)setSecurityType:(id)arg1;
- (id)name;
- (void)setName:(id)arg1;
- (id)_passwordSpecifier;
- (id)_securitySpecifier;
- (id)_groupSeparatorSpecifier;
- (id)_networkNameSpecifier;
- (id)specifiers;
- (void)returnPressedAtEnd;
- (void)textFieldDidChange:(id)arg1;
- (void)_joinTapped;
- (void)joinTapped:(id)arg1;
- (void)cancelTapped:(id)arg1;
- (void)_networkJoinRetryTimerFired:(id)arg1;
- (void)_handleAssociationEvent:(id)arg1;
- (void)_returnKeyTapped:(id)arg1;
- (void)_keyboardWillPresent:(id)arg1;
- (void)_cleanUp;
- (void)dealloc;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)_deregisterNotifications;
- (void)_registerForNotifications;
- (void)viewWillAppear:(_Bool)arg1;
- (void)_setupNavBar;
- (void)viewDidLoad;
- (id)initWithNetworkInfo:(id)arg1;

@end

