//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FBSystemApp.h"

@class CBIdleSleepManager, NSTimer, _UIFeedbackEventBehavior;

@interface CBApplication : FBSystemApp
{
    _Bool _allowWiFiSettingsAction;
    _Bool _lockButtonLongPressed;
    _Bool _homeButtonPressedWithDisplayDim;
    _Bool _lockButtonPressedWithDisplayDim;
    NSTimer *_lockButtonTimer;
    CBIdleSleepManager *_idleSleepManager;
    _UIFeedbackEventBehavior *_feedbackEventBehavior;
}

+ (_Bool)runStatusBarServer;
+ (_Bool)registerAsSystemApp;
+ (_Bool)shouldCheckInWithBackboard;
@property(retain, nonatomic) _UIFeedbackEventBehavior *feedbackEventBehavior; // @synthesize feedbackEventBehavior=_feedbackEventBehavior;
@property(retain, nonatomic) CBIdleSleepManager *idleSleepManager; // @synthesize idleSleepManager=_idleSleepManager;
@property(nonatomic) _Bool lockButtonPressedWithDisplayDim; // @synthesize lockButtonPressedWithDisplayDim=_lockButtonPressedWithDisplayDim;
@property(retain, nonatomic) NSTimer *lockButtonTimer; // @synthesize lockButtonTimer=_lockButtonTimer;
@property(nonatomic) _Bool homeButtonPressedWithDisplayDim; // @synthesize homeButtonPressedWithDisplayDim=_homeButtonPressedWithDisplayDim;
@property(nonatomic) _Bool lockButtonLongPressed; // @synthesize lockButtonLongPressed=_lockButtonLongPressed;
@property(nonatomic) _Bool allowWiFiSettingsAction; // @synthesize allowWiFiSettingsAction=_allowWiFiSettingsAction;
- (void).cxx_destruct;
- (_Bool)_isSpringBoard;
- (_Bool)_hasHomeButton;
- (void)_handleThermalWarningScreenPresentation;
- (void)_lockButtonUp;
- (void)_cancelLockButtonTimer;
- (_Bool)_isLockButtonTimerValid;
- (void)_showPowerDownView;
- (void)_lockButtonLongPress;
- (void)_startLockButtonTimer;
- (void)_lockButtonDown;
- (void)_ringerSwitchUp;
- (void)_ringerSwitchDown;
- (void)_homeButtonUp;
- (void)_homeButtonDown;
- (_Bool)__handleHIDEvent:(struct __IOHIDEvent *)arg1;
- (_Bool)_handlePhysicalButtonEvent:(id)arg1;
- (void)_handleHIDEvent:(struct __IOHIDEvent *)arg1;
- (void)_hideWiFiSettingsAction;
- (void)_showWiFiSettingsAction;
- (void)_registerForNotifications;
- (id)init;

@end

