//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface CBInternalSettings : NSObject
{
}

+ (id)preferencesValueforKey:(struct __CFString *)arg1 domain:(struct __CFString *)arg2;
+ (void)setPreferencesValue:(id)arg1 key:(struct __CFString *)arg2 domain:(struct __CFString *)arg3;
+ (_Bool)isInternalBuild;

@end

