//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface CBUserSettings : NSObject
{
    _Bool _checkedInWiFiSettings;
    _Bool _wifiPowerStateOn;
}

+ (id)sharedInstance;
@property(nonatomic) _Bool wifiPowerStateOn; // @synthesize wifiPowerStateOn=_wifiPowerStateOn;
@property(nonatomic) _Bool checkedInWiFiSettings; // @synthesize checkedInWiFiSettings=_checkedInWiFiSettings;
- (void)checkInWiFiSettings:(_Bool)arg1;
- (id)init;

@end

