//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class NSArray, UIImageView;

@interface CBWiFiTableViewCell : UITableViewCell
{
    double _networkScaledRSSIStrength;
    UIImageView *_lockView;
    UIImageView *_rssiBarsView;
    NSArray *_rssiBarImages;
}

@property(retain, nonatomic) NSArray *rssiBarImages; // @synthesize rssiBarImages=_rssiBarImages;
@property(retain, nonatomic) UIImageView *rssiBarsView; // @synthesize rssiBarsView=_rssiBarsView;
@property(retain, nonatomic) UIImageView *lockView; // @synthesize lockView=_lockView;
@property(nonatomic) double networkScaledRSSIStrength; // @synthesize networkScaledRSSIStrength=_networkScaledRSSIStrength;
- (void).cxx_destruct;
- (void)hideRSSIStrength:(_Bool)arg1;
- (void)showPasswordLock:(_Bool)arg1;
- (void)dealloc;
- (void)layoutSubviews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

