//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSMutableDictionary, NSString, NSTimer;

@interface CBWiFiManager : NSObject
{
    _Bool _wifiPoweredOn;
    _Bool _scanning;
    _Bool _postedDidAssociateToEncryptedNetworkNotification;
    int _signalStrengthBars;
    int _signalStrengthRSSI;
    int _rssiThreshold;
    struct NSMutableArray *_filteredWiFiScanResults;
    struct NSMutableArray *_previousScanFilteredWiFiScanResults;
    struct NSMutableDictionary *_filteredNetworksDictionary;
    struct NSMutableDictionary *_previousScanFilteredNetworksDictionary;
    NSString *_currentNetworkSSID;
    struct __WiFiManagerClient *_manager;
    struct __WiFiDeviceClient *_device;
    NSTimer *_scanTimer;
}

+ (id)sharedInstance;
+ (id)networkScaledRSSIKey;
@property(nonatomic) _Bool postedDidAssociateToEncryptedNetworkNotification; // @synthesize postedDidAssociateToEncryptedNetworkNotification=_postedDidAssociateToEncryptedNetworkNotification;
@property(nonatomic) _Bool scanning; // @synthesize scanning=_scanning;
@property(retain, nonatomic) NSTimer *scanTimer; // @synthesize scanTimer=_scanTimer;
@property(nonatomic) int rssiThreshold; // @synthesize rssiThreshold=_rssiThreshold;
@property(nonatomic) struct __WiFiDeviceClient *device; // @synthesize device=_device;
@property(nonatomic) struct __WiFiManagerClient *manager; // @synthesize manager=_manager;
@property(nonatomic, getter=isWiFiPoweredOn) _Bool wifiPoweredOn; // @synthesize wifiPoweredOn=_wifiPoweredOn;
@property(nonatomic) int signalStrengthRSSI; // @synthesize signalStrengthRSSI=_signalStrengthRSSI;
@property(nonatomic) int signalStrengthBars; // @synthesize signalStrengthBars=_signalStrengthBars;
@property(retain, nonatomic) NSString *currentNetworkSSID; // @synthesize currentNetworkSSID=_currentNetworkSSID;
@property(retain, nonatomic) NSMutableDictionary *previousScanFilteredNetworksDictionary; // @synthesize previousScanFilteredNetworksDictionary=_previousScanFilteredNetworksDictionary;
@property(retain, nonatomic) NSMutableDictionary *filteredNetworksDictionary; // @synthesize filteredNetworksDictionary=_filteredNetworksDictionary;
@property(retain, nonatomic) NSMutableArray *previousScanFilteredWiFiScanResults; // @synthesize previousScanFilteredWiFiScanResults=_previousScanFilteredWiFiScanResults;
@property(retain, nonatomic) NSMutableArray *filteredWiFiScanResults; // @synthesize filteredWiFiScanResults=_filteredWiFiScanResults;
- (void).cxx_destruct;
- (void)_postDidAssociateToEncryptedNetworkNotificationWithError:(int)arg1;
- (void)_updateSignalStrengthFromRawRSSI:(int)arg1 andScaledRSSI:(float)arg2;
- (void)_updateSignalStrength;
- (void)_associateToHiddenUnencryptedNetwork:(struct __WiFiNetwork *)arg1;
- (void)_associateToUnencryptedNetwork:(struct __WiFiNetwork *)arg1;
- (void)_addWiFiEncryption:(int)arg1 toAssociationDict:(id)arg2;
- (int)_associateToNetwork:(struct _Apple80211 *)arg1 withSSID:(id)arg2 password:(id)arg3 encryption:(int)arg4 apMode:(int)arg5 joinBSSID:(id)arg6;
- (int)_performDirectedScan:(struct _Apple80211 *)arg1 forNetworkSSID:(id)arg2;
- (void)_performDirectedScan:(_Bool)arg1 AndAssociateToNetworkWithName:(id)arg2 password:(id)arg3 securityType:(id)arg4;
- (void)associateToHiddenEncryptedNetworkWithName:(id)arg1 password:(id)arg2 securityType:(id)arg3;
- (void)associateToEncryptedNetworkWithName:(id)arg1 password:(id)arg2 securityType:(id)arg3;
- (void)associateToHiddenUnencryptedNetworkWithName:(id)arg1;
- (void)_associateToNetworkWithInfo:(id)arg1;
- (void)associateToNetworkBySSID:(id)arg1;
- (void)associateToNetworkByIndex:(long long)arg1;
- (_Bool)attemptingToAssociateToCurrentNetworkByIndex:(long long)arg1;
- (void)_setTimeForNextScan:(double)arg1;
- (void)_wifiDirectedScanCompleted:(struct __CFArray *)arg1;
- (void)_wifiScanCompleted:(struct __CFArray *)arg1;
- (void)_restartWiFiNetworkScan;
- (void)stopWiFiNetworkScan;
- (id)_scanDictForNetworkSSID:(id)arg1;
- (void)_performDirectedScanForNetworkSSID:(id)arg1;
- (void)startWiFiNetworkScan;
- (void)_powerStateDidChange;
- (void)setPowered:(_Bool)arg1;
- (void)_forceWiFiOnIfNecessary;
- (void)_sortWiFiScanResultsAlphabetically:(struct NSMutableArray *)arg1;
- (void)_dedupNetworkToHighestRSSI:(struct __WiFiNetwork *)arg1 withInfo:(id)arg2 toLookup:(struct NSMutableDictionary *)arg3;
- (void)_addNetwork:(struct __WiFiNetwork *)arg1 toLookup:(struct NSMutableDictionary *)arg2;
- (id)_securityTypeFromNetwork:(struct __WiFiNetwork *)arg1;
- (_Bool)_shouldIncludeNetwork:(struct __WiFiNetwork *)arg1;
- (struct NSMutableDictionary *)_filteredLookupWithNetworks:(struct __CFArray *)arg1;
- (_Bool)isAssociatedToNetwork;
- (void)_updateCurrentNetwork;
- (void)_updateWiFiState;
- (void)_registerWiFiNotifications;
- (void)_deregisterWiFiNotifications;
- (void)_setWiFiDevice:(struct __WiFiDeviceClient *)arg1;
- (void)_updateWiFiDevice;
- (struct __WiFiManagerClient *)_WiFiManager;
- (void)dealloc;
- (id)init;

@end

