//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CBWindowDelegate.h"

@class CBWindow, NSArray;

@interface CBWindowManager : NSObject <CBWindowDelegate>
{
    CBWindow *_wallpaperWindow;
    NSArray *_layers;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSArray *layers; // @synthesize layers=_layers;
@property(retain, nonatomic) CBWindow *wallpaperWindow; // @synthesize wallpaperWindow=_wallpaperWindow;
- (void).cxx_destruct;
- (void)_adjustWallpaperWindowLevel;
- (double)_maxLevelForLayer:(unsigned long long)arg1;
- (void)_rekeyWindows;
- (void)window:(id)arg1 changedWallpaperTunnel:(_Bool)arg2;
- (void)windowDidDismiss:(id)arg1;
- (void)windowWillDismiss:(id)arg1;
- (void)windowDidAppear:(id)arg1;
- (void)windowWillAppear:(id)arg1;
- (id)presentViewController:(id)arg1 onLayer:(unsigned long long)arg2 wallpaperTunnel:(_Bool)arg3 statusBarVisible:(_Bool)arg4 animated:(_Bool)arg5 completion:(CDUnknownBlockType)arg6;
- (id)createRepresentationWithIdentifier:(id)arg1;
- (id)init;

@end

