//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIWindow.h"

#import "CBWindowLike.h"
#import "CBWindowLikeInternal.h"

@class NSString, UIViewController;

@interface CBWindow : UIWindow <CBWindowLikeInternal, CBWindowLike>
{
    _Bool _presentViewControllerWithStatusBarShown;
    _Bool _statusBarHidden;
    _Bool _wallpaperTunnel;
    _Bool _dismissed;
    unsigned long long _windowManagerLayer;
    id <CBWindowDelegate> _windowManager;
    double _previousStatusBarWindowLevel;
    UIViewController *_presentedView;
}

@property(retain, nonatomic) UIViewController *presentedView; // @synthesize presentedView=_presentedView;
@property(nonatomic) _Bool dismissed; // @synthesize dismissed=_dismissed;
@property(nonatomic) _Bool wallpaperTunnel; // @synthesize wallpaperTunnel=_wallpaperTunnel;
@property(nonatomic, getter=isStatusBarHidden) _Bool statusBarHidden;
@property(nonatomic) double previousStatusBarWindowLevel;
@property(nonatomic) _Bool presentViewControllerWithStatusBarShown;
@property(nonatomic) __weak id <CBWindowDelegate> windowManager; // @synthesize windowManager=_windowManager;
@property(nonatomic) unsigned long long windowManagerLayer; // @synthesize windowManagerLayer=_windowManagerLayer;
- (void).cxx_destruct;
- (void)viewControllerDidDismiss;
- (void)dismissViewControllerAnimated:(_Bool)arg1;
- (id)initWithWallpaperTunnel:(_Bool)arg1;
- (id)init;
@property(readonly, copy) NSString *description;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(nonatomic, getter=isHidden) _Bool hidden; // @dynamic hidden;
@property(readonly) Class superclass;
@property(nonatomic) double windowLevel;

@end

