//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "BFFBackupDeviceControllerDelegate.h"
#import "BFFFlowItem.h"
#import "MBManagerDelegate.h"

@class BKSProcessAssertion, BackupRestoreProgressView, MBManager, NSDate, NSString, RestorableBackupItem;

@interface BackupRestoreProgressController : UIViewController <BFFBackupDeviceControllerDelegate, MBManagerDelegate, BFFFlowItem>
{
    MBManager *_backupManager;
    BackupRestoreProgressView *_progressView;
    BKSProcessAssertion *_restoringProcessAssertion;
    struct __MKBAssertion *_restoringLockAssertion;
    UIViewController *_spinningViewController;
    RestorableBackupItem *_currentRestorable;
    double _backupPercentComplete;
    double _restorePercentComplete;
    _Bool _backupThenRestore;
    NSDate *_lastSourceDeviceBackupDate;
    int _restoreState;
    id <BFFFlowItemDelegate> _delegate;
}

+ (id)cloudConfigSkipKey;
+ (_Bool)controllerNeedsToRun;
@property(nonatomic) int restoreState; // @synthesize restoreState=_restoreState;
@property(nonatomic) __weak id <BFFFlowItemDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)managerDidLoseConnectionToService:(id)arg1;
- (void)manager:(id)arg1 didFailRestoreWithError:(id)arg2;
- (void)managerDidFinishRestore:(id)arg1;
- (void)manager:(id)arg1 didUpdateProgress:(float)arg2 estimatedTimeRemaining:(unsigned long long)arg3;
- (void)backupProgress:(double)arg1 estimatedTimeRemaining:(unsigned long long)arg2;
- (void)backupDeviceController:(id)arg1 backupCompletedWithError:(id)arg2;
- (id)waitForBackupToComplete;
- (void)restoreFailedWithError:(id)arg1;
- (void)handleBackupFailed:(id)arg1;
- (void)reattemptBackup;
- (id)latestSnapshotForSourceDevice:(id *)arg1;
- (void)updateProgressText;
- (void)updateProgress;
- (void)releaseProcessAndLockAssertion;
- (void)takeProcessAndLockAssertionCompletion:(CDUnknownBlockType)arg1;
- (_Bool)hasProcessAndLockAssertions;
- (void)startRestore:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)startRestore:(id)arg1 withProgressOnNavigationController:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)popBackFromProgress;
- (void)stopSpinningForIdentifier:(id)arg1;
- (void)startSpinningWithIdentifier:(id)arg1 overNav:(id)arg2;
- (void)loadView;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

