//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class BFFSetupAssistantGuideUserToBackup, NSDate, NSMutableArray, NSMutableDictionary, NSString;

@interface BFFAnalyticsManager : NSObject
{
    NSDate *_timingStartDate;
    long long _timingStartIdentifier;
    NSMutableDictionary *_skippedPanes;
    NSMutableDictionary *_buddyChoices;
    BFFSetupAssistantGuideUserToBackup *_guideUserMetric;
    NSMutableArray *_stagedMetrics;
    id _callstack;
    NSString *_activationADKey;
    NSString *_appleIDADKey;
}

+ (id)sharedManager;
@property(retain, nonatomic) NSString *appleIDADKey; // @synthesize appleIDADKey=_appleIDADKey;
@property(retain, nonatomic) NSString *activationADKey; // @synthesize activationADKey=_activationADKey;
- (void).cxx_destruct;
- (void)logOnBoardingPaneTimeShownForPlaceholder:(double)arg1 forVideo:(double)arg2;
- (void)logGuideUserToBackupSucceeded:(_Bool)arg1;
- (void)logGuideUserToBackupSelected:(_Bool)arg1;
- (void)logDestinationDeviceClass:(id)arg1;
- (void)logSourceDeviceClass:(id)arg1;
- (void)logMostRecentBackupAge:(long long)arg1;
- (void)logGuideUserToBackupAvailable:(_Bool)arg1;
- (void)logExpressRestoreShown:(_Bool)arg1;
- (void)commitAnalyticsForRunType:(long long)arg1;
- (void)_commitFeatureChoiceAnalyticsForRunType:(long long)arg1;
- (void)_commitSkippedPaneAnalyticsForRunType:(long long)arg1;
- (void)clearSkipChoice:(_Bool)arg1 forPane:(long long)arg2;
- (void)logSkipChoice:(_Bool)arg1 forPane:(long long)arg2;
- (void)clearBuddyChoiceForPane:(long long)arg1;
- (void)logBuddyChoice:(unsigned long long)arg1 forPane:(long long)arg2;
- (void)logKeyboardChoices:(id)arg1 againstGuessedKeyboards:(id)arg2 forLocaleidentifier:(id)arg3;
- (id)_stringForKeyboardList:(id)arg1;
- (void)logBuddyDuration:(double)arg1 lockedDuration:(double)arg2 forRunType:(long long)arg3;
- (void)logNumberOfBuddySections:(unsigned long long)arg1 forRunType:(long long)arg2;
- (void)cancelTiming;
- (void)finishTimingIfNeededWithEndIdentifier:(id)arg1;
- (void)finishTimingWithEndIdentifier:(id)arg1;
- (void)_finishTimingWithEndIdentifier:(id)arg1 hardFailure:(_Bool)arg2;
- (void)startUserPerceivedTimingWithStartIdentifier:(long long)arg1;
- (void)stageMetricID:(unsigned int)arg1 metric:(id)arg2;
- (id)init;

@end

