//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBCodable.h"

#import "NSCopying.h"

@class NSString;

@interface BFFSetupAssistantGuideUserToBackup : PBCodable <NSCopying>
{
    long long _backupAge;
    unsigned long long _timestamp;
    NSString *_destinationDeviceClass;
    NSString *_sourceDeviceClass;
    _Bool _expressRestoreShown;
    _Bool _guideUserAvailable;
    _Bool _guideUserSelected;
    _Bool _guideUserSucceeded;
    struct {
        unsigned int backupAge:1;
        unsigned int timestamp:1;
        unsigned int expressRestoreShown:1;
        unsigned int guideUserAvailable:1;
        unsigned int guideUserSelected:1;
        unsigned int guideUserSucceeded:1;
    } _has;
}

@property(nonatomic) _Bool guideUserSucceeded; // @synthesize guideUserSucceeded=_guideUserSucceeded;
@property(nonatomic) _Bool guideUserSelected; // @synthesize guideUserSelected=_guideUserSelected;
@property(retain, nonatomic) NSString *destinationDeviceClass; // @synthesize destinationDeviceClass=_destinationDeviceClass;
@property(retain, nonatomic) NSString *sourceDeviceClass; // @synthesize sourceDeviceClass=_sourceDeviceClass;
@property(nonatomic) long long backupAge; // @synthesize backupAge=_backupAge;
@property(nonatomic) _Bool guideUserAvailable; // @synthesize guideUserAvailable=_guideUserAvailable;
@property(nonatomic) _Bool expressRestoreShown; // @synthesize expressRestoreShown=_expressRestoreShown;
@property(nonatomic) unsigned long long timestamp; // @synthesize timestamp=_timestamp;
- (void).cxx_destruct;
- (void)mergeFrom:(id)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (_Bool)readFrom:(id)arg1;
- (id)dictionaryRepresentation;
- (id)description;
@property(nonatomic) _Bool hasGuideUserSucceeded;
@property(nonatomic) _Bool hasGuideUserSelected;
@property(readonly, nonatomic) _Bool hasDestinationDeviceClass;
@property(readonly, nonatomic) _Bool hasSourceDeviceClass;
@property(nonatomic) _Bool hasBackupAge;
@property(nonatomic) _Bool hasGuideUserAvailable;
@property(nonatomic) _Bool hasExpressRestoreShown;
@property(nonatomic) _Bool hasTimestamp;

@end

