//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBCodable.h"

#import "NSCopying.h"

@class NSString;

@interface BFFSetupAssistantKeyboardChoices : PBCodable <NSCopying>
{
    unsigned long long _timestamp;
    NSString *_chosenKeyboards;
    NSString *_guessedKeyboards;
    NSString *_localeIdentifier;
    _Bool _usedDefault;
    struct {
        unsigned int timestamp:1;
    } _has;
}

@property(retain, nonatomic) NSString *guessedKeyboards; // @synthesize guessedKeyboards=_guessedKeyboards;
@property(retain, nonatomic) NSString *chosenKeyboards; // @synthesize chosenKeyboards=_chosenKeyboards;
@property(nonatomic) _Bool usedDefault; // @synthesize usedDefault=_usedDefault;
@property(retain, nonatomic) NSString *localeIdentifier; // @synthesize localeIdentifier=_localeIdentifier;
@property(nonatomic) unsigned long long timestamp; // @synthesize timestamp=_timestamp;
- (void).cxx_destruct;
- (void)mergeFrom:(id)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (_Bool)readFrom:(id)arg1;
- (id)dictionaryRepresentation;
- (id)description;
@property(readonly, nonatomic) _Bool hasGuessedKeyboards;
@property(readonly, nonatomic) _Bool hasChosenKeyboards;
@property(nonatomic) _Bool hasTimestamp;

@end

