//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BuddyTableViewController.h"

#import "BFFFlowItem.h"
#import "BuddyAppleIDControllerDelegate.h"

@class AASetupAssistantConfigResponse, BuddyAppleIDController, BuddyAppleIDTableHeaderView, NSArray, NSString, UITableViewCell;

@interface BuddyAppleIDChoiceController : BuddyTableViewController <BFFFlowItem, BuddyAppleIDControllerDelegate>
{
    UITableViewCell *_forgotCell;
    UITableViewCell *_createNewCell;
    NSArray *_itemIcons;
    NSArray *_itemDescriptions;
    BuddyAppleIDTableHeaderView *_serviceHeaderView;
    BuddyAppleIDController *_appleIDController;
    _Bool _allowBack;
    _Bool _whatIsReady;
    _Bool _whatIsRequested;
    _Bool _didShowWifiAlert;
    _Bool _shouldShowWifiIfCancellingSkipAlert;
    _Bool _passbookPaymentSupported;
    _Bool _runningSpinner;
    AASetupAssistantConfigResponse *_urlConfiguration;
    id <BFFFlowItemDelegate> _delegate;
}

+ (id)cloudConfigSkipKey;
+ (void)initialize;
@property(nonatomic) __weak id <BFFFlowItemDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)appleIDController:(id)arg1 failedWithError:(id)arg2;
- (void)appleIDControllerFinished:(id)arg1;
- (long long)tableView:(id)arg1 titleAlignmentForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)_reallySkip;
- (void)_skipPressed:(id)arg1;
- (void)_showOfflineTerms;
- (void)_whatIsPressed:(id)arg1;
- (void)dealloc;
- (_Bool)controllerAllowsNavigatingBack;
- (_Bool)useScreenFooter;
- (void)viewDidLayoutSubviews;
- (void)loadView;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (_Bool)shouldAllowStartOver;
- (void)startOver;
- (void)viewDidAppear:(_Bool)arg1;
- (void)didMoveToParentViewController:(id)arg1;
- (id)titleText;
- (void)performExtendedInitializationWithCompletion:(CDUnknownBlockType)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

