//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BFFFlow.h"

#import "BuddyAppleIDControllerDelegate.h"
#import "BuddySoftwareUpdateControllerDelegate.h"
#import "BuddyTCSubControllerDelegate.h"

@class BYBackupMetadata, BackupRestoreProgressController, BuddyAppleIDAuthManager, BuddyAppleIDController, BuddySoftwareUpdateController, MBManager, NSDictionary, NSMutableArray, NSMutableDictionary, NSObject<OS_dispatch_queue>, NSString, RestorableBackupItem, SSAccount, SSTermsAndConditions, UIViewController;

@interface BuddyiCloudRestoreFlow : BFFFlow <BuddyAppleIDControllerDelegate, BuddyTCSubControllerDelegate, BuddySoftwareUpdateControllerDelegate>
{
    MBManager *_backupManager;
    BackupRestoreProgressController *_restoreProgressController;
    BuddyAppleIDController *_iTunesAppleIDController;
    BuddyAppleIDController *_softwareUpdateAppleIDController;
    UIViewController *_spinningViewController;
    NSString *_activeStoreAccount;
    NSDictionary *_storeAccountMap;
    NSMutableArray *_storeAccountsToSignIn;
    SSAccount *_currentStoreAccount;
    SSTermsAndConditions *_currentStoreTerms;
    _Bool _signInWasSilent;
    NSString *_appleIDPassword;
    NSMutableDictionary *_authManagers;
    BuddyAppleIDAuthManager *_softwareUpdateAuthManager;
    BuddySoftwareUpdateController *_softwareUpdateController;
    UIViewController *_firstFlowViewController;
    _Bool _requireInteractiveAuth;
    RestorableBackupItem *_pendingBackupItem;
    RestorableBackupItem *_attemptedBackupItem;
    BYBackupMetadata *_pendingBackupMetadata;
    NSObject<OS_dispatch_queue> *_metadataQueue;
    RestorableBackupItem *_backupItem;
}

+ (_Bool)controllerNeedsToRun;
+ (id)sharedFlow;
@property(retain) RestorableBackupItem *backupItem; // @synthesize backupItem=_backupItem;
- (void).cxx_destruct;
- (void)softwareUpdateController:(id)arg1 didFailToInstallUpdateWithError:(id)arg2;
- (void)softwareUpdateController:(id)arg1 didStartInstallForUpdate:(id)arg2;
- (void)softwareUpdateController:(id)arg1 prepareToInstallUpdate:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)_prepareForSoftwareUpdate:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)appleIDControllerFinished:(id)arg1;
- (void)backNavigationButtonTappedPostSoftwareUpdate:(id)arg1;
- (void)startPostSoftwareUpdateRestore;
- (_Bool)needsToRunPostSoftwareUpdateRestore;
- (id)_validatedRestorableMarker;
- (id)signInPageForPostRestoreAuthenticationWithNavigationController:(id)arg1;
- (void)buddyTCSubController:(id)arg1 didFinishWithAgree:(_Bool)arg2;
- (void)upgradeStoreAccountSignInPageDidSkip;
- (void)upgradeStoreAccountSignInPageDidSignInWithUsername:(id)arg1 password:(id)arg2 rawPassword:(id)arg3 altDSID:(id)arg4;
- (void)_showStoreTermsForAccount:(id)arg1;
- (void)_showNextStoreAccountTerms;
- (void)showStoreTermsIfNeeded;
- (void)stopSpinningForIdentifier:(id)arg1;
- (void)startSpinningWithIdentifier:(id)arg1;
- (void)willResignActive;
- (void)controllerWasPopped;
- (void)showStoreSignIn;
- (id)_localizedExtraStoresSignInTextForStoreContentMap:(id)arg1;
- (void)_removeOldStoreSignInAndTermsPages;
- (void)startRestore;
- (void)pushViewController:(id)arg1 animated:(_Bool)arg2;
- (void)startFlowAnimated:(_Bool)arg1;
- (id)initWithNavigationController:(id)arg1;
- (void)preScanForSoftwareUpdateCompletion:(CDUnknownBlockType)arg1;
- (id)softwareUpdateController;
- (void)getPendingBackupMetadataWithHandler:(CDUnknownBlockType)arg1;
- (void)setPendingBackupMetadata:(id)arg1;
- (id)attemptedBackupItem;
- (void)setAttemptedBackupItem:(id)arg1;
- (id)pendingBackupItem;
- (void)setPendingBackupItem:(id)arg1;
- (void)setPendingBackupItem:(id)arg1 invalidateStash:(_Bool)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

