//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSString, UIImageView, UILabel;

@interface BuddyPosedDeviceView : UIView
{
    NSString *_primaryDeviceModelIdentifier;
    NSString *_secondaryDeviceModelIdentifier;
    UIImageView *_primaryDeviceImageView;
    UIImageView *_secondaryDeviceImageView;
    UIImageView *_primaryDeviceScreenImageView;
    UIImageView *_secondaryDeviceScreenImageView;
    UILabel *_primaryDeviceHelloLabel;
    UILabel *_primaryDeviceInstructionLabel;
}

+ (id)deviceScreenImagePrefixForModelIdentifier:(id)arg1 limited:(_Bool)arg2;
+ (id)deviceImagePrefixForModelIdentifier:(id)arg1 limited:(_Bool)arg2;
+ (id)helloImageForModelIdentifier:(id)arg1;
+ (id)homeScreenImageForModelIdentifier:(id)arg1;
+ (id)deviceImageForModelIdentifier:(id)arg1;
+ (id)backgroundColor;
@property(retain) UILabel *primaryDeviceInstructionLabel; // @synthesize primaryDeviceInstructionLabel=_primaryDeviceInstructionLabel;
@property(retain) UILabel *primaryDeviceHelloLabel; // @synthesize primaryDeviceHelloLabel=_primaryDeviceHelloLabel;
@property(retain) UIImageView *secondaryDeviceScreenImageView; // @synthesize secondaryDeviceScreenImageView=_secondaryDeviceScreenImageView;
@property(retain) UIImageView *primaryDeviceScreenImageView; // @synthesize primaryDeviceScreenImageView=_primaryDeviceScreenImageView;
@property(retain) UIImageView *secondaryDeviceImageView; // @synthesize secondaryDeviceImageView=_secondaryDeviceImageView;
@property(retain) UIImageView *primaryDeviceImageView; // @synthesize primaryDeviceImageView=_primaryDeviceImageView;
@property(retain) NSString *secondaryDeviceModelIdentifier; // @synthesize secondaryDeviceModelIdentifier=_secondaryDeviceModelIdentifier;
@property(retain) NSString *primaryDeviceModelIdentifier; // @synthesize primaryDeviceModelIdentifier=_primaryDeviceModelIdentifier;
- (void).cxx_destruct;
- (long long)deviceTypeForModelIdentifier:(id)arg1;
- (long long)currentDeviceType;
- (void)addDevice:(id)arg1 screenContent:(long long)arg2;
- (void)layoutInstructionLabel:(id)arg1 forModelIdentifier:(id)arg2 relativeToScreenFrame:(struct CGRect)arg3;
- (void)layoutHelloLabel:(id)arg1 forModelIdentifier:(id)arg2 relativeToScreenFrame:(struct CGRect)arg3;
- (void)layoutScreenView:(id)arg1 forModelIdentifier:(id)arg2 relativeToDeviceFrame:(struct CGRect)arg3 scale:(double)arg4;
- (void)layoutScreenView:(id)arg1 forModelIdentifier:(id)arg2 relativeToDeviceFrame:(struct CGRect)arg3;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

