//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "RemoteUIControllerDelegate.h"

@class NSString, NSURL, RemoteUIController, UIViewController;

@interface BuddyAboutPaneLoader : NSObject <RemoteUIControllerDelegate>
{
    _Bool _firstPage;
    NSURL *_baseURL;
    UIViewController *_hostViewController;
    CDUnknownBlockType _completion;
    CDUnknownBlockType _requestMutator;
    RemoteUIController *_ruiController;
}

+ (id)loaderWithBaseURL:(id)arg1 hostViewController:(id)arg2;
@property(retain, nonatomic) RemoteUIController *ruiController; // @synthesize ruiController=_ruiController;
@property(copy, nonatomic) CDUnknownBlockType requestMutator; // @synthesize requestMutator=_requestMutator;
@property(copy, nonatomic) CDUnknownBlockType completion; // @synthesize completion=_completion;
@property(nonatomic) __weak UIViewController *hostViewController; // @synthesize hostViewController=_hostViewController;
@property(retain, nonatomic) NSURL *baseURL; // @synthesize baseURL=_baseURL;
- (void).cxx_destruct;
- (void)remoteUIController:(id)arg1 didFinishLoadWithError:(id)arg2;
- (void)remoteUIController:(id)arg1 didReceiveObjectModel:(id)arg2 actionSignal:(unsigned long long *)arg3;
- (void)remoteUIController:(id)arg1 willPresentObjectModel:(id)arg2 modally:(_Bool)arg3;
- (_Bool)remoteUIController:(id)arg1 shouldLoadRequest:(id)arg2 redirectResponse:(id)arg3;
- (void)_cleanup;
- (void)showPaneForAboutPageNamed:(id)arg1 withRequestMutator:(CDUnknownBlockType)arg2 completion:(CDUnknownBlockType)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

