//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface BuddyWifiAutoJoiner : NSObject
{
    struct __WiFiManagerClient *_wifiManagerRef;
}

+ (void)stopAutojoiningWiFiNetworks;
+ (void)beginAutojoiningWiFiNetworks;
+ (id)_sharedInstance;
- (void)stopAutojoiningWiFiNetworks;
- (void)beginAutojoiningWiFiNetworks;
- (struct __CFArray *)_copyAutoJoinableWiFiNetworks;
- (struct __WiFiNetwork *)createNetworkWithSSID:(id)arg1;
- (void)dealloc;

@end

