//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIImage, UIImageView;

@interface BuddyRoundedRectImageView : UIView
{
    UIImageView *_imageView;
    _Bool _usesMask;
}

@property(nonatomic) _Bool usesMask; // @synthesize usesMask=_usesMask;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
@property(retain, nonatomic) UIImage *image;
- (id)initWithImage:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

