//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BuddyTableViewController.h"

#import "BFFFlowItem.h"
#import "BuddyPasscodeEntryDelegate.h"
#import "PSUISoftwareUpdateManagerDelegate.h"

@class NSString, PSSoftwareUpdateTitleCell, PSUISoftwareUpdateManager, SUDescriptor, UIActivityIndicatorView, UIButton, UILabel, UITableViewCell;

@interface BuddySoftwareUpdateController : BuddyTableViewController <PSUISoftwareUpdateManagerDelegate, BuddyPasscodeEntryDelegate, BFFFlowItem>
{
    PSUISoftwareUpdateManager *_manager;
    PSSoftwareUpdateTitleCell *_titleCell;
    UITableViewCell *_learnMoreCell;
    UIActivityIndicatorView *_actionSpinner;
    UIButton *_actionButton;
    UIButton *_installTonightButton;
    UIButton *_skipButton;
    UILabel *_errorLabel;
    CDUnknownBlockType _devicePasscodeCompletion;
    unsigned long long _userChoice;
    _Bool _allowUserToSkip;
    _Bool _allowUserToInstallTonight;
    _Bool _scannedForUpdate;
    id <BFFFlowItemDelegate> _delegate;
    id <BuddySoftwareUpdateControllerDelegate> _softwareUpdateDelegate;
    SUDescriptor *_update;
}

+ (id)cloudConfigSkipKey;
@property(retain) SUDescriptor *update; // @synthesize update=_update;
@property _Bool scannedForUpdate; // @synthesize scannedForUpdate=_scannedForUpdate;
@property _Bool allowUserToInstallTonight; // @synthesize allowUserToInstallTonight=_allowUserToInstallTonight;
@property _Bool allowUserToSkip; // @synthesize allowUserToSkip=_allowUserToSkip;
@property(nonatomic) __weak id <BuddySoftwareUpdateControllerDelegate> softwareUpdateDelegate; // @synthesize softwareUpdateDelegate=_softwareUpdateDelegate;
@property(nonatomic) __weak id <BFFFlowItemDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)detailedReleaseNotesDonePressed:(id)arg1;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)manager:(id)arg1 installFailedWithError:(id)arg2;
- (void)manager:(id)arg1 installStartedForUpdate:(id)arg2;
- (void)manager:(id)arg1 downloadFinished:(id)arg2;
- (void)manager:(id)arg1 downloadProgressChanged:(id)arg2 displayStyle:(int)arg3;
- (void)manager:(id)arg1 didTransitionToState:(int)arg2 fromState:(int)arg3 error:(id)arg4;
- (void)setButtonTitle:(id)arg1;
- (void)setErrorText:(id)arg1;
- (void)manager:(id)arg1 promptForDevicePasscodeWithCompletion:(CDUnknownBlockType)arg2;
- (void)_cancelDevicePasscodePicker:(id)arg1;
- (void)passcodeEntryController:(id)arg1 didEnterPasscode:(id)arg2;
- (void)performExtendedInitializationWithCompletion:(CDUnknownBlockType)arg1;
- (void)installTonightPressed:(id)arg1;
- (void)downloadAndInstallTonightPressed:(id)arg1;
- (void)skipPressed:(id)arg1;
- (void)resumePressed:(id)arg1;
- (void)installNowPressed:(id)arg1;
- (void)_installFailedWithError:(id)arg1;
- (void)downloadAndInstallPressed:(id)arg1;
- (void)beginDownloadingUpdate;
- (void)setButtonState:(_Bool)arg1;
- (void)didBecomeActive:(id)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)scanForUpdateCompletion:(CDUnknownBlockType)arg1;
- (void)loadView;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

