//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSMutableArray, NSMutableDictionary;

@interface BuddyConstrainedView : UIView
{
    NSMutableDictionary *_views;
    NSMutableDictionary *_metrics;
    NSMutableArray *_buddyConstraints;
}

@property(retain, nonatomic) NSMutableArray *buddyConstraints; // @synthesize buddyConstraints=_buddyConstraints;
@property(retain, nonatomic) NSMutableDictionary *metrics; // @synthesize metrics=_metrics;
@property(retain, nonatomic) NSMutableDictionary *views; // @synthesize views=_views;
- (void).cxx_destruct;
- (void)adjustMarginMetricA:(id)arg1 B:(id)arg2 toFitHeight:(double)arg3 metricMinA:(id)arg4;
- (_Bool)adjustMetric:(id)arg1 untilHeightUnder:(double)arg2 step:(double)arg3 limit:(double)arg4;
- (_Bool)adjustMetric:(id)arg1 untilSentinel:(CDUnknownBlockType)arg2 step:(double)arg3 limit:(double)arg4;
- (_Bool)attemptAdjustToDescriptionLines:(int)arg1;
- (void)adjustToFit;
- (double)layoutHeight;
- (void)adjustMetric:(id)arg1 by:(double)arg2;
- (void)resetConstraints;
- (void)buddyAddSubview:(id)arg1 named:(id)arg2;
- (void)buddyAddConstraints:(id)arg1;
- (void)applyConstraints;
- (void)initMetrics;
- (void)centerLabel:(id)arg1 withMargin:(double)arg2;
- (void)center:(id)arg1;
- (void)center:(id)arg1 withMargin:(double)arg2;
- (float)metric:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

