//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "BFFFlowItem.h"
#import "BFFNavigationControllerDelegate.h"
#import "WFBuddyViewControllerDelegate.h"

@class BFFNavigationController, NSString, NSTimer, UIAlertController, WFBuddyViewController, WFNetworkListController;

@interface BuddyWiFiController : NSObject <WFBuddyViewControllerDelegate, BFFNavigationControllerDelegate, BFFFlowItem>
{
    WFBuddyViewController *_viewController;
    BFFNavigationController *_navigationController;
    WFNetworkListController *_wifiManager;
    UIAlertController *_badWifiAlert;
    NSTimer *_wifiTimeoutTimer;
    _Bool _showingWifiTimeoutSpinner;
    _Bool _wifiWillPush;
    _Bool _appleIDWifiSkipAlertShown;
    _Bool _showNetworkSettings;
    _Bool _supportsCellularActivation;
    id <BFFFlowItemDelegate> _delegate;
}

+ (id)cloudConfigSkipKey;
+ (_Bool)controllerNeedsToRun;
+ (_Bool)deviceHasWiFi;
+ (_Bool)controllerAffectedByTapFreeSetup;
@property(nonatomic) _Bool supportsCellularActivation; // @synthesize supportsCellularActivation=_supportsCellularActivation;
@property(nonatomic) _Bool showNetworkSettings; // @synthesize showNetworkSettings=_showNetworkSettings;
@property(readonly, nonatomic) _Bool appleIDWifiSkipAlertShown; // @synthesize appleIDWifiSkipAlertShown=_appleIDWifiSkipAlertShown;
@property(nonatomic) __weak id <BFFFlowItemDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)buddyViewControllerDidPressAlternateSetupButton:(id)arg1;
- (void)wifiTimeoutFired:(id)arg1;
- (void)_clearWifiTimeoutTimer;
- (void)wifiNetworkJoinStarted:(id)arg1;
- (void)wifiNetworkJoinFinished:(id)arg1;
- (void)_resetWifiControllerTimeoutSpinner;
- (void)_showNavBarSpinner;
- (void)updateNextButton;
- (void)reachabilityChanged:(_Bool)arg1;
- (void)_wifiControllerDone:(id)arg1;
- (void)_wifiControllerReallyDone;
- (void)navigationController:(id)arg1 willShowViewController:(id)arg2 operation:(long long)arg3 animated:(_Bool)arg4;
- (void)controllerWasPopped;
- (void)setNavigationController:(id)arg1;
- (id)viewController;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

