//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SetupChoiceController.h"

@class BuddyAppleIDController, SetupChoice;

@interface BuddyAppleIDFindMyPhonePage : SetupChoiceController
{
    BuddyAppleIDController *_appleIDController;
    SetupChoice *_enableChoice;
    SetupChoice *_disableChoice;
}

+ (void)setDeviceLocatorEnabled:(_Bool)arg1 viewControllerForAlertIfAccountChange:(id)arg2 completion:(CDUnknownBlockType)arg3;
+ (id)secondaryAccountWithFMiPForAccountStore:(id)arg1;
+ (id)cloudConfigSkipKey;
+ (_Bool)controllerNeedsToRun;
@property(retain, nonatomic) SetupChoice *disableChoice; // @synthesize disableChoice=_disableChoice;
@property(retain, nonatomic) SetupChoice *enableChoice; // @synthesize enableChoice=_enableChoice;
@property(nonatomic) __weak BuddyAppleIDController *appleIDController; // @synthesize appleIDController=_appleIDController;
- (void).cxx_destruct;
- (_Bool)controllerAllowsNavigatingBack;
- (void)controllerDone;
- (void)whatIsPressed;
- (void)learnMoreButtonTapped:(id)arg1;
- (id)learnMoreButtonText;
- (id)footerDetailText;
- (id)footerTitleText;
- (id)footerIconName;
- (_Bool)wantsNextButton;
- (id)titleText;
- (id)init;

@end

