//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SetupChoiceController.h"

#import "PSUIHomeButtonCustomizeControllerDelegate.h"

@class SetupChoice, UIImageView;

@interface BuddyHomeButtonController : SetupChoiceController <PSUIHomeButtonCustomizeControllerDelegate>
{
    SetupChoice *_customizeChoice;
    SetupChoice *_skipChoice;
    UIImageView *_deviceChromeImageView;
    UIImageView *_homeScreenImageView;
}

+ (id)cloudConfigSkipKey;
+ (_Bool)controllerNeedsToRun;
- (void).cxx_destruct;
- (void)homeButtonCustomizeControllerDidFinish:(id)arg1;
- (void)controllerDone;
- (void)viewDidLayoutSubviews;
- (void)viewDidAppear:(_Bool)arg1;
- (void)loadView;
- (_Bool)useTableLayout;
- (_Bool)wantsNextButton;
- (id)footerDetailText;
- (id)titleText;
- (_Bool)shouldAllowStartOver;
- (id)init;
- (void)performExtendedInitializationWithCompletion:(CDUnknownBlockType)arg1;

@end

