//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BFFFlow.h"

@class ACAccountStore;

@interface BuddyAppleIDFlow : BFFFlow
{
    ACAccountStore *_accountStore;
}

- (void).cxx_destruct;
- (void)flowItemDone:(id)arg1 nextItemClass:(Class)arg2;
- (id)firstItem;
- (id)init;

@end

