//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class NSString, UILabel, UIScrollView;

@interface BuddyCloudConfigAboutConfigurationContainerController : UIViewController
{
    _Bool _isSupervised;
    UIScrollView *_containerView;
    UILabel *_descriptionLabel;
    NSString *_organizationName;
    NSString *_organizationDepartment;
    NSString *_organizationAddress;
    NSString *_organizationAddressLine1;
    NSString *_organizationAddressLine2;
    NSString *_organizationCity;
    NSString *_organizationRegion;
    NSString *_organizationZipCode;
    NSString *_organizationCountry;
    NSString *_organizationSupportPhone;
}

+ (id)defaultParagraphTextAttributes;
@property(nonatomic) _Bool isSupervised; // @synthesize isSupervised=_isSupervised;
@property(copy, nonatomic) NSString *organizationSupportPhone; // @synthesize organizationSupportPhone=_organizationSupportPhone;
@property(copy, nonatomic) NSString *organizationCountry; // @synthesize organizationCountry=_organizationCountry;
@property(copy, nonatomic) NSString *organizationZipCode; // @synthesize organizationZipCode=_organizationZipCode;
@property(copy, nonatomic) NSString *organizationRegion; // @synthesize organizationRegion=_organizationRegion;
@property(copy, nonatomic) NSString *organizationCity; // @synthesize organizationCity=_organizationCity;
@property(copy, nonatomic) NSString *organizationAddressLine2; // @synthesize organizationAddressLine2=_organizationAddressLine2;
@property(copy, nonatomic) NSString *organizationAddressLine1; // @synthesize organizationAddressLine1=_organizationAddressLine1;
@property(copy, nonatomic) NSString *organizationAddress; // @synthesize organizationAddress=_organizationAddress;
@property(copy, nonatomic) NSString *organizationDepartment; // @synthesize organizationDepartment=_organizationDepartment;
@property(copy, nonatomic) NSString *organizationName; // @synthesize organizationName=_organizationName;
@property(retain, nonatomic) UILabel *descriptionLabel; // @synthesize descriptionLabel=_descriptionLabel;
@property(retain, nonatomic) UIScrollView *containerView; // @synthesize containerView=_containerView;
- (void).cxx_destruct;
- (id)_descriptionText;
- (void)controllerDone:(id)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLayoutSubviews;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

