//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AASetupAssistantConfigResponse, NSObject<OS_dispatch_queue>;

@interface BuddyAppleIDConfigurationManager : NSObject
{
    AASetupAssistantConfigResponse *_configurationResponse;
    NSObject<OS_dispatch_queue> *_urlConfigurationQueue;
    _Bool _serviceEnabled;
}

+ (id)sharedManager;
@property(readonly, nonatomic, getter=isServiceEnabled) _Bool serviceEnabled; // @synthesize serviceEnabled=_serviceEnabled;
- (void).cxx_destruct;
- (id)URLConfiguration;
- (void)getURLConfigurationWithHandler:(CDUnknownBlockType)arg1;
- (id)init;

@end

