//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BuddyChoiceController.h"

@class BuddyChoice;

@interface BuddyPhoneNumberPermissionController : BuddyChoiceController
{
    BuddyChoice *_enableChoice;
    BuddyChoice *_disableChoice;
}

+ (void)registerPhoneNumberPermissionEnabled:(_Bool)arg1;
+ (void)skippedByCloudConfig;
+ (id)cloudConfigSkipKey;
+ (_Bool)controllerNeedsToRun;
+ (_Bool)controllerAffectedByTapFreeSetup;
@property(retain, nonatomic) BuddyChoice *disableChoice; // @synthesize disableChoice=_disableChoice;
@property(retain, nonatomic) BuddyChoice *enableChoice; // @synthesize enableChoice=_enableChoice;
- (void).cxx_destruct;
- (void)didSelectChoice:(id)arg1;
- (id)init;

@end

