//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BuddyChoiceController.h"

@class CBClient, UILabel, UIView;

@interface BuddyHarmonyController : BuddyChoiceController
{
    UILabel *_label;
    UIView *_button;
    CBClient *_brightnessClient;
}

+ (id)cloudConfigSkipKey;
+ (_Bool)controllerNeedsToRun;
- (void).cxx_destruct;
- (void)didSelectChoice:(id)arg1;
- (void)viewDidLayoutSubviews;
- (void)buttonPressed:(id)arg1;
- (void)_toggleSelection:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)loadView;
- (id)init;

@end

