//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BuddySimpleTCController.h"

@class NSString;

@interface BuddyiTMSTCController : BuddySimpleTCController
{
    NSString *_terms;
}

- (void).cxx_destruct;
- (id)titleString;
- (id)tcContent;
- (id)initWithTerms:(id)arg1;

@end

