//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "BFFFlowItemDelegate.h"
#import "BuddyAppleIDSpinnerPageDelegate.h"
#import "RUIObjectModelDelegate.h"
#import "RemoteUIWebViewControllerDelegate.h"

@class AASetupAssistantService, AAUICloudSyncServicesController, ACAccount, ACAccountStore, BuddyAboutPaneLoader, BuddyAppleIDAuthManager, BuddyAppleIDFindMyPhonePage, BuddyAppleIDSignInController, BuddyAppleIDSpinnerPage, BuddyAppleIDiCloudDrivePage, BuddyEmailSetupPage, NSDictionary, NSMutableArray, NSMutableDictionary, NSString, NSURL, RUILoader, RUIPage, SSAccount, UINavigationController, UIViewController;

@interface BuddyAppleIDController : NSObject <RUIObjectModelDelegate, BuddyAppleIDSpinnerPageDelegate, RemoteUIWebViewControllerDelegate, BFFFlowItemDelegate>
{
    ACAccount *_accountToUpgrade;
    struct OpaqueCFHTTPCookieStorage *_cookieStorage;
    SSAccount *_storeAccount;
    NSString *_storeUsername;
    NSString *_storePassword;
    RUILoader *_loader;
    BuddyAboutPaneLoader *_aboutLoader;
    NSMutableArray *_objectModels;
    NSURL *_createAppleIDURL;
    NSURL *_existingAccountTermsURL;
    NSURL *_aboutURL;
    NSURL *_genericTermsURL;
    _Bool _upgradeIsSkip;
    _Bool _didLoginDelegates;
    int _desiredPane;
    int _currentPane;
    _Bool _over13;
    RUIPage *_loadingPage;
    AAUICloudSyncServicesController *_iCloudSyncServicesController;
    BuddyAppleIDFindMyPhonePage *_findMyPhonePage;
    BuddyEmailSetupPage *_emailSetupPage;
    BuddyAppleIDiCloudDrivePage *_iCloudDrivePage;
    BuddyAppleIDSpinnerPage *_upgradeWithTokenAuthSpinnerPage;
    NSMutableDictionary *_spinnerApperanceHandlers;
    _Bool _restoreFromBackupMode;
    int _existingAccountType;
    int _operationType;
    _Bool _omitITunesBundle;
    NSString *_existingAccountID;
    NSString *_accountDSID;
    _Bool _completingEnablingCloudServices;
    ACAccountStore *_upgradeAccountStore;
    BuddyAppleIDAuthManager *_authManager;
    BuddyAppleIDAuthManager *_twoAccountsiCloudAuthManager;
    BuddyAppleIDAuthManager *_twoAccountsiTunesAuthManager;
    BuddyAppleIDSignInController *_twoAccountsiCloudSignInPage;
    NSDictionary *_twoAccountsiCloudAuthResults;
    NSString *_emailChoice;
    CDUnknownBlockType _didAuthCompletion;
    UIViewController *_authAttemptLandingViewController;
    _Bool _legacyCreate;
    NSString *_rawPassword;
    _Bool _removeBackToSignInPageOnFirstRemoteUIPush;
    id <BuddyAppleIDControllerDelegate> _delegate;
    UINavigationController *_navigationController;
    AASetupAssistantService *_aaService;
}

@property(nonatomic) _Bool restoreFromBackupMode; // @synthesize restoreFromBackupMode=_restoreFromBackupMode;
@property(retain, nonatomic) UIViewController *authAttemptLandingViewController; // @synthesize authAttemptLandingViewController=_authAttemptLandingViewController;
@property(retain, nonatomic) AASetupAssistantService *aaService; // @synthesize aaService=_aaService;
@property(readonly, nonatomic) int operationType; // @synthesize operationType=_operationType;
@property(copy, nonatomic) NSString *existingAccountID; // @synthesize existingAccountID=_existingAccountID;
@property(nonatomic) __weak UINavigationController *navigationController; // @synthesize navigationController=_navigationController;
@property(nonatomic) __weak id <BuddyAppleIDControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)cleanupRemoteUI;
- (void)objectModelPressedBack:(id)arg1;
- (id)parentViewControllerForObjectModel:(id)arg1;
- (id)_remoteUINavController;
- (void)remoteUIWebViewControllerDonePressed:(id)arg1;
- (void)_removeBackToPageMatchingBlock:(CDUnknownBlockType)arg1;
- (void)loader:(id)arg1 didFailWithError:(id)arg2;
- (void)objectModelDidChange:(id)arg1;
- (_Bool)objectModel:(id)arg1 shouldShowModalHTMLViewWithURL:(id)arg2;
- (void)objectModel:(id)arg1 pressedLink:(id)arg2 httpMethod:(id)arg3;
- (void)objectModel:(id)arg1 pressedButton:(id)arg2 attributes:(id)arg3;
- (void)loader:(id)arg1 receivedObjectModel:(id)arg2 actionSignal:(unsigned long long)arg3;
- (void)_popObjectModelAnimated:(_Bool)arg1;
- (void)_cleanupLoader;
- (void)_authCompletedShouldProceed:(_Bool)arg1 error:(id)arg2;
- (void)appleIDControllerCompletedShouldProceed:(_Bool)arg1 error:(id)arg2;
- (void)_popBackToAuthAttemptLandingPage;
- (void)cancelAuthentication;
- (void)didAuthenticateWithResults:(id)arg1 showPostSignIn:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)_clearStoreAccount;
- (void)_userRespondedToCombinedTCsWithAgreement:(_Bool)arg1 withSLAVersion:(id)arg2;
- (void)_setAppearanceHandler:(CDUnknownBlockType)arg1 forSpinnerPage:(id)arg2;
- (void)showSpinnerPage:(id)arg1 appearanceHandler:(CDUnknownBlockType)arg2;
- (void)buddyAppleIDSpinnerPageDidAppear:(id)arg1;
- (void)_createOrUpdateAppleAccountWithCompletion:(CDUnknownBlockType)arg1;
- (void)_didNotifyAppleIDLoginPluginsWithCompletion:(CDUnknownBlockType)arg1;
- (void)_loginDelegateAccountsWithCompletion:(CDUnknownBlockType)arg1;
- (void)_setupiTunesAndLoginDelegateAccountsCompletion:(CDUnknownBlockType)arg1;
- (void)_nameDevice;
- (void)_createMeCard;
- (void)_loadRepairCloudAccountRemoteUIWithContinuationData:(id)arg1;
- (void)_loadPostSignInRemoteUI;
- (void)_showPostSignInRemoteUI;
- (void)_showPostSignInPage;
- (void)flowItemDone:(id)arg1 nextItemClass:(Class)arg2;
- (void)flowItemDone:(id)arg1 nextItem:(id)arg2;
- (void)flowItemDone:(id)arg1;
- (void)showiCloudDrivePageIfNecessary;
- (void)_vetHSAAuthToken:(id)arg1 fullMessage:(id)arg2 sourceAddress:(id)arg3 serviceID:(id)arg4;
- (void)_vetIfNeeded;
- (void)buddyEmailSetupPage:(id)arg1 didEnterPassword:(id)arg2;
- (void)_showEmailSetupPage;
- (_Bool)_canAutoSetupEmail;
- (_Bool)_needsEmailSetup;
- (void)_vetEmail;
- (_Bool)_needsEmailVetting;
- (void)_vettingCompleted;
- (void)enableTouchIDForPurchasesIfNeededWithCompletion:(CDUnknownBlockType)arg1;
- (void)_enableTouchIDForPurchasesIfNeeded;
- (void)_reallyCompleteEnablingCloudServices;
- (void)_reallyEnableBackupAndCloudServices;
- (void)_enableBackupAndCloudServices;
- (void)_runFacetimeRegistration;
- (id)iCloudRestoreSignInViewController;
- (id)signInViewController;
- (void)_showTwoAccountsiCloudSignInPage;
- (void)_showTwoAccountsiTunesSignInPage;
- (void)enableCloudServices;
- (void)runFindMyPhoneFlow;
- (_Bool)shouldAllowStartOver;
- (void)dealloc;
- (void)_showAboutPageErrorForError:(id)arg1;
- (void)_showSignInFailure:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_showPasswordFailureWithCompletion:(CDUnknownBlockType)arg1;
- (void)_showUpdateAppleIDFailure:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_showCreateAppleIDFailure:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_loadCreateAppleIDUI;
- (void)_addHeadersToRequest:(id)arg1;
- (void)_showSpinnerPageWithIdentifier:(id)arg1 handler:(CDUnknownBlockType)arg2;
- (void)_postSignInRemoteUIFinishedWithSuccess:(_Bool)arg1 error:(id)arg2 withSpinnerAction:(CDUnknownBlockType)arg3;
- (void)createOrUpdateAccountWithDelegateSignIn:(_Bool)arg1;
- (void)appleIDFindMyPhoneAboutPressed;
- (void)showAboutAppleID;
- (void)_loadSkipDataWithCompletion:(CDUnknownBlockType)arg1;
- (void)skipAppleID;
- (void)upgradeiCloudSignInPageDidSkip;
- (void)_upgradeAccountWithPassword:(id)arg1 rawPassword:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)upgradeAccountWithTokenAuth;
- (void)_beginPostUpgradeAppleIDLoginWithUsername:(id)arg1 password:(id)arg2 continuationKey:(id)arg3 signInController:(id)arg4;
- (void)_beginPostUpgradeAppleIDLoginWithUsername:(id)arg1 password:(id)arg2 signInController:(id)arg3;
- (id)silentUpgradeViewControllerWithLoginContext:(id)arg1;
- (id)upgradeAccountSignInViewController;
- (void)_loadUpgradeUIForResponseData:(id)arg1 proceedOnFailure:(_Bool)arg2;
- (_Bool)isLoadingRemoteUI;
- (void)showCreateAppleID;
- (void)showiForgot;
- (void)showiForgotWithLandingPage:(id)arg1;
- (void)_pushNextViewController:(id)arg1;
- (void)_tryShowingPane;
- (void)_reallyTryShowingPane;
- (void)setExistingAccountType:(int)arg1;
- (void)_downloadURLConfigurationIfNeededCompletion:(CDUnknownBlockType)arg1;
- (void)appleIDControllerFinished;
- (id)init;
- (id)initWithAccount:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

