//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "BFFFlowItem.h"

@class NSString, WLWelcomeViewController;

@interface BuddyWelcomeKitController : NSObject <BFFFlowItem>
{
    WLWelcomeViewController *_welcomeViewController;
    id <BFFFlowItemDelegate> _delegate;
}

+ (id)cloudConfigSkipKey;
+ (_Bool)showWelcomeKitRestoreChoice;
+ (void)prefetchShowWelcomeKitRestoreChoice;
@property(nonatomic) __weak id <BFFFlowItemDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)_welcomeKitDidFinishWithSuccess:(_Bool)arg1;
- (_Bool)controllerAllowsNavigatingBack;
- (id)viewController;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

