//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BuddyTableViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "UITextFieldDelegate.h"

@class BFFLinkLabelFooterView, BuddyAppleIDInfoIconView, NSNotification, NSString, OBPrivacyLinkController, UITableViewCell, UIView;

@interface BuddyAppleIDSignInController : BuddyTableViewController <UITextFieldDelegate, UITableViewDelegate, UITableViewDataSource>
{
    UITableViewCell *_usernameCell;
    UITableViewCell *_passwordCell;
    NSString *_lastEnteredUsername;
    BFFLinkLabelFooterView *_topSectionFooterView;
    BFFLinkLabelFooterView *_infoFooterView;
    BFFLinkLabelFooterView *_twoAccountsView;
    OBPrivacyLinkController *_privacyLink;
    UIView *_privacyLinkContainer;
    BuddyAppleIDInfoIconView *_infoIconView;
    struct CGRect _lastKeyboardFrame;
    double _availableHeaderFooterHeight;
    NSNotification *_keyboardNotification;
    int _mode;
    _Bool _phoneNumberSupported;
    _Bool _showsUsernameAsField;
    _Bool _showsPasswordAsField;
    _Bool _showsInfoSection;
    _Bool _enabled;
    CDUnknownBlockType _handler;
    CDUnknownBlockType _appearanceHandler;
    CDUnknownBlockType _authModeHandler;
    CDUnknownBlockType _twoAccountsHandler;
}

+ (id)localizedAboutAppleIDAndPrivacyLinkTitle;
+ (id)federatedAuthSignInControllerInNavigationController:(id)arg1 mode:(int)arg2;
@property(nonatomic) _Bool enabled; // @synthesize enabled=_enabled;
@property(copy, nonatomic) CDUnknownBlockType twoAccountsHandler; // @synthesize twoAccountsHandler=_twoAccountsHandler;
@property(nonatomic) _Bool showsInfoSection; // @synthesize showsInfoSection=_showsInfoSection;
@property(nonatomic) _Bool showsPasswordAsField; // @synthesize showsPasswordAsField=_showsPasswordAsField;
@property(nonatomic) _Bool showsUsernameAsField; // @synthesize showsUsernameAsField=_showsUsernameAsField;
@property(copy, nonatomic) CDUnknownBlockType authModeHandler; // @synthesize authModeHandler=_authModeHandler;
@property(copy, nonatomic) CDUnknownBlockType appearanceHandler; // @synthesize appearanceHandler=_appearanceHandler;
@property(copy, nonatomic) CDUnknownBlockType handler; // @synthesize handler=_handler;
- (void).cxx_destruct;
- (void)setShowsPasswordAsField:(_Bool)arg1 animated:(_Bool)arg2;
- (void)_setNextButtonEnabledOrDisabled;
- (void)_textChanged:(id)arg1;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)_signInToAccount;
- (void)_nextButtonTapped;
- (id)passwordCell;
@property(copy, nonatomic) NSString *username;
- (id)usernameCell;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (struct UIEdgeInsets)_infoFooterViewMargins;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (_Bool)useScreenFooter;
- (void)viewDidLayoutSubviews;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)loadView;
- (double)rowHeight;
- (void)keyboardWillHide:(id)arg1;
- (void)keyboardWillShow;
- (void)coalescingKeyboardWillShow:(id)arg1;
- (id)twoAccountsView;
- (id)privacyLinkContainer;
- (id)infoFooterView;
- (id)infoIconView;
- (id)topSectionFooterView;
@property(copy, nonatomic) NSString *footerText;
- (void)removeFooterLinkAtIndex:(unsigned long long)arg1;
- (void)addFooterLinkWithTitle:(id)arg1 handler:(CDUnknownBlockType)arg2;
- (void)setiForgotText:(id)arg1 handler:(CDUnknownBlockType)arg2;
- (id)_footerText;
- (id)_subTitleText;
- (id)stringWithUsernameFormattedIntoString:(id)arg1;
- (id)_titleText;
- (void)dealloc;
- (id)initWithMode:(int)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

