//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SetupChoiceController.h"

#import "UITextFieldDelegate.h"

@class BuddyCloudConfigController, NSError, NSString, UIBarButtonItem, UITableViewCell, UITextField;

@interface BuddyCloudConfigLoginViewController : SetupChoiceController <UITextFieldDelegate>
{
    BuddyCloudConfigController *_configController;
    NSError *_lastError;
    UITableViewCell *_usernameCell;
    UITableViewCell *_passwordCell;
    UIBarButtonItem *_nextButton;
    UITextField *_activeTextField;
}

@property(retain, nonatomic) UITextField *activeTextField; // @synthesize activeTextField=_activeTextField;
@property(retain, nonatomic) UIBarButtonItem *nextButton; // @synthesize nextButton=_nextButton;
@property(retain, nonatomic) UITableViewCell *passwordCell; // @synthesize passwordCell=_passwordCell;
@property(retain, nonatomic) UITableViewCell *usernameCell; // @synthesize usernameCell=_usernameCell;
@property(retain, nonatomic) NSError *lastError; // @synthesize lastError=_lastError;
@property(nonatomic) __weak BuddyCloudConfigController *configController; // @synthesize configController=_configController;
- (void).cxx_destruct;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)textFieldDidEndEditing:(id)arg1;
- (void)textFieldDidBeginEditing:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)retryLogin;
- (void)_textChanged:(id)arg1;
- (void)_setupForCloudConfigurationState;
- (void)_layoutTableView;
- (void)viewDidLayoutSubviews;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)keyboardWillHide:(id)arg1;
- (void)keyboardDidShow:(id)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

