//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "BYExpressSetupDataSource.h"

@class BYExpressSetupBackupSource, BYExpressSetupDefaultSource, BYExpressSetupProximityDataSource, NSArray, NSMutableArray, NSNumber, NSString;

@interface BYExpressSetupDataProvider : NSObject <BYExpressSetupDataSource>
{
    _Bool _expressSettingsApplied;
    NSArray *_listedFeatures;
    NSMutableArray *_enabledFeatures;
    NSNumber *_hasStoredVoiceProfile;
    BYExpressSetupProximityDataSource *_proximitySetupDataSource;
    BYExpressSetupBackupSource *_backupDataSource;
    BYExpressSetupDefaultSource *_defaultSource;
}

@property(retain) BYExpressSetupDefaultSource *defaultSource; // @synthesize defaultSource=_defaultSource;
@property(retain) BYExpressSetupBackupSource *backupDataSource; // @synthesize backupDataSource=_backupDataSource;
@property(retain) BYExpressSetupProximityDataSource *proximitySetupDataSource; // @synthesize proximitySetupDataSource=_proximitySetupDataSource;
- (void).cxx_destruct;
- (_Bool)_hasiCloudSiriTrainingDataForLanguage:(id)arg1;
- (_Bool)_supportsAlwaysOnHeySiri;
- (_Bool)_siriWantsToRun;
- (id)_countryCode;
- (_Bool)_countrySupportsFastDeviceAnalyticsOptIn;
- (id)_cloudConfigManager;
- (_Bool)_isRestrictedForFeature:(unsigned long long)arg1;
- (void)_setEnabled:(_Bool)arg1 forFeature:(unsigned long long)arg2;
- (void)setEnabled:(_Bool)arg1 forFeature:(unsigned long long)arg2;
- (id)_stringForFeature:(unsigned long long)arg1;
- (void)revertExpressSettings;
- (void)skipExpressSettings;
- (void)applyExpressSettings;
- (_Bool)hasVoiceProfileIniCloud;
- (id)siriOptIn;
- (id)iCloudAnalyticsOptInError:(id *)arg1;
- (id)deviceAnalyticsOptIn;
- (id)appAnalyticsOptIn;
- (_Bool)locationServicesOptIn;
- (id)findMyPhoneOptIn;
- (id)appleID;
- (id)firstName;
- (id)sourceDeviceClass;
- (id)sourceDeviceName;
- (_Bool)dataAvailable;
- (id)expressSetupFeatures;
- (void)reset;
@property(readonly) unsigned long long dataSourceType;
- (id)dataSource;
@property(readonly, copy) NSString *description;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

