//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@class CAShapeLayer, CAShapeLayerAnimated;

@interface RecordButton : UIButton
{
    CAShapeLayer *_outer;
    CAShapeLayer *_outerWhite;
    CAShapeLayer *_innerWhite;
    CAShapeLayerAnimated *_innerRed;
}

- (void).cxx_destruct;
- (void)setEnabled:(_Bool)arg1;
- (void)layoutSubviews;
- (void)configure;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

