//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UNNotificationContentExtension.h"

@class NSString, UIColor;

@interface PhotosMemoriesNotificationsUpdatesViewController : UIViewController <UNNotificationContentExtension>
{
    UIViewController *_previewViewController;
}

- (void).cxx_destruct;
- (void)didReceiveNotification:(id)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)_dismissOneUpViewController;
- (void)_presentViewControllerForMemoryUUID:(id)arg1;
- (void)_updatePreferredContentSizeForPreferredPreviewSize:(struct CGSize)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) struct CGRect mediaPlayPauseButtonFrame;
@property(readonly, copy, nonatomic) UIColor *mediaPlayPauseButtonTintColor;
@property(readonly, nonatomic) unsigned long long mediaPlayPauseButtonType;
@property(readonly) Class superclass;

@end

