//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FBSystemApp.h"

@class NSTimer, PBAIdleSleepController;

@interface PBAApplication : FBSystemApp
{
    _Bool _eatMenuUp;
    NSTimer *_lockButtonTimer;
    PBAIdleSleepController *_idleSleepController;
}

+ (double)systemIdleSleepInterval;
+ (_Bool)registerAsSystemApp;
+ (_Bool)shouldCheckInWithBackboard;
@property(retain, nonatomic) PBAIdleSleepController *idleSleepController; // @synthesize idleSleepController=_idleSleepController;
@property(retain, nonatomic) NSTimer *lockButtonTimer; // @synthesize lockButtonTimer=_lockButtonTimer;
- (void).cxx_destruct;
- (void)_lockButtonUp;
- (void)_cancelLockButtonTimer;
- (void)_startLockButtonTimer;
- (void)_lockButtonLongPress;
- (void)_lockButtonDown;
- (_Bool)_handlePhysicalButtonEvent:(id)arg1;
- (void)_handleHIDEvent:(struct __IOHIDEvent *)arg1;
- (_Bool)__handleHIDEvent:(struct __IOHIDEvent *)arg1;
- (void)applicationDidOrderOutContext:(id)arg1 screen:(id)arg2;
- (void)applicationWillOrderInContext:(id)arg1 windowLevel:(float)arg2 screen:(id)arg3;
- (_Bool)_isSpringBoard;
- (void)_createStatusBarWithRequestedStyle:(long long)arg1 orientation:(long long)arg2 hidden:(_Bool)arg3;
- (id)init;

@end

