//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "PBADeviceBlockOverlayViewControllerDelegate.h"
#import "PBAPasscodeEntryViewControllerDelegate.h"

@class NSString, PBADeviceBlockOverlayViewController, PBASimpleLockScreenView, PBAStackViewController, SBFAuthenticationAssertion, SBFAuthenticationAssertionManager, SBFUserAuthenticationController;

@interface PBADeviceUnlockViewController : UIViewController <PBAPasscodeEntryViewControllerDelegate, PBADeviceBlockOverlayViewControllerDelegate>
{
    PBAStackViewController *_stackViewController;
    PBASimpleLockScreenView *_newLockScreenView;
    PBADeviceBlockOverlayViewController *_blockOverlayController;
    _Bool _attemptingUnlock;
    SBFAuthenticationAssertion *_transientAssertion;
    id <SBFLockOutStatusProvider> _deviceLockController;
    SBFUserAuthenticationController *_authenticationController;
    SBFAuthenticationAssertionManager *_assertionManager;
    id <SBFAuthenticationPolicy> _authenticationPolicy;
}

- (void).cxx_destruct;
- (id)_localizedUpgradeStringForHomeButtonType:(long long)arg1;
- (void)_invalidAuthHandler:(id)arg1;
- (void)_failedAuthHandler:(id)arg1 error:(id)arg2;
- (void)_successfulAuthHandler:(id)arg1 passcode:(id)arg2;
- (void)_resetStateAfterHandlingAuthenticationResult;
- (void)passcodeEntryViewControllerCancelButtonPressed:(id)arg1;
- (void)passcodeEntryViewControllerEntryCompleted:(id)arg1 passcode:(id)arg2;
- (void)passcodeEntryViewControllerEntryCancelled:(id)arg1;
- (void)passcodeEntryViewControllerEntryBegan:(id)arg1;
- (void)deviceBlockOverlayViewControllerDidChangeBlockState:(id)arg1;
- (void)_pushPasscodeEntryView;
- (void)_handleEdgeSwipe:(id)arg1;
- (void)_homeButtonPressed:(id)arg1;
- (void)_evaluateDeviceBlockState;
- (void)_handleUnblockedDevice;
- (void)_handleBlockedDevice;
- (void)handlePasscodeLockStatusChangeNotification:(id)arg1;
- (void)registerForUnlockNotification;
- (void)deviceUnlocked:(CDUnknownBlockType)arg1;
- (_Bool)shouldAutorotate;
- (unsigned long long)supportedInterfaceOrientations;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithContainingStackViewController:(id)arg1 authenticationPolicy:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

