//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "PBADeviceBlockOverlayViewControllerDelegate.h"
#import "PBAPasscodeEntryViewControllerDelegate.h"
#import "UIGestureRecognizerDelegate.h"

@class NSData, NSString, PBADataRecoveryEngine, PBADeviceBlockOverlayViewController, PBAIdleSleepController, PBAStackViewController, SBFAuthenticationAssertionManager, SBFDeviceLockOutController, SBFUserAuthenticationController;

@interface PBADataRecoveryViewController : UIViewController <PBAPasscodeEntryViewControllerDelegate, PBADeviceBlockOverlayViewControllerDelegate, UIGestureRecognizerDelegate>
{
    PBADataRecoveryEngine *_dataRecoveryEngine;
    PBAStackViewController *_stackViewController;
    NSData *_firstPasscode;
    PBAIdleSleepController *_idleSleepController;
    SBFAuthenticationAssertionManager *_assertionManager;
    id <SBFAuthenticationPolicy> _authenticationPolicy;
    SBFUserAuthenticationController *_authenticationController;
    SBFDeviceLockOutController *_deviceLockOutController;
    PBADeviceBlockOverlayViewController *_blockOverlayController;
}

@property(retain, nonatomic) PBADataRecoveryEngine *dataRecoveryEngine; // @synthesize dataRecoveryEngine=_dataRecoveryEngine;
- (void).cxx_destruct;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceivePress:(id)arg2;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (void)passcodeEntryViewControllerCancelButtonPressed:(id)arg1;
- (void)passcodeEntryViewControllerEntryCompleted:(id)arg1 passcode:(id)arg2;
- (void)deviceBlockOverlayViewControllerDidChangeBlockState:(id)arg1;
- (void)_evaluateDeviceBlockState;
- (void)_handleUnblockedDevice;
- (void)_handleBlockedDevice;
- (void)_beginRecovery:(id)arg1 fromViewController:(id)arg2;
- (void)_pushPasscodeView;
- (void)_handleEdgeSwipe:(id)arg1;
- (void)_homeButtonPressed:(id)arg1;
- (id)_localizedRecoveryStringForHomeButtonType:(long long)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (void)loadView;
- (id)initWithContainingStackViewController:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

