//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSObject<OS_dispatch_queue>, SBFMobileKeyBag;

@interface PBADataRecoveryEngine : NSObject
{
    NSObject<OS_dispatch_queue> *_queue;
    NSObject<OS_dispatch_queue> *_calloutQueue;
    SBFMobileKeyBag *_queue_mobileKeyBag;
}

- (void).cxx_destruct;
- (void)_queue_performDataRecoveryWithPasscode:(id)arg1 progressHandler:(CDUnknownBlockType)arg2 completion:(CDUnknownBlockType)arg3;
- (void)performDataRecoveryWithPasscode:(id)arg1 progressHandler:(CDUnknownBlockType)arg2 completion:(CDUnknownBlockType)arg3;
@property(readonly, nonatomic) _Bool dataRecoveryPossible;
@property(readonly, nonatomic) _Bool requiresDataRecovery;
- (id)init;
- (id)initWithMobileKeyBag:(id)arg1;

@end

