//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "DKDiagnosticInputs.h"

@class NSNumber, NSString;

@interface ProximitySensorInputs : NSObject <DKDiagnosticInputs>
{
    NSNumber *_noInputTimeout;
    NSNumber *_holdTime;
}

@property(retain, nonatomic) NSNumber *holdTime; // @synthesize holdTime=_holdTime;
@property(retain, nonatomic) NSNumber *noInputTimeout; // @synthesize noInputTimeout=_noInputTimeout;
- (void).cxx_destruct;
- (_Bool)validateAndInitializeParameters:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

