//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SSHBHIDSamplePrintable.h"

@class NSMutableArray;

@interface SSHBHIDSampleBuffer : NSObject <SSHBHIDSamplePrintable>
{
    _Bool _isFull;
    NSMutableArray *_buffer;
    unsigned long long _bufferSize;
}

@property(nonatomic) unsigned long long bufferSize; // @synthesize bufferSize=_bufferSize;
@property(retain, nonatomic) NSMutableArray *buffer; // @synthesize buffer=_buffer;
@property(nonatomic) _Bool isFull; // @synthesize isFull=_isFull;
- (void).cxx_destruct;
- (void)writeSamplesWithFilePath:(id)arg1;
- (id)csv;
- (id)removeSample;
- (void)addSample:(id)arg1;
- (id)sampleBuffer;
- (id)initWithSize:(unsigned long long)arg1;
- (id)init;

@end

