//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SSHBHIDManagerDelegate.h"

@class SSHBHIDManager;

@interface Turtle : NSObject <SSHBHIDManagerDelegate>
{
    id <SSHBHIDSSHBTurtleDelegate> _delegate;
    SSHBHIDManager *_hidManager;
    struct __IOHIDDevice *_turtleRef;
}

@property(nonatomic) struct __IOHIDDevice *turtleRef; // @synthesize turtleRef=_turtleRef;
@property(retain, nonatomic) SSHBHIDManager *hidManager; // @synthesize hidManager=_hidManager;
@property(nonatomic) __weak id <SSHBHIDSSHBTurtleDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)criticalErrors:(id *)arg1;
- (id)_getReport:(int)arg1 error:(id *)arg2;
- (id)_frequentScanPeriodMs:(id *)arg1;
- (_Bool)configureFrequentBackgroundScan:(_Bool)arg1 error:(id *)arg2;
- (_Bool)gapSubtraction:(_Bool)arg1 error:(id *)arg2;
- (void)waitForDuration:(double)arg1;
- (id)bytesToInputPacket:(CDStruct_88bb3f59 *)arg1;
- (void)hidReportCallback:(struct __IOHIDDevice *)arg1 result:(int)arg2 type:(int)arg3 reportID:(unsigned int)arg4 report:(char *)arg5 reportLength:(long long)arg6;
- (void)deviceWasRemoved:(struct __IOHIDDevice *)arg1;
- (void)deviceWasAdded:(struct __IOHIDDevice *)arg1;
- (id)init;

@end

