//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DKReporterController.h"

#import "DKReporter.h"

@class DKComponentIdentity, NSString;

@interface ComponentBase : DKReporterController <DKReporter>
{
}

- (void)populateAttributes:(struct NSMutableDictionary *)arg1;
- (_Bool)isPresent;
- (void)setupWithContext:(id)arg1;

// Remaining properties
@property(readonly, nonatomic) DKComponentIdentity *componentIdentity;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

