//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class Alarm, AlarmManager;

@protocol AlarmManagerObserver <NSObject>

@optional
- (void)alarmManagerDidUpdateAlarms:(AlarmManager *)arg1;
- (void)alarmManager:(AlarmManager *)arg1 didUpdateAlarm:(Alarm *)arg2;
- (void)alarmManager:(AlarmManager *)arg1 didRemoveAlarm:(Alarm *)arg2;
- (void)alarmManager:(AlarmManager *)arg1 didAddAlarm:(Alarm *)arg2;
@end

