//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class MTUIAlarmView, UISwitch;

@interface MTAAlarmTableViewCell : UITableViewCell
{
    id <AlarmActiveDelegate> _alarmActiveDelegate;
    MTUIAlarmView *_alarmView;
    _Bool _enabled;
    UISwitch *_enabledSwitch;
}

@property(retain, nonatomic) UISwitch *enabledSwitch; // @synthesize enabledSwitch=_enabledSwitch;
- (void).cxx_destruct;
- (void)setupAsTemplateLayoutCell:(_Bool)arg1;
- (void)setEditing:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setHighlighted:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)willTransitionToState:(unsigned long long)arg1;
- (void)_alarmActiveChanged:(id)arg1;
- (void)setAlarmActiveDelegate:(id)arg1;
- (void)refreshUI:(id)arg1 animated:(_Bool)arg2;
- (void)setBackgroundColor:(id)arg1;
- (void)internalSetBackgroundColor:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (id)init;

@end

