//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewController.h"

@class MTAStopwatchLapCell, NSMutableArray;

@interface MTAStopwatchLapTableViewController : UITableViewController
{
    _Bool _showsCurrentLap;
    double _currentInterval;
    unsigned long long _cellStyle;
    double _previousLapsTotalInterval;
    NSMutableArray *_lapTimes;
    MTAStopwatchLapCell *_currentLapCell;
    CDStruct_d2880215 _lapExtrema;
}

@property(retain, nonatomic) MTAStopwatchLapCell *currentLapCell; // @synthesize currentLapCell=_currentLapCell;
@property(nonatomic) CDStruct_d2880215 lapExtrema; // @synthesize lapExtrema=_lapExtrema;
@property(retain, nonatomic) NSMutableArray *lapTimes; // @synthesize lapTimes=_lapTimes;
@property(nonatomic) double previousLapsTotalInterval; // @synthesize previousLapsTotalInterval=_previousLapsTotalInterval;
@property(nonatomic) unsigned long long cellStyle; // @synthesize cellStyle=_cellStyle;
@property(nonatomic) _Bool showsCurrentLap; // @synthesize showsCurrentLap=_showsCurrentLap;
@property(nonatomic) double currentInterval; // @synthesize currentInterval=_currentInterval;
- (void).cxx_destruct;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)_updateLapExtrema;
- (double)runningTotalForLap:(long long)arg1;
- (unsigned long long)lapCount;
- (void)clearAllLaps;
- (void)setLaps:(id)arg1;
- (void)addLap:(double)arg1;
- (void)_updateCurrentLapCell;
- (void)loadView;
- (id)initWithStyle:(long long)arg1;

@end

