//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

#import "MTUIWorldClockCellViewDelegate.h"

@class MTUIWorldClockCellView, NSString, WorldClockCity;

@interface MTAWorldClockTableViewCell : UITableViewCell <MTUIWorldClockCellViewDelegate>
{
    WorldClockCity *_city;
    MTUIWorldClockCellView *_clockCellView;
}

+ (float)defaultHeight;
@property(readonly, nonatomic) MTUIWorldClockCellView *clockCellView; // @synthesize clockCellView=_clockCellView;
- (void).cxx_destruct;
- (void)timeDidChangeForClockCell:(id)arg1;
- (void)willTransitionToState:(unsigned long long)arg1;
- (void)setEditing:(_Bool)arg1 animated:(_Bool)arg2;
@property(retain, nonatomic) WorldClockCity *city; // @synthesize city=_city;
- (void)updateShouldStackViewInCell:(_Bool)arg1;
- (void)setupConstraints;
- (void)prepareForReuse;
- (void)dealloc;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

