//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface CPKeyView : UIView
{
    long long _keyIndex;
}

@property(nonatomic) long long keyIndex; // @synthesize keyIndex=_keyIndex;
- (_Bool)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;
- (_Bool)canBecomeFocused;

@end

