//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class NSArray, NSDictionary, NSLayoutConstraint, PHRecentsItem, UIDateLabel, UIImageView, UILabel;

@interface MPRecentsTableViewCell : UITableViewCell
{
    NSDictionary *_allViewsDictionary;
    NSLayoutConstraint *_topConstraint;
    NSLayoutConstraint *_bottomConstraint;
    NSLayoutConstraint *_dateTrailingConstraint;
    NSLayoutConstraint *_countTrailingConstraint;
    NSLayoutConstraint *_dateYConstraint;
    NSLayoutConstraint *_labelConstraint;
    NSLayoutConstraint *_labelCountConstraint;
    NSLayoutConstraint *_countBaselineConstraint;
    NSLayoutConstraint *_nameTrailingConstraint;
    NSLayoutConstraint *_iconYConstraint;
    NSLayoutConstraint *_iconXConstraint;
    NSLayoutConstraint *_nameLeftAlignConstraint;
    NSLayoutConstraint *_labelLeftAlignConstraint;
    NSLayoutConstraint *_dateLeftAlignConstraint;
    NSArray *_nameCountDateVisualConstraints;
    NSArray *_labelDateVisualConstraints;
    NSArray *_labelCountVisualConstraints;
    _Bool _accessibilityConstraintsEnabled;
    _Bool _builtConstraints;
    PHRecentsItem *_item;
    UILabel *_callerCountLabel;
    UIDateLabel *_callerDateLabel;
    UILabel *_callerLabelLabel;
    UILabel *_callerNameLabel;
    UIImageView *_callTypeIconView;
}

+ (id)allMetrics;
+ (double)minimumRowHeight;
+ (double)marginWidth;
+ (double)editingMarginWidth;
@property(nonatomic) _Bool builtConstraints; // @synthesize builtConstraints=_builtConstraints;
@property(nonatomic) _Bool accessibilityConstraintsEnabled; // @synthesize accessibilityConstraintsEnabled=_accessibilityConstraintsEnabled;
@property(readonly, nonatomic) UIImageView *callTypeIconView; // @synthesize callTypeIconView=_callTypeIconView;
@property(readonly, nonatomic) UILabel *callerNameLabel; // @synthesize callerNameLabel=_callerNameLabel;
@property(readonly, nonatomic) UILabel *callerLabelLabel; // @synthesize callerLabelLabel=_callerLabelLabel;
@property(readonly, nonatomic) UIDateLabel *callerDateLabel; // @synthesize callerDateLabel=_callerDateLabel;
@property(readonly, nonatomic) UILabel *callerCountLabel; // @synthesize callerCountLabel=_callerCountLabel;
@property(retain, nonatomic) PHRecentsItem *item; // @synthesize item=_item;
- (void).cxx_destruct;
- (void)_updateCallerCountFont;
- (void)_updateFonts;
- (void)traitCollectionDidChange:(id)arg1;
- (void)_updateConstraints;
- (void)setConstraintsForConfiguration:(_Bool)arg1;
- (void)_buildConstraints;
- (void)setTableViewMarginWidth:(double)arg1 animated:(_Bool)arg2;
- (void)setEditing:(_Bool)arg1 animated:(_Bool)arg2;
@property(readonly) NSDictionary *allMetrics; // @dynamic allMetrics;
@property(readonly) NSDictionary *allViews; // @dynamic allViews;
- (void)dealloc;
- (void)commonInit;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly) long long count; // @dynamic count;

@end

