//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TPTableViewCell.h"

#import "VMActivityButtonsViewDelegate.h"
#import "VMMessageToolbarDelegate.h"

@class MPVoicemailMessageTableViewCellScrollView, NSLayoutConstraint, NSString, UIDateLabel, UIImageView, UITapGestureRecognizer, VMMessageMetadataView, VMMessageToolbar, VMMessageTranscriptView, VMPlayerControlsView;

@interface MPVoicemailMessageTableViewCell : TPTableViewCell <VMActivityButtonsViewDelegate, VMMessageToolbarDelegate>
{
    _Bool _expanded;
    _Bool _showsPlayerControls;
    _Bool _showsTranscriptionView;
    UIImageView *_unreadIndicatorImageView;
    NSString *_localizedTranscriptionMessage;
    id <MPVoicemailMessageTableViewCellDelegate> _delegate;
    VMMessageMetadataView *_metadataView;
    VMPlayerControlsView *_playerControlsView;
    VMMessageToolbar *_toolbar;
    VMMessageTranscriptView *_transcriptView;
    NSLayoutConstraint *_maximumHeightConstraint;
    MPVoicemailMessageTableViewCellScrollView *_containerScrollView;
    UITapGestureRecognizer *_metadataViewTapGestureRecognizer;
    NSLayoutConstraint *_containerTopLayoutConstraint;
    NSLayoutConstraint *_containerBottomLayoutConstraint;
    NSLayoutConstraint *_containerLeadingLayoutConstraint;
    NSLayoutConstraint *_containerTrailingLayoutConstraint;
    NSLayoutConstraint *_containerHeightLayoutConstraint;
    NSLayoutConstraint *_metadataViewBottomLayoutConstraint;
    NSLayoutConstraint *_metadataViewLeadingLayoutConstraint;
    NSLayoutConstraint *_metadataViewTopLayoutConstraint;
    NSLayoutConstraint *_metadataViewTrailingLayoutConstraint;
    NSLayoutConstraint *_playerControlsViewLeftLayoutConstraint;
    NSLayoutConstraint *_playerControlsViewTopLayoutConstraint;
    NSLayoutConstraint *_playerControlsViewRightLayoutConstraint;
    NSLayoutConstraint *_playerControlsViewTimelineSliderTopLayoutConstraint;
    NSLayoutConstraint *_toolbarBottomLayoutConstraint;
    NSLayoutConstraint *_toolbarLeadingLayoutConstraint;
    NSLayoutConstraint *_toolbarTopLayoutConstraint;
    NSLayoutConstraint *_toolbarTrailingLayoutConstraint;
    NSLayoutConstraint *_transcriptViewBottomLayoutConstraint;
    NSLayoutConstraint *_transcriptViewLeadingLayoutConstraint;
    NSLayoutConstraint *_transcriptViewTopLayoutConstraint;
    NSLayoutConstraint *_transcriptViewTrailingLayoutConstraint;
    NSLayoutConstraint *_unreadIndicatorImageViewHeightLayoutConstraint;
    NSLayoutConstraint *_unreadIndicatorImageViewLeadingLayoutConstraint;
    NSLayoutConstraint *_unreadIndicatorImageViewTopLayoutConstraint;
    NSLayoutConstraint *_unreadIndicatorImageViewWidthLayoutConstraint;
}

+ (double)unreadIndicatorImageViewWidthLayoutConstraintConstantForContentSizeCategory:(id)arg1;
+ (double)unreadIndicatorImageViewLeadingLayoutConstraintConstantForContentSizeCategory:(id)arg1;
+ (double)metadataViewLeadingLayoutConstraintConstantForContentSizeCategory:(id)arg1;
+ (struct UIEdgeInsets)separatorInsetForContentSizeCategory:(id)arg1;
+ (id)reuseIdentifier;
@property(retain, nonatomic) NSLayoutConstraint *unreadIndicatorImageViewWidthLayoutConstraint; // @synthesize unreadIndicatorImageViewWidthLayoutConstraint=_unreadIndicatorImageViewWidthLayoutConstraint;
@property(retain, nonatomic) NSLayoutConstraint *unreadIndicatorImageViewTopLayoutConstraint; // @synthesize unreadIndicatorImageViewTopLayoutConstraint=_unreadIndicatorImageViewTopLayoutConstraint;
@property(retain, nonatomic) NSLayoutConstraint *unreadIndicatorImageViewLeadingLayoutConstraint; // @synthesize unreadIndicatorImageViewLeadingLayoutConstraint=_unreadIndicatorImageViewLeadingLayoutConstraint;
@property(retain, nonatomic) NSLayoutConstraint *unreadIndicatorImageViewHeightLayoutConstraint; // @synthesize unreadIndicatorImageViewHeightLayoutConstraint=_unreadIndicatorImageViewHeightLayoutConstraint;
@property(retain, nonatomic) NSLayoutConstraint *transcriptViewTrailingLayoutConstraint; // @synthesize transcriptViewTrailingLayoutConstraint=_transcriptViewTrailingLayoutConstraint;
@property(retain, nonatomic) NSLayoutConstraint *transcriptViewTopLayoutConstraint; // @synthesize transcriptViewTopLayoutConstraint=_transcriptViewTopLayoutConstraint;
@property(retain, nonatomic) NSLayoutConstraint *transcriptViewLeadingLayoutConstraint; // @synthesize transcriptViewLeadingLayoutConstraint=_transcriptViewLeadingLayoutConstraint;
@property(retain, nonatomic) NSLayoutConstraint *transcriptViewBottomLayoutConstraint; // @synthesize transcriptViewBottomLayoutConstraint=_transcriptViewBottomLayoutConstraint;
@property(retain, nonatomic) NSLayoutConstraint *toolbarTrailingLayoutConstraint; // @synthesize toolbarTrailingLayoutConstraint=_toolbarTrailingLayoutConstraint;
@property(retain, nonatomic) NSLayoutConstraint *toolbarTopLayoutConstraint; // @synthesize toolbarTopLayoutConstraint=_toolbarTopLayoutConstraint;
@property(retain, nonatomic) NSLayoutConstraint *toolbarLeadingLayoutConstraint; // @synthesize toolbarLeadingLayoutConstraint=_toolbarLeadingLayoutConstraint;
@property(retain, nonatomic) NSLayoutConstraint *toolbarBottomLayoutConstraint; // @synthesize toolbarBottomLayoutConstraint=_toolbarBottomLayoutConstraint;
@property(retain, nonatomic) NSLayoutConstraint *playerControlsViewTimelineSliderTopLayoutConstraint; // @synthesize playerControlsViewTimelineSliderTopLayoutConstraint=_playerControlsViewTimelineSliderTopLayoutConstraint;
@property(retain, nonatomic) NSLayoutConstraint *playerControlsViewRightLayoutConstraint; // @synthesize playerControlsViewRightLayoutConstraint=_playerControlsViewRightLayoutConstraint;
@property(retain, nonatomic) NSLayoutConstraint *playerControlsViewTopLayoutConstraint; // @synthesize playerControlsViewTopLayoutConstraint=_playerControlsViewTopLayoutConstraint;
@property(retain, nonatomic) NSLayoutConstraint *playerControlsViewLeftLayoutConstraint; // @synthesize playerControlsViewLeftLayoutConstraint=_playerControlsViewLeftLayoutConstraint;
@property(retain, nonatomic) NSLayoutConstraint *metadataViewTrailingLayoutConstraint; // @synthesize metadataViewTrailingLayoutConstraint=_metadataViewTrailingLayoutConstraint;
@property(retain, nonatomic) NSLayoutConstraint *metadataViewTopLayoutConstraint; // @synthesize metadataViewTopLayoutConstraint=_metadataViewTopLayoutConstraint;
@property(retain, nonatomic) NSLayoutConstraint *metadataViewLeadingLayoutConstraint; // @synthesize metadataViewLeadingLayoutConstraint=_metadataViewLeadingLayoutConstraint;
@property(retain, nonatomic) NSLayoutConstraint *metadataViewBottomLayoutConstraint; // @synthesize metadataViewBottomLayoutConstraint=_metadataViewBottomLayoutConstraint;
@property(retain, nonatomic) NSLayoutConstraint *containerHeightLayoutConstraint; // @synthesize containerHeightLayoutConstraint=_containerHeightLayoutConstraint;
@property(retain, nonatomic) NSLayoutConstraint *containerTrailingLayoutConstraint; // @synthesize containerTrailingLayoutConstraint=_containerTrailingLayoutConstraint;
@property(retain, nonatomic) NSLayoutConstraint *containerLeadingLayoutConstraint; // @synthesize containerLeadingLayoutConstraint=_containerLeadingLayoutConstraint;
@property(retain, nonatomic) NSLayoutConstraint *containerBottomLayoutConstraint; // @synthesize containerBottomLayoutConstraint=_containerBottomLayoutConstraint;
@property(retain, nonatomic) NSLayoutConstraint *containerTopLayoutConstraint; // @synthesize containerTopLayoutConstraint=_containerTopLayoutConstraint;
@property(retain, nonatomic) UITapGestureRecognizer *metadataViewTapGestureRecognizer; // @synthesize metadataViewTapGestureRecognizer=_metadataViewTapGestureRecognizer;
@property(retain, nonatomic) MPVoicemailMessageTableViewCellScrollView *containerScrollView; // @synthesize containerScrollView=_containerScrollView;
@property(retain, nonatomic) NSLayoutConstraint *maximumHeightConstraint; // @synthesize maximumHeightConstraint=_maximumHeightConstraint;
@property(readonly, nonatomic) VMMessageTranscriptView *transcriptView; // @synthesize transcriptView=_transcriptView;
@property(readonly, nonatomic) VMMessageToolbar *toolbar; // @synthesize toolbar=_toolbar;
@property(readonly, nonatomic) VMPlayerControlsView *playerControlsView; // @synthesize playerControlsView=_playerControlsView;
@property(readonly, nonatomic) VMMessageMetadataView *metadataView; // @synthesize metadataView=_metadataView;
@property(nonatomic) _Bool showsTranscriptionView; // @synthesize showsTranscriptionView=_showsTranscriptionView;
@property(nonatomic) _Bool showsPlayerControls; // @synthesize showsPlayerControls=_showsPlayerControls;
@property(nonatomic) __weak id <MPVoicemailMessageTableViewCellDelegate> delegate; // @synthesize delegate=_delegate;
@property(copy, nonatomic) NSString *localizedTranscriptionMessage; // @synthesize localizedTranscriptionMessage=_localizedTranscriptionMessage;
@property(retain, nonatomic) UIImageView *unreadIndicatorImageView; // @synthesize unreadIndicatorImageView=_unreadIndicatorImageView;
@property(nonatomic) _Bool expanded; // @synthesize expanded=_expanded;
- (void).cxx_destruct;
- (void)messageToolbar:(id)arg1 handleActionForButtonType:(unsigned long long)arg2;
- (void)activityButtonsView:(id)arg1 handleActionForButtonType:(unsigned long long)arg2 event:(id)arg3;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (void)updateConstraintsConstants;
@property(readonly, nonatomic) double unreadIndicatorImageViewWidthLayoutConstraintConstant;
@property(readonly, nonatomic) double unreadIndicatorImageViewTopLayoutConstraintConstant;
@property(readonly, nonatomic) double unreadIndicatorImageViewLeadingLayoutConstraintConstant;
@property(readonly, nonatomic) double toolbarLeadingLayoutConstraintConstant;
@property(readonly, nonatomic) double playerControlsViewTimelineSliderTopLayoutConstraintConstant;
@property(readonly, nonatomic) double playerControlsViewRightLayoutConstraintConstant;
@property(readonly, nonatomic) double metadataViewTrailingLayoutConstraintConstant;
@property(readonly, nonatomic) double metadataViewLeadingLayoutConstraintConstant;
- (void)handleMetadataViewTapGesture:(id)arg1;
- (_Bool)shouldShowTranscriptView;
- (void)unloadConstraints;
- (void)loadConstraints;
- (void)loadContentView;
- (void)willTransitionToState:(unsigned long long)arg1;
- (void)setEditing:(_Bool)arg1 animated:(_Bool)arg2;
@property(copy, nonatomic) NSString *localizedSubtitle;
@property(copy, nonatomic) NSString *localizedTitle;
@property(copy, nonatomic) NSString *localizedDuration;
@property(copy, nonatomic) NSString *localizedDate;
- (void)setExpanded:(_Bool)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)setExpanded:(_Bool)arg1 animated:(_Bool)arg2;
@property(readonly, nonatomic) UIDateLabel *dateLabel;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

