//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CNContactStore, NSObject<OS_dispatch_queue>, TUCallProviderManager, TUMetadataCache;

@interface PHApplicationServices : NSObject
{
    TUCallProviderManager *_callProviderManager;
    CNContactStore *_contactStore;
    TUMetadataCache *_metadataCache;
    NSObject<OS_dispatch_queue> *_dispatchQueue;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *dispatchQueue; // @synthesize dispatchQueue=_dispatchQueue;
- (void).cxx_destruct;
@property(readonly, nonatomic) TUMetadataCache *metadataCache; // @synthesize metadataCache=_metadataCache;
@property(readonly, nonatomic) CNContactStore *contactStore; // @synthesize contactStore=_contactStore;
@property(readonly, nonatomic) TUCallProviderManager *callProviderManager; // @synthesize callProviderManager=_callProviderManager;
- (void)performAsynchronousWriteBlock:(CDUnknownBlockType)arg1;
- (void)performSynchronousReadBlock:(CDUnknownBlockType)arg1;
- (id)init;

@end

