//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UINavigationControllerDelegate.h"

@class NSString, PHCarPlayMainMenuContainerViewController, UINavigationController;

@interface PHCarPlayRootContainerViewController : UIViewController <UINavigationControllerDelegate>
{
    UINavigationController *_wrapperNavigationController;
    PHCarPlayMainMenuContainerViewController *_mainMenuContainerViewController;
}

@property(retain) PHCarPlayMainMenuContainerViewController *mainMenuContainerViewController; // @synthesize mainMenuContainerViewController=_mainMenuContainerViewController;
@property(retain) UINavigationController *wrapperNavigationController; // @synthesize wrapperNavigationController=_wrapperNavigationController;
- (void).cxx_destruct;
- (id)preferredFocusEnvironments;
- (void)navigationController:(id)arg1 willShowViewController:(id)arg2 animated:(_Bool)arg3;
- (void)viewWillAppear:(_Bool)arg1;
- (void)loadView;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

