//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIAlertController.h"

@class UIView;

@interface PHDialerAlertController : UIAlertController
{
    UIView *_sourceView;
}

@property(nonatomic) __weak UIView *sourceView; // @synthesize sourceView=_sourceView;
- (void).cxx_destruct;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;

@end

