//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSString, UIImageView, UILabel;

@interface PHRecentCallDetailsItemView : UIView
{
    UILabel *_durationAndDataLabel;
    UILabel *_statusLabel;
    UILabel *_timeLabel;
    id <PHRecentCallDetailsItemViewDelegate> _delegate;
    NSString *_callUUID;
    UIImageView *_ttyIndicatorImageView;
    UIImageView *_ttyDetailDisclosureImageView;
}

+ (id)_sharedDetailDisclosureImage;
+ (id)_sharedTTYRelayImage;
+ (id)_sharedTTYDirectImage;
@property(retain, nonatomic) UIImageView *ttyDetailDisclosureImageView; // @synthesize ttyDetailDisclosureImageView=_ttyDetailDisclosureImageView;
@property(retain, nonatomic) UIImageView *ttyIndicatorImageView; // @synthesize ttyIndicatorImageView=_ttyIndicatorImageView;
@property(retain, nonatomic) NSString *callUUID; // @synthesize callUUID=_callUUID;
@property(nonatomic) __weak id <PHRecentCallDetailsItemViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) UILabel *timeLabel; // @synthesize timeLabel=_timeLabel;
@property(retain, nonatomic) UILabel *statusLabel; // @synthesize statusLabel=_statusLabel;
@property(retain, nonatomic) UILabel *durationAndDataLabel; // @synthesize durationAndDataLabel=_durationAndDataLabel;
- (void).cxx_destruct;
- (void)handleTTYTranscriptAction:(id)arg1;
- (void)loadSubviewsLayoutConstraints;
- (void)loadSubviews;
- (struct CGSize)intrinsicContentSize;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1 callUUID:(id)arg2 andDelegate:(id)arg3;

@end

