//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CNContactFormatter, CNContactStore, NSArray, NSCache, NSNumberFormatter, NSObject<OS_dispatch_queue>, TUCallHistoryController, TUCallProviderManager, TUMetadataCache;

@interface PHRecentsController : NSObject
{
    int _callDirectoryManagerIdentificationEntriesChangedNotificationToken;
    TUCallHistoryController *_callHistoryController;
    NSCache *_callProviderCache;
    TUCallProviderManager *_callProviderManager;
    NSObject<OS_dispatch_queue> *_completionDispatchQueue;
    NSCache *_contactCache;
    CNContactFormatter *_contactFormatter;
    NSCache *_itemCache;
    NSNumberFormatter *_numberFormatter;
    TUMetadataCache *_metadataCache;
    NSArray *_recentCalls;
    unsigned long long _unreadCallCount;
    CNContactStore *_contactStore;
    NSObject<OS_dispatch_queue> *_concurrentDispatchQueue;
}

+ (id)indexPathsToInsertIntoCachedRecentCalls:(id)arg1 fromBackingRecentCalls:(id)arg2;
@property(nonatomic) int callDirectoryManagerIdentificationEntriesChangedNotificationToken; // @synthesize callDirectoryManagerIdentificationEntriesChangedNotificationToken=_callDirectoryManagerIdentificationEntriesChangedNotificationToken;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *concurrentDispatchQueue; // @synthesize concurrentDispatchQueue=_concurrentDispatchQueue;
@property(readonly, nonatomic) CNContactStore *contactStore; // @synthesize contactStore=_contactStore;
- (void).cxx_destruct;
- (void)performConcurrentSynchronousReadBlock:(CDUnknownBlockType)arg1;
- (void)handleUIApplicationSignificantTimeChangeNotification:(id)arg1;
- (void)handleTUMetadataCacheDidFinishUpdatingNotification:(id)arg1;
- (void)handleTUCallHistoryControllerUnreadCallCountDidChangeNotification:(id)arg1;
- (void)handleTUCallHistoryControllerRecentCallsDidChangeNotification:(id)arg1;
- (void)handleNSCurrentLocaleDidChangeNotification:(id)arg1;
- (void)handleIDSServiceAvailabilityDidChangeNotification:(id)arg1;
- (void)handleCNContactStoreDidChangeNotification:(id)arg1;
- (id)fetchRecentCalls;
- (id)fetchNumberFormatter;
- (void)fetchMetadataForRecentCalls:(id)arg1;
- (id)fetchImageForRecentCall:(id)arg1;
- (id)fetchContactFormatter;
- (id)fetchCallProviderForRecentCall:(id)arg1;
@property(nonatomic) unsigned long long unreadCallCount; // @synthesize unreadCallCount=_unreadCallCount;
@property(copy, nonatomic) NSArray *recentCalls; // @synthesize recentCalls=_recentCalls;
@property(retain, nonatomic) NSNumberFormatter *numberFormatter; // @synthesize numberFormatter=_numberFormatter;
@property(readonly, nonatomic) NSCache *itemCache; // @synthesize itemCache=_itemCache;
@property(retain, nonatomic) CNContactFormatter *contactFormatter; // @synthesize contactFormatter=_contactFormatter;
@property(readonly, nonatomic) NSCache *contactCache; // @synthesize contactCache=_contactCache;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *completionDispatchQueue; // @synthesize completionDispatchQueue=_completionDispatchQueue;
@property(readonly, nonatomic) TUCallProviderManager *callProviderManager; // @synthesize callProviderManager=_callProviderManager;
@property(readonly, nonatomic) NSCache *callProviderCache; // @synthesize callProviderCache=_callProviderCache;
@property(readonly, nonatomic) TUCallHistoryController *callHistoryController; // @synthesize callHistoryController=_callHistoryController;
- (id)contactForRecentCall:(id)arg1 keyDescriptors:(id)arg2;
- (void)markRecentAudioCallsAsRead;
- (void)markRecentCallsAsRead;
- (void)deleteRecentCalls:(id)arg1;
- (void)deleteAllRecentCalls;
- (_Bool)coalesceRecentCall:(id)arg1 withRecentCall:(id)arg2;
- (id)itemForRecentCall:(id)arg1;
@property(retain, nonatomic) TUMetadataCache *metadataCache; // @synthesize metadataCache=_metadataCache;
- (void)dealloc;
- (id)init;

@end

