//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TPTableViewCell.h"

@class NSLayoutConstraint, UILabel;

@interface PHTableViewCell : TPTableViewCell
{
    UILabel *_titleLabel;
    UILabel *_subtitleLabel;
    NSLayoutConstraint *_titleLabelFirstBaselineLayoutConstraint;
    NSLayoutConstraint *_titleLabelLastBaselineLayoutConstraint;
    NSLayoutConstraint *_titleLabelLeadingLayoutConstraint;
    NSLayoutConstraint *_titleLabelTrailingLayoutConstraint;
    NSLayoutConstraint *_subtitleLabelFirstBaselineLayoutConstraint;
    NSLayoutConstraint *_subtitleLabelLastBaselineLayoutConstraint;
    NSLayoutConstraint *_subtitleLabelLeadingLayoutConstraint;
    NSLayoutConstraint *_subtitleLabelTrailingLayoutConstraint;
    double _titleLabelFirstBaselineLayoutConstraintConstant;
    double _titleLabelLastBaselineLayoutConstraintConstant;
    double _titleLabelTrailingLayoutConstraintConstant;
    double _subtitleLabelFirstBaselineLayoutConstraintConstant;
    double _subtitleLabelLastBaselineLayoutConstraintConstant;
    double _subtitleLabelLeadingLayoutConstraintConstant;
    double _subtitleLabelTrailingLayoutConstraintConstant;
}

+ (double)titleLabelLeadingAnchorLayoutConstraintConstantForContentCategorySize:(id)arg1;
+ (id)reuseIdentifier;
@property(readonly, nonatomic) double subtitleLabelTrailingLayoutConstraintConstant; // @synthesize subtitleLabelTrailingLayoutConstraintConstant=_subtitleLabelTrailingLayoutConstraintConstant;
@property(readonly, nonatomic) double subtitleLabelLeadingLayoutConstraintConstant; // @synthesize subtitleLabelLeadingLayoutConstraintConstant=_subtitleLabelLeadingLayoutConstraintConstant;
@property(readonly, nonatomic) double subtitleLabelLastBaselineLayoutConstraintConstant; // @synthesize subtitleLabelLastBaselineLayoutConstraintConstant=_subtitleLabelLastBaselineLayoutConstraintConstant;
@property(readonly, nonatomic) double subtitleLabelFirstBaselineLayoutConstraintConstant; // @synthesize subtitleLabelFirstBaselineLayoutConstraintConstant=_subtitleLabelFirstBaselineLayoutConstraintConstant;
@property(readonly, nonatomic) double titleLabelTrailingLayoutConstraintConstant; // @synthesize titleLabelTrailingLayoutConstraintConstant=_titleLabelTrailingLayoutConstraintConstant;
@property(readonly, nonatomic) double titleLabelLastBaselineLayoutConstraintConstant; // @synthesize titleLabelLastBaselineLayoutConstraintConstant=_titleLabelLastBaselineLayoutConstraintConstant;
@property(readonly, nonatomic) double titleLabelFirstBaselineLayoutConstraintConstant; // @synthesize titleLabelFirstBaselineLayoutConstraintConstant=_titleLabelFirstBaselineLayoutConstraintConstant;
@property(retain, nonatomic) NSLayoutConstraint *subtitleLabelTrailingLayoutConstraint; // @synthesize subtitleLabelTrailingLayoutConstraint=_subtitleLabelTrailingLayoutConstraint;
@property(retain, nonatomic) NSLayoutConstraint *subtitleLabelLeadingLayoutConstraint; // @synthesize subtitleLabelLeadingLayoutConstraint=_subtitleLabelLeadingLayoutConstraint;
@property(retain, nonatomic) NSLayoutConstraint *subtitleLabelLastBaselineLayoutConstraint; // @synthesize subtitleLabelLastBaselineLayoutConstraint=_subtitleLabelLastBaselineLayoutConstraint;
@property(retain, nonatomic) NSLayoutConstraint *subtitleLabelFirstBaselineLayoutConstraint; // @synthesize subtitleLabelFirstBaselineLayoutConstraint=_subtitleLabelFirstBaselineLayoutConstraint;
@property(retain, nonatomic) NSLayoutConstraint *titleLabelTrailingLayoutConstraint; // @synthesize titleLabelTrailingLayoutConstraint=_titleLabelTrailingLayoutConstraint;
@property(retain, nonatomic) NSLayoutConstraint *titleLabelLeadingLayoutConstraint; // @synthesize titleLabelLeadingLayoutConstraint=_titleLabelLeadingLayoutConstraint;
@property(retain, nonatomic) NSLayoutConstraint *titleLabelLastBaselineLayoutConstraint; // @synthesize titleLabelLastBaselineLayoutConstraint=_titleLabelLastBaselineLayoutConstraint;
@property(retain, nonatomic) NSLayoutConstraint *titleLabelFirstBaselineLayoutConstraint; // @synthesize titleLabelFirstBaselineLayoutConstraint=_titleLabelFirstBaselineLayoutConstraint;
@property(retain, nonatomic) UILabel *subtitleLabel; // @synthesize subtitleLabel=_subtitleLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void).cxx_destruct;
@property(readonly, nonatomic) double titleLabelLeadingLayoutConstraintConstant;
- (void)updateFonts;
- (void)unloadConstraints;
- (void)loadContentView;
- (id)initWithCoder:(id)arg1;

@end

