//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIActivity.h"

@class VMVoicemail;

@interface PHVoicemailVoiceMemoActivity : UIActivity
{
    VMVoicemail *_voicemail;
}

+ (id)applicationProxy;
+ (long long)activityCategory;
@property(readonly, nonatomic) VMVoicemail *voicemail; // @synthesize voicemail=_voicemail;
- (void).cxx_destruct;
- (void)performActivity;
- (void)prepareWithActivityItems:(id)arg1;
- (_Bool)canPerformWithActivityItems:(id)arg1;
- (id)_bundleIdentifierForActivityImageCreation;
- (id)activityTitle;
- (id)activityType;
- (id)initWithVoicemail:(id)arg1;

@end

