//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VMViewController.h"

#import "VMPlayerViewController.h"

@class NSString, VMPlayerController, VMPlayerControlsView;

@interface VMPlayerViewController : VMViewController <VMPlayerViewController>
{
    VMPlayerController *_playerController;
    VMPlayerControlsView *_playerControlsView;
}

@property(retain, nonatomic) VMPlayerControlsView *playerControlsView; // @synthesize playerControlsView=_playerControlsView;
@property(retain, nonatomic) VMPlayerController *playerController; // @synthesize playerController=_playerController;
- (void).cxx_destruct;
- (void)playerControllerDidReset:(id)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

