//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VMViewController.h"

#import "PHVoicemailGreetingViewControllerDelegate.h"
#import "TPSetPINViewControllerDelegate.h"

@interface VMSetupViewController : VMViewController <PHVoicemailGreetingViewControllerDelegate, TPSetPINViewControllerDelegate>
{
    id <VMSetupViewControllerDelegate> _delegate;
    long long _state;
}

@property(nonatomic) long long state; // @synthesize state=_state;
@property(nonatomic) __weak id <VMSetupViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)setPINViewControllerFinished:(id)arg1 success:(_Bool)arg2 oldPIN:(id)arg3 newPIN:(id)arg4;
- (void)voicemailGreetingViewControllerFinished:(id)arg1;
- (void)contentUnavailableViewButtonAction;
- (void)viewDidLoad;

@end

