/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 21, 2018 at 11:42:38 PM Central European Summer Time
* Operating System: Version 11.3.1 (Build 15E302)
* Image Source: /Applications/ServerDocuments.app/Frameworks/ServerDocsClient.framework/ServerDocsClient
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol SVViewOptionsHeaderViewDelegate <NSObject>
@required
-(void)headerView:(id)arg1 didToggleDisplayMode:(long long)arg2;
-(void)headerView:(id)arg1 didChangeSortOrder:(long long)arg2;

@end

