//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ComponentBase.h"

@interface ComponentWiFi : ComponentBase
{
}

- (id)serialNumber;
- (_Bool)isPresent;
- (id)wifiAddress;
- (void)populateAttributes:(struct NSMutableDictionary *)arg1;
- (id)wifiDeviceCount;

@end

