//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ComponentCameraBase.h"

@interface ComponentStrobeFrontSLP : ComponentCameraBase
{
}

- (_Bool)serialNumberMismatch;
- (_Bool)flexDisconnected;
- (id)serialNumber;
- (void)populateAttributes:(struct NSMutableDictionary *)arg1;
- (_Bool)isPresent;

@end

