//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface OSDGrape : NSObject
{
    struct __MTDevice *_grapeDevice;
    NSString *_constructedFirmwareVersion;
    NSString *_bcdVersion;
    long long _resetCount;
}

- (void).cxx_destruct;
- (_Bool)setOrbImageCapacitanceMode;
- (_Bool)setOrbImageGapMode;
- (_Bool)_setOrbImageFrameType:(int)arg1;
- (unsigned int)getDopplerReferenceSignalEvents;
- (id)getDopplerSiliconVersion;
- (id)_getMTReportErrorFromCommandBuffer:(char *)arg1 length:(int)arg2;
- (id)getDopplerDataRegister;
- (id)getDopplerError;
- (_Bool)didDopplerErrorOccur;
- (_Bool)isDoppler;
- (_Bool)_unregisterForProx:(CDUnknownFunctionPointerType)arg1;
- (_Bool)_registerForProx:(CDUnknownFunctionPointerType)arg1;
- (_Bool)_enableProx:(_Bool)arg1;
- (_Bool)_isProxEnabled;
- (void)cleanupStreaming:(CDUnknownFunctionPointerType)arg1;
- (void)startStreaming:(CDUnknownFunctionPointerType)arg1;
- (void)resetGrape;
- (_Bool)isGrapePowered;
- (_Bool)scheduleSystemWake:(unsigned int)arg1;
- (id)criticalErrorSet:(out unsigned long long *)arg1;
- (_Bool)_setMTReport:(unsigned char)arg1 payloadBuffer:(char *)arg2 bufferSize:(unsigned int)arg3;
- (_Bool)_getMTReport:(unsigned char)arg1 payloadBuffer:(char *)arg2 bufferSize:(unsigned int *)arg3;
- (_Bool)proxErrorDetected;
- (id)orbErrorDetected;
- (_Bool)_grapeCriticalErrorDetected:(id)arg1;
- (id)orbChipID;
- (long long)resetCount;
- (id)bcdVersion;
- (id)constructedFirmwareVersion;
- (unsigned int)multitouchFirmwareVersion;
- (_Bool)_refreshGrapeProperties;
- (void)dealloc;
- (id)init;
- (struct __MTDevice *)_createMTDevice:(unsigned int)arg1;

@end

