//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIView<SBUIPasscodeLockView>, _UIBackdropView;

@interface SUSUIPasscodeEntryView : UIView
{
    UIView *_containerView;
    UIView<SBUIPasscodeLockView> *_passcodeView;
    _UIBackdropView *_blurView;
    _Bool _dismissing;
}

@property(readonly, nonatomic) UIView<SBUIPasscodeLockView> *passcodeLockView; // @synthesize passcodeLockView=_passcodeView;
- (void).cxx_destruct;
- (id)createPasscodeView;
- (void)layoutSubviews;
- (void)updateStatusText;
- (void)setPasscodeViewsToVisible:(_Bool)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (id)initWithFrame:(struct CGRect)arg1;

@end

