//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIApplication.h"

#import "UIApplicationDelegate.h"

@class DemoPlayerViewController, NSString, UIWindow;

@interface DemoApplication : UIApplication <UIApplicationDelegate>
{
    UIWindow *_window;
    DemoPlayerViewController *_playerViewController;
}

- (void).cxx_destruct;
- (void)sendEvent:(id)arg1;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)applicationDidFinishLaunching:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(retain, nonatomic) UIWindow *window;

@end

