//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SBSRemoteAlertHandleObserver.h"
#import "UIApplicationDelegate.h"

@class AuthRemoteAlertViewController, NSDictionary, NSString, SBSRemoteAlertHandle, UIViewController, UIWindow;

@interface CTCarrierSpaceAuthAppDelegate : NSObject <SBSRemoteAlertHandleObserver, UIApplicationDelegate>
{
    UIWindow *_window;
    UIViewController *_rootViewController;
    SBSRemoteAlertHandle *_alertHandle;
    AuthRemoteAlertViewController *_alertViewController;
    NSDictionary *_launchContext;
}

@property(readonly, nonatomic) NSDictionary *launchContext; // @synthesize launchContext=_launchContext;
@property(retain, nonatomic) AuthRemoteAlertViewController *alertViewController; // @synthesize alertViewController=_alertViewController;
@property(retain, nonatomic) UIWindow *window; // @synthesize window=_window;
- (void).cxx_destruct;
- (void)remoteAlertHandleDidDeactivate:(id)arg1;
- (void)applicationWillTerminate:(id)arg1;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)applicationWillEnterForeground:(id)arg1;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)applicationWillResignActive:(id)arg1;
- (_Bool)application:(id)arg1 openURL:(id)arg2 options:(id)arg3;
- (void)application:(id)arg1 didFinishLaunchingSuspendedWithOptions:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

