/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 21, 2018 at 11:42:08 PM Central European Summer Time
* Operating System: Version 11.3.1 (Build 15E302)
* Image Source: /Applications/AppStore.app/Frameworks/AppStoreKit.framework/AppStoreKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <StoreServices/SSMetricsCustomEvent.h>

@class NSArray, NSString;

@interface _TtC11AppStoreKitP33_4E8C15A1165D3F1974B8F5C50AF1595715MetricsLogEvent : SSMetricsCustomEvent

@property (copy,nonatomic) NSArray * arguments; 
@property (copy,nonatomic) NSString * loggerName; 
@property (copy,nonatomic) NSString * message; 
-(NSString *)loggerName;
-(void)setLoggerName:(NSString *)arg1 ;
-(void)setArguments:(NSArray *)arg1 ;
-(id)init;
-(void)setMessage:(NSString *)arg1 ;
-(NSString *)message;
-(id)initWithBodyDictionary:(id)arg1 ;
-(NSArray *)arguments;
@end

