/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 21, 2018 at 11:42:08 PM Central European Summer Time
* Operating System: Version 11.3.1 (Build 15E302)
* Image Source: /Applications/AppStore.app/Frameworks/AppStoreKit.framework/AppStoreKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <AppStoreKit/AppStoreKit.Lockup.h>

@class NSString, _TtC11AppStoreKit10FlowAction, _TtC11AppStoreKit6Lockup;

@interface AppStoreKit.InAppPurchaseLockup : AppStoreKit.Lockup {

	 descriptionText;
	 theme;
	 productAction;
	 isSubscription;
	 parent;

}

@property (readonly,nonatomic) NSString * descriptionText; 
@property (readonly,nonatomic) _TtC11AppStoreKit10FlowAction * productAction; 
@property (readonly,nonatomic) BOOL isSubscription; 
@property (readonly,nonatomic) _TtC11AppStoreKit6Lockup * parent; 
-(_TtC11AppStoreKit10FlowAction *)productAction;
-(BOOL)isSubscription;
-(NSString *)descriptionText;
-(_TtC11AppStoreKit6Lockup *)parent;
@end

