/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 21, 2018 at 11:42:08 PM Central European Summer Time
* Operating System: Version 11.3.1 (Build 15E302)
* Image Source: /Applications/AppStore.app/Frameworks/AppStoreKit.framework/AppStoreKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <AppStoreKit/AppStoreKit.Action.h>

@class NSString, _TtC11AppStoreKit6Action;

@interface AppStoreKit.InAppPurchaseAction : AppStoreKit.Action {

	 productIdentifier;
	 appAdamId;
	 appBundleId;
	 installRequiredAction;
	 minimumShortVersionSupportingInAppPurchaseFlow;
	 appTitle;
	 productTitle;

}

@property (readonly,nonatomic) NSString * productIdentifier; 
@property (readonly,nonatomic) NSString * appBundleId; 
@property (readonly,nonatomic) _TtC11AppStoreKit6Action * installRequiredAction; 
@property (readonly,nonatomic) NSString * minimumShortVersionSupportingInAppPurchaseFlow; 
@property (readonly,nonatomic) NSString * appTitle; 
@property (readonly,nonatomic) NSString * productTitle; 
-(_TtC11AppStoreKit6Action *)installRequiredAction;
-(NSString *)minimumShortVersionSupportingInAppPurchaseFlow;
-(NSString *)productTitle;
-(NSString *)appBundleId;
-(NSString *)productIdentifier;
-(NSString *)appTitle;
@end

