/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 21, 2018 at 11:42:08 PM Central European Summer Time
* Operating System: Version 11.3.1 (Build 15E302)
* Image Source: /Applications/AppStore.app/Frameworks/AppStoreKit.framework/AppStoreKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class _TtC11AppStoreKit6Lockup, NSString, _TtC11AppStoreKit6Action;

@interface AppStoreKit.AppShowcase : NSObject {

	 lockup;
	 descriptionText;
	 video;
	 allowsAutoPlay;
	 type;

}

@property (readonly,nonatomic) _TtC11AppStoreKit6Lockup * lockup; 
@property (readonly,nonatomic) NSString * descriptionText; 
@property (readonly,nonatomic) BOOL allowsAutoPlay; 
@property (readonly,nonatomic) _TtC11AppStoreKit6Action * clickAction; 
@property (readonly,nonatomic) id clickSender; 
-(id)clickSender;
-(BOOL)allowsAutoPlay;
-(NSString *)descriptionText;
-(id)init;
-(_TtC11AppStoreKit6Lockup *)lockup;
-(_TtC11AppStoreKit6Action *)clickAction;
@end

