/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 21, 2018 at 11:42:07 PM Central European Summer Time
* Operating System: Version 11.3.1 (Build 15E302)
* Image Source: /Applications/AppStore.app/Frameworks/AppStoreKit.framework/AppStoreKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <AppStoreKit/ASKAirplaneModeInquiryDelegate.h>

@class NSString, NSURL, NSError;

@interface AppStoreKit.ErrorPresenter : NSObject <ASKAirplaneModeInquiryDelegate> {

	 networkObserver;
	 airplaneModeInquiry;
	 cellularDataInquiry;
	 view;
	 reasonForNoInternet;
	 error;

}

@property (readonly,nonatomic) NSString * title; 
@property (readonly,nonatomic) NSString * message; 
@property (readonly,nonatomic) NSURL * settingsURL; 
@property (copy,nonatomic) NSError * error; 
-(void)airplaneModeInquiryDidObserveChange:(id)arg1 ;
-(NSURL *)settingsURL;
-(void)networkActivityDidBegin;
-(void)networkActivityDidEnd;
-(void)networkReachabilityDidChangeTo:(unsigned)arg1 ;
-(id)init;
-(NSString *)title;
-(void)update;
-(NSString *)message;
-(void)setError:(NSError *)arg1 ;
-(NSError *)error;
@end

