/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 21, 2018 at 11:42:08 PM Central European Summer Time
* Operating System: Version 11.3.1 (Build 15E302)
* Image Source: /Applications/AppStore.app/Frameworks/AppStoreKit.framework/AppStoreKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString;

@interface AppStoreKit.OfferDisplayProperties : NSObject {

	 offerType;
	 adamId;
	 parentAdamId;
	 titles;
	 subtitles;
	 style;
	 environment;
	 tint;
	 isDeletableSystemApp;
	 isFree;
	 hasDiscount;
	 offerLabelStyle;
	 contentRating;
	 offerToken;
	 subscriptionFamilyId;

}

@property (readonly,nonatomic) long long style; 
@property (readonly,nonatomic) long long environment; 
@property (readonly,nonatomic) long long tint; 
@property (readonly,nonatomic) BOOL isDeletableSystemApp; 
@property (readonly,nonatomic) BOOL isFree; 
@property (readonly,nonatomic) BOOL hasDiscount; 
@property (readonly,nonatomic) long long offerLabelStyle; 
@property (readonly,nonatomic) id offerToken; 
@property (readonly,nonatomic) NSString * subscriptionFamilyId; 
-(BOOL)isDeletableSystemApp;
-(BOOL)hasDiscount;
-(long long)offerLabelStyle;
-(id)offerToken;
-(id)init;
-(long long)environment;
-(long long)style;
-(BOOL)isFree;
-(NSString *)subscriptionFamilyId;
-(long long)tint;
@end

