/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 21, 2018 at 11:42:07 PM Central European Summer Time
* Operating System: Version 11.3.1 (Build 15E302)
* Image Source: /Applications/AppStore.app/Frameworks/AppStoreKit.framework/AppStoreKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/LSApplicationWorkspaceObserverProtocol.h>

@protocol OS_dispatch_queue, ASKBag;
@class LSApplicationWorkspace, NSObject, NSMapTable, NSDictionary, NSString;

@interface ASKAppLibrary : NSObject <LSApplicationWorkspaceObserverProtocol> {

	LSApplicationWorkspace* _applicationWorkspace;
	NSObject*<OS_dispatch_queue> _queue;
	id<ASKBag> _bag;
	NSMapTable* _observers;
	NSDictionary* _hideableSystemAppMap;

}

@property (nonatomic,readonly) LSApplicationWorkspace * applicationWorkspace;              //@synthesize applicationWorkspace=_applicationWorkspace - In the implementation block
@property (nonatomic,readonly) NSObject*<OS_dispatch_queue> queue;                         //@synthesize queue=_queue - In the implementation block
@property (nonatomic,readonly) id<ASKBag> bag;                                             //@synthesize bag=_bag - In the implementation block
@property (nonatomic,retain) NSMapTable * observers;                                       //@synthesize observers=_observers - In the implementation block
@property (nonatomic,retain) NSDictionary * hideableSystemAppMap;                          //@synthesize hideableSystemAppMap=_hideableSystemAppMap - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)supportedApplicationTypes;
+(id)adamIdWithApplicationProxy:(id)arg1 hideableSystemAppMap:(id)arg2 ;
-(NSDictionary *)hideableSystemAppMap;
-(id)appsFromApplicationProxies:(id)arg1 ;
-(id)descriptionFromApps:(id)arg1 ;
-(void)notifyObserversOfEvent:(long long)arg1 apps:(id)arg2 ;
-(id)initWithBag:(id)arg1 ;
-(void)fetchAppsWithAdamIds:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)addObserver:(id)arg1 action:(/*^block*/id)arg2 ;
-(void)setHideableSystemAppMap:(NSDictionary *)arg1 ;
-(void)dealloc;
-(void)removeObserver:(id)arg1 ;
-(void)willEnterForeground:(id)arg1 ;
-(NSObject*<OS_dispatch_queue>)queue;
-(void)setObservers:(NSMapTable *)arg1 ;
-(NSMapTable *)observers;
-(id<ASKBag>)bag;
-(void)applicationInstallsDidStart:(id)arg1 ;
-(void)applicationInstallsDidChange:(id)arg1 ;
-(void)applicationsWillInstall:(id)arg1 ;
-(void)applicationsDidInstall:(id)arg1 ;
-(void)applicationsDidFailToInstall:(id)arg1 ;
-(void)applicationsDidUninstall:(id)arg1 ;
-(void)applicationsDidFailToUninstall:(id)arg1 ;
-(void)applicationInstallsDidCancel:(id)arg1 ;
-(BOOL)observeLaunchProhibitedApps;
-(LSApplicationWorkspace *)applicationWorkspace;
@end

