/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, August 21, 2018 at 11:42:07 PM Central European Summer Time
* Operating System: Version 11.3.1 (Build 15E302)
* Image Source: /Applications/AppStore.app/Frameworks/AppStoreKit.framework/AppStoreKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_dispatch_queue;
@class NSObject, ACAccountStore, AAUIProfilePictureStore, NSString;

@interface ASKProfilePictureStore : NSObject {

	BOOL _hasRequestedImages;
	NSObject*<OS_dispatch_queue> _accessQueue;
	NSObject*<OS_dispatch_queue> _notificationQueue;
	ACAccountStore* _accountStore;
	AAUIProfilePictureStore* _profilePictureStore;
	NSString* _primaryAccountName;
	NSString* _storeAccountName;

}

@property (nonatomic,retain) NSObject*<OS_dispatch_queue> accessQueue;                    //@synthesize accessQueue=_accessQueue - In the implementation block
@property (nonatomic,retain) NSObject*<OS_dispatch_queue> notificationQueue;              //@synthesize notificationQueue=_notificationQueue - In the implementation block
@property (nonatomic,retain) ACAccountStore * accountStore;                               //@synthesize accountStore=_accountStore - In the implementation block
@property (nonatomic,retain) AAUIProfilePictureStore * profilePictureStore;               //@synthesize profilePictureStore=_profilePictureStore - In the implementation block
@property (nonatomic,copy) NSString * primaryAccountName;                                 //@synthesize primaryAccountName=_primaryAccountName - In the implementation block
@property (nonatomic,copy) NSString * storeAccountName;                                   //@synthesize storeAccountName=_storeAccountName - In the implementation block
@property (assign) BOOL hasRequestedImages;                                               //@synthesize hasRequestedImages=_hasRequestedImages - In the implementation block
+(id)sharedStore;
-(void)appleAccountsDidChange:(id)arg1 ;
-(void)storeAccountsDidChange:(id)arg1 ;
-(void)profilePictureStoreDidChange:(id)arg1 ;
-(void)configureProfilePictureStoreAndNotifyIfNeeded;
-(NSString *)primaryAccountName;
-(AAUIProfilePictureStore *)profilePictureStore;
-(void)setPrimaryAccountName:(NSString *)arg1 ;
-(void)setProfilePictureStore:(AAUIProfilePictureStore *)arg1 ;
-(void)notifyIfNeeded;
-(BOOL)hasRequestedImages;
-(void)_markAsHasRequestedImages;
-(id)_profilePictureForFamilyMember:(id)arg1 withProfilePictureStore:(id)arg2 ;
-(void)setHasRequestedImages:(BOOL)arg1 ;
-(void)profilePictureForAccountOwnerWithoutMonogramFallbackWithCompletion:(/*^block*/id)arg1 ;
-(void)profilePictureWithMonogramFallbackForFamilyMember:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)profilePictureWithMonogramFallbackForFamilyMembers:(id)arg1 completion:(/*^block*/id)arg2 ;
-(id)init;
-(void)dealloc;
-(void)setStoreAccountName:(NSString *)arg1 ;
-(ACAccountStore *)accountStore;
-(void)setAccessQueue:(NSObject*<OS_dispatch_queue>)arg1 ;
-(NSObject*<OS_dispatch_queue>)accessQueue;
-(NSString *)storeAccountName;
-(NSObject*<OS_dispatch_queue>)notificationQueue;
-(void)setNotificationQueue:(NSObject*<OS_dispatch_queue>)arg1 ;
-(void)setAccountStore:(ACAccountStore *)arg1 ;
@end

