//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class DCDocumentManager, DCManagedUpload, NSArray, NSDictionary, NSError, NSString, NSURL, NSURLSessionDownloadTask;

@protocol DCDocumentManagerDelegate

@optional
- (void)documentManager:(DCDocumentManager *)arg1 didStartUploadingItemAtPath:(NSString *)arg2 upload:(DCManagedUpload *)arg3;
- (void)documentManager:(DCDocumentManager *)arg1 didStartDownloadingItemAtPath:(NSString *)arg2 downloadTask:(NSURLSessionDownloadTask *)arg3;
- (void)documentManager:(DCDocumentManager *)arg1 didFailToUpdateItemAtPath:(NSString *)arg2 error:(NSError *)arg3;
- (void)documentManager:(DCDocumentManager *)arg1 didUpdateAttributesOfItemAtPath:(NSString *)arg2 attributes:(NSDictionary *)arg3;
- (void)documentManager:(DCDocumentManager *)arg1 didUpdateThumbnailOfFileAtPath:(NSString *)arg2 url:(NSURL *)arg3;
- (void)documentManager:(DCDocumentManager *)arg1 didUpdateContentsOfFileAtPath:(NSString *)arg2;
- (void)documentManager:(DCDocumentManager *)arg1 didUpdateContentsOfDirectoryAtPath:(NSString *)arg2 contents:(NSArray *)arg3;
- (void)documentManager:(DCDocumentManager *)arg1 didUpdateConnectionStatus:(_Bool)arg2;
@end

