//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIButton, UILabel;

@interface SVErrorView : UIView
{
    UILabel *_titleLabel;
    UILabel *_detailLabel;
    UIButton *_retryButton;
}

@property(nonatomic) __weak UIButton *retryButton; // @synthesize retryButton=_retryButton;
@property(nonatomic) __weak UILabel *detailLabel; // @synthesize detailLabel=_detailLabel;
@property(nonatomic) __weak UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void).cxx_destruct;
- (void)traitCollectionDidChange:(id)arg1;
- (id)init;

@end

