//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SVMetadataItem, SVProgressView, SVViewOptionsHeaderView, UIScrollView;

@protocol SVFilesChildViewController <NSObject>
@property(readonly, nonatomic) UIScrollView *scrollView;
@property(readonly, nonatomic) SVViewOptionsHeaderView *viewOptionsHeaderView;
- (void)flashToEmphasizeItem:(SVMetadataItem *)arg1 completionHandler:(void (^)(void))arg2;
- (void)scrollItemToVisible:(SVMetadataItem *)arg1 completionHandler:(void (^)(void))arg2;
- (void)cancelDownloadProgressForItem:(SVMetadataItem *)arg1;
- (SVProgressView *)showDownloadProgressForItem:(SVMetadataItem *)arg1;
@end

