//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class NSLayoutConstraint, SVListProgressView, UIImageView, UILabel;

@interface SVFileTableViewCell : UITableViewCell
{
    _Bool _enabled;
    UILabel *_nameLabel;
    UILabel *_detailLabel;
    UIImageView *_iconImageView;
    SVListProgressView *_downloadProgressView;
    long long _itemType;
    UIImageView *_badgeImageView;
    NSLayoutConstraint *_badgeViewTrailingConstraint;
    NSLayoutConstraint *_badgeViewBottomConstraint;
}

@property(nonatomic) __weak NSLayoutConstraint *badgeViewBottomConstraint; // @synthesize badgeViewBottomConstraint=_badgeViewBottomConstraint;
@property(nonatomic) __weak NSLayoutConstraint *badgeViewTrailingConstraint; // @synthesize badgeViewTrailingConstraint=_badgeViewTrailingConstraint;
@property(nonatomic) __weak UIImageView *badgeImageView; // @synthesize badgeImageView=_badgeImageView;
@property(nonatomic) long long itemType; // @synthesize itemType=_itemType;
@property(nonatomic) _Bool enabled; // @synthesize enabled=_enabled;
@property(retain, nonatomic) SVListProgressView *downloadProgressView; // @synthesize downloadProgressView=_downloadProgressView;
@property(nonatomic) __weak UIImageView *iconImageView; // @synthesize iconImageView=_iconImageView;
@property(nonatomic) __weak UILabel *detailLabel; // @synthesize detailLabel=_detailLabel;
@property(nonatomic) __weak UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
- (void).cxx_destruct;
- (void)setDownloadProgressViewHidden:(_Bool)arg1 animated:(_Bool)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)setBadgeImage:(id)arg1 animated:(_Bool)arg2;
- (void)updateFonts;
- (void)awakeFromNib;
- (void)updateBadgeViewConstraints;
- (void)layoutSubviews;

@end

