//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <ServerDocsClient/SVProgressView.h>

@class CALayer, CAShapeLayer, UIImageView;

@interface SVGridProgressView : SVProgressView
{
    _Bool _onLightBackground;
    _Bool _completed;
    CAShapeLayer *_backgroundRingLayer;
    CAShapeLayer *_progressLayer;
    CALayer *_maskLayer;
    UIImageView *_progressBlurredImageView;
    CAShapeLayer *_checkmarkLayer;
    CALayer *_progressLayerMask;
}

@property(retain, nonatomic) CALayer *progressLayerMask; // @synthesize progressLayerMask=_progressLayerMask;
@property(retain, nonatomic) CAShapeLayer *checkmarkLayer; // @synthesize checkmarkLayer=_checkmarkLayer;
@property(retain, nonatomic) UIImageView *progressBlurredImageView; // @synthesize progressBlurredImageView=_progressBlurredImageView;
@property(retain, nonatomic) CALayer *maskLayer; // @synthesize maskLayer=_maskLayer;
@property(retain, nonatomic) CAShapeLayer *progressLayer; // @synthesize progressLayer=_progressLayer;
@property(retain, nonatomic) CAShapeLayer *backgroundRingLayer; // @synthesize backgroundRingLayer=_backgroundRingLayer;
@property(nonatomic) _Bool completed; // @synthesize completed=_completed;
@property(nonatomic) _Bool onLightBackground; // @synthesize onLightBackground=_onLightBackground;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)setBackgroundImage:(id)arg1;
- (struct CGRect)_backgroundRingLayerPathFrame;
- (double)_backgroundRingLineWidth;
- (struct CGRect)_insetFrame;
- (void)updateLayerPropertiesAnimated:(_Bool)arg1;
- (void)prepareForInterfaceBuilder;

@end

