//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <ServerDocsClient/SVProgressView.h>

@class CAShapeLayer;

@interface SVListProgressView : SVProgressView
{
    _Bool _hidesStopButton;
    CAShapeLayer *_backgroundRingLayer;
    CAShapeLayer *_progressLayer;
    CAShapeLayer *_stopButtonLayer;
}

@property(retain, nonatomic) CAShapeLayer *stopButtonLayer; // @synthesize stopButtonLayer=_stopButtonLayer;
@property(retain, nonatomic) CAShapeLayer *progressLayer; // @synthesize progressLayer=_progressLayer;
@property(retain, nonatomic) CAShapeLayer *backgroundRingLayer; // @synthesize backgroundRingLayer=_backgroundRingLayer;
@property(nonatomic) _Bool hidesStopButton; // @synthesize hidesStopButton=_hidesStopButton;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)updateLayerPropertiesAnimated:(_Bool)arg1;

@end

