//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSSet;

@interface Blacklist : NSObject
{
    NSSet *_exactBundleIDs;
    NSSet *_prefixBundleIDs;
    NSSet *_exceptions;
}

@property(retain, nonatomic) NSSet *exceptions; // @synthesize exceptions=_exceptions;
@property(retain, nonatomic) NSSet *prefixBundleIDs; // @synthesize prefixBundleIDs=_prefixBundleIDs;
@property(retain, nonatomic) NSSet *exactBundleIDs; // @synthesize exactBundleIDs=_exactBundleIDs;
- (void).cxx_destruct;

@end

