//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface DAApplicationVersion : NSObject
{
    NSString *_shortVersion;
    NSString *_bundleVersion;
}

@property(retain, nonatomic) NSString *bundleVersion; // @synthesize bundleVersion=_bundleVersion;
@property(retain, nonatomic) NSString *shortVersion; // @synthesize shortVersion=_shortVersion;
- (void).cxx_destruct;
- (_Bool)isEqual:(id)arg1;

@end

