//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "DKDiagnosticInputs.h"

@class Blacklist, NSDate, NSString;

@interface SystemStabilityInputs : NSObject <DKDiagnosticInputs>
{
    Blacklist *_blacklist;
    NSDate *_minDate;
    NSDate *_maxDate;
    unsigned long long _maxNumberOfLogFiles;
}

@property(nonatomic) unsigned long long maxNumberOfLogFiles; // @synthesize maxNumberOfLogFiles=_maxNumberOfLogFiles;
@property(retain, nonatomic) NSDate *maxDate; // @synthesize maxDate=_maxDate;
@property(retain, nonatomic) NSDate *minDate; // @synthesize minDate=_minDate;
@property(retain, nonatomic) Blacklist *blacklist; // @synthesize blacklist=_blacklist;
- (void).cxx_destruct;
- (id)blacklistFromParameters:(id)arg1;
- (_Bool)validateAndInitializeParameters:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

