//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DKDiagnosticController.h"

@interface EnhancedCellularCallPerformanceController : DKDiagnosticController
{
    _Bool _copyForSyncing;
}

@property(nonatomic) _Bool copyForSyncing; // @synthesize copyForSyncing=_copyForSyncing;
- (id)_archiveFiles:(id)arg1;
- (id)_extractFilePaths:(id)arg1;
- (void)start;
- (void)setupWithInputs:(id)arg1 responder:(id)arg2;

@end

