//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface ComponentOrientationSpecification : NSObject
{
    float _lowerBoundOffsetThresholdX;
    float _upperBoundOffsetThresholdX;
    float _lowerBoundOffsetThresholdY;
    float _upperBoundOffsetThresholdY;
    float _lowerBoundOffsetThresholdZ;
    float _upperBoundOffsetThresholdZ;
    float _zeroRangeThreshold;
    float _degreesShiftRangeThreshold;
}

@property(nonatomic) float degreesShiftRangeThreshold; // @synthesize degreesShiftRangeThreshold=_degreesShiftRangeThreshold;
@property(nonatomic) float zeroRangeThreshold; // @synthesize zeroRangeThreshold=_zeroRangeThreshold;
@property(nonatomic) float upperBoundOffsetThresholdZ; // @synthesize upperBoundOffsetThresholdZ=_upperBoundOffsetThresholdZ;
@property(nonatomic) float lowerBoundOffsetThresholdZ; // @synthesize lowerBoundOffsetThresholdZ=_lowerBoundOffsetThresholdZ;
@property(nonatomic) float upperBoundOffsetThresholdY; // @synthesize upperBoundOffsetThresholdY=_upperBoundOffsetThresholdY;
@property(nonatomic) float lowerBoundOffsetThresholdY; // @synthesize lowerBoundOffsetThresholdY=_lowerBoundOffsetThresholdY;
@property(nonatomic) float upperBoundOffsetThresholdX; // @synthesize upperBoundOffsetThresholdX=_upperBoundOffsetThresholdX;
@property(nonatomic) float lowerBoundOffsetThresholdX; // @synthesize lowerBoundOffsetThresholdX=_lowerBoundOffsetThresholdX;

@end

