//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "EURLogGenerator.h"

@class ClassIndex, NSString;

@interface EURLogGenerator2 : EURLogGenerator
{
    NSString *pListName;
    ClassIndex *cIndex;
}

- (id)getStartCommand;
- (id)generateLogUsingState:(id)arg1;
- (id)getDisplayFromState:(id)arg1;
- (void)printDict:(id)arg1;
- (id)processTemplate:(id)arg1;
- (void)updateState:(id)arg1 withData:(id)arg2;
- (void)updateWithData:(id)arg1;
- (void)dealloc;
- (id)initWithPListName:(id)arg1 cIndexObj:(id)arg2;

@end

