//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UNNotificationContentExtension.h"

@class CADisplayLink, MTNotificationView, NSDate, NSString, UIColor;

@interface MTNotificationViewController : UIViewController <UNNotificationContentExtension>
{
    NSDate *_countDownDate;
    MTNotificationView *_noteView;
    CADisplayLink *_displayLink;
}

@property(retain, nonatomic) CADisplayLink *displayLink; // @synthesize displayLink=_displayLink;
@property(retain, nonatomic) MTNotificationView *noteView; // @synthesize noteView=_noteView;
@property(retain, nonatomic) NSDate *countDownDate; // @synthesize countDownDate=_countDownDate;
- (void).cxx_destruct;
- (void)_teardownDisplayLink;
- (void)_setupDisplayLink;
- (void)_updateCountDown:(id)arg1;
- (void)didReceiveNotification:(id)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) struct CGRect mediaPlayPauseButtonFrame;
@property(readonly, copy, nonatomic) UIColor *mediaPlayPauseButtonTintColor;
@property(readonly, nonatomic) unsigned long long mediaPlayPauseButtonType;
@property(readonly) Class superclass;

@end

